#region References

using NUnit.Framework;

#endregion

namespace Cornerstone.Generators.UnitTests.Avalonia;

[TestFixture]
public class AttachedPropertyTests : GeneratorUnitTest
{
	#region Methods

	[Test]
	public void Attached()
	{
		var input = """
					public partial class Test : CornerstoneControl
					{
						[AttachedProperty]
						public partial int Bar { get; set; }
					}
					""";

		// Generated Code - Expected
		var expected = new[]
		{
			"""
			using System;
			using System.Collections.Generic;
			// <auto-generated>
			// Auto-generated by Cornerstone.Generators
			// </auto-generated>
			partial class Test
			{
				public static readonly global::Avalonia.AttachedProperty<global::System.Int32> BarProperty = global::Avalonia.AvaloniaProperty.RegisterAttached<global::Test, global::Test, global::System.Int32>(nameof(Bar));
				public partial global::System.Int32 Bar
				{
					get => GetValue(BarProperty);
					set => SetValue(BarProperty, value);
				}
			}
			""",
			"""
			// <auto-generated>
			// Auto-generated by Cornerstone.Generators
			// </auto-generated>
			internal static partial class __CornerstoneSourceReflectorInitializer
			{
				[global::System.Runtime.CompilerServices.ModuleInitializer]
				public static void Initialize()
				{
				}
			}
			"""
		};
		// Generated Code - /Expected

		ValidateSource(input, expected);
	}

	#endregion
}