#region References

using NUnit.Framework;

#endregion

namespace Cornerstone.Generators.UnitTests.Avalonia;

[TestFixture]
public class DirectPropertyTests : GeneratorUnitTest
{
	#region Methods

	[Test]
	public void DirectGetAndSet()
	{
		var input = """
					public partial class Test : CornerstoneControl
					{
						[DirectProperty]
						public int Bar { get; set; }
					}
					""";

		// Generated Code - Expected
		var expected = new[]
		{
			"""
			using System;
			using System.Collections.Generic;
			// <auto-generated>
			// Auto-generated by Cornerstone.Generators
			// </auto-generated>
			partial class Test
			{
				public static readonly global::Avalonia.DirectProperty<global::Test, global::System.Int32> BarProperty = global::Avalonia.AvaloniaProperty.RegisterDirect<global::Test, global::System.Int32>(nameof(Bar), getter: x => x.Bar, setter: (x, v) => x.Bar = v);
			}
			""",
			"""
			// <auto-generated>
			// Auto-generated by Cornerstone.Generators
			// </auto-generated>
			internal static partial class __CornerstoneSourceReflectorInitializer
			{
				[global::System.Runtime.CompilerServices.ModuleInitializer]
				public static void Initialize()
				{
				}
			}
			"""
		};
		// Generated Code - /Expected

		ValidateSource(input, expected);
	}

	[Test]
	public void DirectGetOnly()
	{
		var input = """
					public partial class Test : CornerstoneControl
					{
						[DirectProperty]
						public int Bar { get; }
					}
					""";

		// Generated Code - Expected
		var expected = new[]
		{
			"""
			using System;
			using System.Collections.Generic;
			// <auto-generated>
			// Auto-generated by Cornerstone.Generators
			// </auto-generated>
			partial class Test
			{
				public static readonly global::Avalonia.DirectProperty<global::Test, global::System.Int32> BarProperty = global::Avalonia.AvaloniaProperty.RegisterDirect<global::Test, global::System.Int32>(nameof(Bar), getter: x => x.Bar);
			}
			""",
			"""
			// <auto-generated>
			// Auto-generated by Cornerstone.Generators
			// </auto-generated>
			internal static partial class __CornerstoneSourceReflectorInitializer
			{
				[global::System.Runtime.CompilerServices.ModuleInitializer]
				public static void Initialize()
				{
				}
			}
			"""
		};
		// Generated Code - /Expected

		ValidateSource(input, expected);
	}

	#endregion
}