#region References

using Microsoft.VisualStudio.TestTools.UnitTesting;

#endregion

namespace Cornerstone.Generators.UnitTests.Avalonia;

[TestClass]
public class DirectPropertyTests : GeneratorUnitTest
{
	#region Methods

	[TestMethod]
	public void DirectGetAndSet()
	{
		var input = """
					public partial class Test : CornerstoneControl
					{
						[DirectProperty]
						public partial int Bar { get; set; }
					}
					""";

		// Generated Code - Expected
		var expected = new[]
		{
			"""
			using System;
			using System.Collections.Generic;
			// <auto-generated>
			// Auto-generated by Cornerstone.Generators
			// </auto-generated>
			partial class Test
			{
				private global::System.Int32 _bar;
				public static readonly global::Avalonia.DirectProperty<global::Test, global::System.Int32> BarProperty = global::Avalonia.AvaloniaProperty.RegisterDirect<global::Test, global::System.Int32>(nameof(Bar), getter: x => x._bar, setter: (x, v) => x.Bar = v);
				public partial global::System.Int32 Bar
				{
					get => _bar;
					set => SetAndRaise(BarProperty, ref _bar, value);
				}
			}
			""",
			"""
			// <auto-generated>
			// Auto-generated by Cornerstone.Generators
			// </auto-generated>
			namespace TestCompilation
			{
				public static partial class CornerstoneGenerated
				{
					[global::System.Runtime.CompilerServices.ModuleInitializer]
					public static void Initialize()
					{
					}
				}
			}
			"""
		};
		// Generated Code - /Expected

		ValidateSource(input, expected);
	}

	[TestMethod]
	public void DirectGetOnly()
	{
		var input = """
					public partial class Test : CornerstoneControl
					{
						[DirectProperty]
						public partial int Bar { get; }
					}
					""";

		// Generated Code - Expected
		var expected = new[]
		{
			"""
			using System;
			using System.Collections.Generic;
			// <auto-generated>
			// Auto-generated by Cornerstone.Generators
			// </auto-generated>
			partial class Test
			{
				private global::System.Int32 _bar;
				public static readonly global::Avalonia.DirectProperty<global::Test, global::System.Int32> BarProperty = global::Avalonia.AvaloniaProperty.RegisterDirect<global::Test, global::System.Int32>(nameof(Bar), getter: x => x._bar);
				public partial global::System.Int32 Bar
				{
					get => _bar;
				}
			}
			""",
			"""
			// <auto-generated>
			// Auto-generated by Cornerstone.Generators
			// </auto-generated>
			namespace TestCompilation
			{
				public static partial class CornerstoneGenerated
				{
					[global::System.Runtime.CompilerServices.ModuleInitializer]
					public static void Initialize()
					{
					}
				}
			}
			"""
		};
		// Generated Code - /Expected

		ValidateSource(input, expected);
	}

	[TestMethod]
	public void DirectPrivateSet()
	{
		var input = """
					public partial class Test : CornerstoneControl
					{
						[DirectProperty]
						public partial double Percentage { get; private set; }
					}
					""";

		// Generated Code - Expected
		var expected = new[]
		{
			"""
			using System;
			using System.Collections.Generic;
			// <auto-generated>
			// Auto-generated by Cornerstone.Generators
			// </auto-generated>
			partial class Test
			{
				private global::System.Double _percentage;
				public static readonly global::Avalonia.DirectProperty<global::Test, global::System.Double> PercentageProperty = global::Avalonia.AvaloniaProperty.RegisterDirect<global::Test, global::System.Double>(nameof(Percentage), getter: x => x._percentage, setter: (x, v) => x.Percentage = v);
				public partial global::System.Double Percentage
				{
					get => _percentage;
					private set => SetAndRaise(PercentageProperty, ref _percentage, value);
				}
			}
			""",
			"""
			// <auto-generated>
			// Auto-generated by Cornerstone.Generators
			// </auto-generated>
			namespace TestCompilation
			{
				public static partial class CornerstoneGenerated
				{
					[global::System.Runtime.CompilerServices.ModuleInitializer]
					public static void Initialize()
					{
					}
				}
			}
			"""
		};
		// Generated Code - /Expected

		ValidateSource(input, expected);
	}

	[TestMethod]
	public void DirectNonPartialCustomBodyRegistersOnly()
	{
		var input = """
					public partial class Test : CornerstoneControl
					{
						private int _storage;

						[DirectProperty]
						public int Bar
						{
							get => _storage;
							set => SetAndRaise(BarProperty, ref _storage, value);
						}
					}
					""";

		// Generated Code - Expected
		var expected = new[]
		{
			"""
			using System;
			using System.Collections.Generic;
			// <auto-generated>
			// Auto-generated by Cornerstone.Generators
			// </auto-generated>
			partial class Test
			{
				public static readonly global::Avalonia.DirectProperty<global::Test, global::System.Int32> BarProperty = global::Avalonia.AvaloniaProperty.RegisterDirect<global::Test, global::System.Int32>(nameof(Bar), getter: x => x.Bar, setter: (x, v) => x.Bar = v);
			}
			""",
			"""
			// <auto-generated>
			// Auto-generated by Cornerstone.Generators
			// </auto-generated>
			namespace TestCompilation
			{
				public static partial class CornerstoneGenerated
				{
					[global::System.Runtime.CompilerServices.ModuleInitializer]
					public static void Initialize()
					{
					}
				}
			}
			"""
		};
		// Generated Code - /Expected

		ValidateSource(input, expected);
	}

	#endregion
}
