<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<AssemblyTitle>Cornerstone.Mapsui</AssemblyTitle>
		<RootNamespace>Cornerstone.Mapsui</RootNamespace>
		<DefineConstants>$(DefineConstants);__CORNERSTONE__</DefineConstants>
		<NoWarn>$(NoWarn);CS8632;IDE0005;IDE0055</NoWarn>
	</PropertyGroup>
	<ItemGroup>
		<ProjectReference Include="..\..\Cornerstone.Presentation\Cornerstone.Presentation.csproj" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="Mapsui" Version="5.1.0" />
		<PackageReference Include="Mapsui.Rendering.Skia" Version="5.1.0" />
		<PackageReference Include="Mapsui.Tiling" Version="5.1.0" />
		<PackageReference Include="SkiaSharp" Version="3.119.4" />
	</ItemGroup>
</Project>
