<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>Library</OutputType>
		<TargetFrameworks>net10.0</TargetFrameworks>
		<IsPackable>false</IsPackable>
	</PropertyGroup>
	<ItemGroup>
		<None Remove="Parsing\Fragments\GetParentTagNameEmpty.xml" />
		<None Remove="Parsing\Fragments\ShouldGetParentTagNameAtLevelOneLevel.xml" />
		<None Remove="Parsing\Fragments\ShouldGetParentTagNameAtLevelOneLevelWithCDATA.xml" />
		<None Remove="Parsing\Fragments\ShouldGetParentTagNameAtLevelOneLevelWithComment.xml" />
		<None Remove="Parsing\Fragments\ShouldGetParentTagNameAtLevelTwoLevel.xml" />
		<None Remove="Parsing\Fragments\ShouldGetParentTagNameAtLevelTwoLevelWithCDATA.xml" />
		<None Remove="Parsing\Fragments\ShouldGetParentTagNameAtLevelTwoLevelWithComment.xml" />
		<None Remove="Parsing\Test.xml" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Avalonia" Version="$(AvaloniaVersion)" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.9.0" />
		<PackageReference Include="MSTest.TestAdapter" Version="4.4.0" />
		<PackageReference Include="MSTest.TestFramework" Version="4.4.0" />
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Include="Parsing\Fragments\ShouldGetParentTagNameAtLevelTwoLevel.xml" />
		<EmbeddedResource Include="Parsing\Fragments\ShouldGetParentTagNameAtLevelTwoLevelWithCDATA.xml" />
		<EmbeddedResource Include="Parsing\Fragments\ShouldGetParentTagNameAtLevelOneLevelWithCDATA.xml" />
		<EmbeddedResource Include="Parsing\Fragments\ShouldGetParentTagNameAtLevelTwoLevelWithComment.xml" />
		<EmbeddedResource Include="Parsing\Fragments\ShouldGetParentTagNameAtLevelOneLevelWithComment.xml" />
		<EmbeddedResource Include="Parsing\Fragments\ShouldGetParentTagNameAtLevelOneLevel.xml" />
		<EmbeddedResource Include="Test.bmp" />
		<AvaloniaResource Include="Test.bmp" />
		<AvaloniaXaml Include="Test.xaml" />
		<AvaloniaXaml Include="TestCompiledTheme.xaml" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Cornerstone.VisualStudio.Core\Cornerstone.VisualStudio.Core.csproj" />
		<ProjectReference Include="..\Cornerstone.VisualStudio.EditorHost\Cornerstone.VisualStudio.EditorHost.csproj" />
		<ProjectReference Include="..\Cornerstone.VisualStudio.Protocol\Cornerstone.VisualStudio.Protocol.csproj" />
		<ProjectReference Include="..\Cornerstone.VisualStudio.EditorHost\Cornerstone.VisualStudio.EditorHost.csproj" />
		<ProjectReference Include="..\TestAssembly1\TestAssembly1.csproj" Aliases="A1" />
		<ProjectReference Include="..\TestAssembly2\TestAssembly2.csproj" Aliases="A2" />
	</ItemGroup>
</Project>