#region References

using Cornerstone.Testing;

#endregion

namespace Cornerstone.Generators.UnitTests.Profiling;

public class ProfilingTests : GeneratorUnitTest
{
	#region Methods

	//[Test]
	public void ProfileMethodAttribute()
	{
		var source = """
					namespace Cornerstone.Test.Models;

					public class Sample
					{
						public void Process()
						{
							System.Console.WriteLine("Inside Method...");
						}
					}
					
					public class Sample
					{
						public void Process()
						{
							using var timed = profiler?.Start(nameof(Process));
							System.Console.WriteLine("Inside Method...");
						}
					}
					
					public static class Test
					{
						public static void Run()
						{
							var sample = new Sample();
							sample.Method();
						}
					}
					""";

		// Generated Code - Expected
		var expected = new[]
		{
			"""
			// <auto-generated>
			// Auto-generated by Cornerstone.Generators
			// </auto-generated>
			internal static partial class __CornerstoneSourceReflectorInitializer
			{
				[global::System.Runtime.CompilerServices.ModuleInitializer]
				public static void Initialize()
				{
				}
			}
			""",
			"""
			// <auto-generated />
			// Profiling interceptors generated by ProfilingGenerator
			using System;
			using System.Diagnostics;
			using System.Runtime.CompilerServices;
			
			#pragma warning disable CS0618 // suppress obsolete if needed
			
			namespace System.Runtime.CompilerServices
			{
			    [global::System.CodeDom.Compiler.GeneratedCode("ProfilingGenerator", "1.0")]
			    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
			    file sealed class InterceptsLocationAttribute : Attribute
			    {
			        public InterceptsLocationAttribute(int version, string data) { }
			    }
			}
			
			namespace GeneratedInterceptors
			{
				internal static class ProfilingInterceptors
				{
					[global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "OpFRoMmVt6Y8W0IzkVohcHMCAAA=")]
					public static void Intercept_Method(this global::Cornerstone.Test.Models.Sample instance)
					{
						var sw = Stopwatch.StartNew();
						try
						{
							instance.Method();
						}
						finally
						{
							sw.Stop();
							Console.WriteLine($"Method Method took {sw.ElapsedMilliseconds} ms");
						}
					}
				}
			}
			"""
		};
		// Generated Code - /Expected

		var result = ValidateSource(source, expected);
		var actual = ExecuteAndCaptureOutput(result, "Test", "Run", "Cornerstone.Test.Models");
		actual.ConsoleOutput.Dump();
		AreEqual("Inside Method...", actual.ConsoleOutput);
	}

	#endregion
}