<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>net10.0-windows10.0.26100.0</TargetFrameworks>
		<AssemblyTitle>Cornerstone.Automation</AssemblyTitle>
		<PackageId>Cornerstone.Automation</PackageId>
		<SignAssembly>true</SignAssembly>
	</PropertyGroup>
	<Import Project="..\Package.props" />
	<ItemGroup>
		<EmbeddedResource Include="Cornerstone.Automation.js" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="Interop.UIAutomationClient" Version="10.19041.0" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\Cornerstone\Cornerstone.csproj" />
	</ItemGroup>
	<ItemGroup>
		<InternalsVisibleTo Include="Cornerstone.AutomationTests, PublicKey=0024000004800000940000000602000000240000525341310004000001000100f97abdc5a6bc1880e495fb5575d8c7758e32b31d901068015d0e4f9d21dfa2d3eda859956e585ebc5d62066957face3530698eaa1eace45a9175da66211e9fff0deb7b686e01743a9a1acee9f42b8edf341c4f97a8212006a5ac0a6c211bc8206dc87f190f890ff1d041c9eb3eda3bb863240775b8ef2580ec4bca96ac0365d8" />
	</ItemGroup>
</Project>