// <auto-generated />

#region References

using Cornerstone.Storage.Sql.Data;
using Cornerstone.Storage.Sql.Migrations;

#endregion

namespace Cornerstone.Sample.Storage.Migrations;

public partial class Snapshot_20260914120000_Initial : SchemaSnapshot
{
	#region Constructors

	public Snapshot_20260914120000_Initial()
	{
		var accounts = AddTable("Accounts", "");
		accounts.Columns.Add(CreateColumn("AddressId", "System.Int64", 0, false, false, false, false, -1, null));
		accounts.Columns.Add(CreateColumn("Id", "System.Int32", 0, false, true, true, false, 0, null));
		accounts.Columns.Add(CreateColumn("SyncId", "System.Guid", 0, false, false, false, true, 0, null));
		accounts.Columns.Add(CreateColumn("AddressSyncId", "System.Guid", 1, false, false, false, false, -1, null));
		accounts.Columns.Add(CreateColumn("CreatedOn", "System.DateTime", 2, false, false, false, false, -1, null));
		accounts.Columns.Add(CreateColumn("CustomerId", "System.Int32", 3, false, false, false, false, -1, null));
		accounts.Columns.Add(CreateColumn("CustomerSyncId", "System.Guid", 4, false, false, false, false, -1, null));
		accounts.Columns.Add(CreateColumn("EmailAddress", "System.String", 5, false, false, false, false, -1, null));
		accounts.Columns.Add(CreateColumn("IsDeleted", "System.Boolean", 7, false, false, false, false, -1, null));
		accounts.Columns.Add(CreateColumn("LastLoginDate", "System.DateTime", 8, false, false, false, false, -1, null));
		accounts.Columns.Add(CreateColumn("ModifiedOn", "System.DateTime", 9, false, false, false, false, -1, null));
		accounts.Columns.Add(CreateColumn("Name", "System.String", 10, false, false, false, false, -1, null));
		accounts.Columns.Add(CreateColumn("Picture", "System.String", 11, false, false, false, false, -1, null));
		accounts.Columns.Add(CreateColumn("Roles", "System.String", 12, false, false, false, false, -1, null));
		accounts.Columns.Add(CreateColumn("Status", "Cornerstone.Sample.Models.AccountStatus", 13, false, false, false, false, -1, null));
		accounts.Columns.Add(CreateColumn("TimeZoneId", "System.String", 15, false, false, false, false, -1, null));
		accounts.Indexes.Add(CreateIndex("IX_Accounts_LastLoginDate", false, "LastLoginDate"));
		accounts.Indexes.Add(CreateIndex("IX_Accounts_ModifiedOn", false, "ModifiedOn"));
		accounts.Indexes.Add(CreateIndex("IX_Accounts_SyncId", true, "SyncId"));
		accounts.ForeignKeys.Add(CreateForeignKey("FK_Accounts_Addresses_AddressId", "Addresses", "Id", "AddressId"));

		var addresses = AddTable("Addresses", "");
		addresses.Columns.Add(CreateColumn("AccuracyMeters", "System.Single", 0, false, false, false, false, -1, null));
		addresses.Columns.Add(CreateColumn("Id", "System.Int64", 0, false, true, true, false, 0, null));
		addresses.Columns.Add(CreateColumn("SyncId", "System.Guid", 0, false, false, false, true, 0, null));
		addresses.Columns.Add(CreateColumn("City", "System.String", 1, false, false, false, false, -1, null));
		addresses.Columns.Add(CreateColumn("CreatedOn", "System.DateTime", 2, false, false, false, false, -1, null));
		addresses.Columns.Add(CreateColumn("CustomerId", "System.Int32", 3, false, false, false, false, -1, null));
		addresses.Columns.Add(CreateColumn("CustomerSyncId", "System.Guid", 4, false, false, false, false, -1, null));
		addresses.Columns.Add(CreateColumn("ExternalId", "System.Guid", 5, false, false, false, false, -1, null));
		addresses.Columns.Add(CreateColumn("Floor", "System.Byte", 6, false, false, false, false, -1, null));
		addresses.Columns.Add(CreateColumn("IsDeleted", "System.Boolean", 8, false, false, false, false, -1, null));
		addresses.Columns.Add(CreateColumn("IsPrimary", "System.Boolean", 9, false, false, false, false, -1, null));
		addresses.Columns.Add(CreateColumn("Latitude", "System.Double", 10, false, false, false, false, -1, null));
		addresses.Columns.Add(CreateColumn("Line1", "System.String", 11, false, false, false, false, -1, null));
		addresses.Columns.Add(CreateColumn("Longitude", "System.Double", 12, false, false, false, false, -1, null));
		addresses.Columns.Add(CreateColumn("ModifiedOn", "System.DateTime", 13, false, false, false, false, -1, null));
		addresses.Columns.Add(CreateColumn("Photo", "System.Byte[]", 14, false, false, false, false, -1, null));
		addresses.Columns.Add(CreateColumn("Postal", "System.String", 15, false, false, false, false, -1, null));
		addresses.Columns.Add(CreateColumn("State", "System.String", 16, false, false, false, false, -1, null));
		addresses.Columns.Add(CreateColumn("TaxRate", "System.Decimal", 18, false, false, false, false, -1, null));
		addresses.Columns.Add(CreateColumn("UnitNumber", "System.Int16", 19, false, false, false, false, -1, null));
		addresses.Indexes.Add(CreateIndex("IX_Addresses_ModifiedOn", false, "ModifiedOn"));
		addresses.Indexes.Add(CreateIndex("IX_Addresses_SyncId", true, "SyncId"));

		var bookmarks = AddTable("Bookmarks", "");
		bookmarks.Columns.Add(CreateColumn("CreatedOn", "System.DateTime", 0, false, false, false, false, -1, null));
		bookmarks.Columns.Add(CreateColumn("Id", "System.Int64", 0, false, true, true, false, 0, null));
		bookmarks.Columns.Add(CreateColumn("SyncId", "System.Guid", 0, false, false, false, true, 0, null));
		bookmarks.Columns.Add(CreateColumn("CustomerId", "System.Int32", 1, false, false, false, false, -1, null));
		bookmarks.Columns.Add(CreateColumn("CustomerSyncId", "System.Guid", 2, false, false, false, false, -1, null));
		bookmarks.Columns.Add(CreateColumn("IsDeleted", "System.Boolean", 4, false, false, false, false, -1, null));
		bookmarks.Columns.Add(CreateColumn("IsParent", "System.Boolean", 5, false, false, false, false, -1, null));
		bookmarks.Columns.Add(CreateColumn("ModifiedOn", "System.DateTime", 6, false, false, false, false, -1, null));
		bookmarks.Columns.Add(CreateColumn("Name", "System.String", 7, false, false, false, false, -1, null));
		bookmarks.Columns.Add(CreateColumn("Order", "System.Int32", 8, false, false, false, false, -1, null));
		bookmarks.Columns.Add(CreateColumn("ParentId", "System.Int64", 9, false, false, false, false, -1, null));
		bookmarks.Columns.Add(CreateColumn("ParentSyncId", "System.Guid", 10, false, false, false, false, -1, null));
		bookmarks.Indexes.Add(CreateIndex("IX_Bookmarks_ModifiedOn", false, "ModifiedOn"));
		bookmarks.Indexes.Add(CreateIndex("IX_Bookmarks_SyncId", true, "SyncId"));
		bookmarks.ForeignKeys.Add(CreateForeignKey("FK_Bookmarks_Bookmarks_ParentId", "Bookmarks", "Id", "ParentId"));

		var customers = AddTable("Customers", "");
		customers.Columns.Add(CreateColumn("CreatedOn", "System.DateTime", 0, false, false, false, false, -1, null));
		customers.Columns.Add(CreateColumn("Id", "System.Int32", 0, false, true, true, false, 0, null));
		customers.Columns.Add(CreateColumn("SyncId", "System.Guid", 0, false, false, false, true, 0, null));
		customers.Columns.Add(CreateColumn("IsDeleted", "System.Boolean", 2, false, false, false, false, -1, null));
		customers.Columns.Add(CreateColumn("ModifiedOn", "System.DateTime", 3, false, false, false, false, -1, null));
		customers.Columns.Add(CreateColumn("Name", "System.String", 4, false, false, false, false, -1, null));
		customers.Indexes.Add(CreateIndex("IX_Customers_ModifiedOn", false, "ModifiedOn"));
		customers.Indexes.Add(CreateIndex("IX_Customers_SyncId", true, "SyncId"));

		var settings = AddTable("Settings", "");
		settings.Columns.Add(CreateColumn("CreatedOn", "System.DateTime", 0, false, false, false, false, -1, null));
		settings.Columns.Add(CreateColumn("Id", "System.Int64", 0, false, true, true, false, 0, null));
		settings.Columns.Add(CreateColumn("SyncId", "System.Guid", 0, false, false, false, true, 0, null));
		settings.Columns.Add(CreateColumn("IsDeleted", "System.Boolean", 2, false, false, false, false, -1, null));
		settings.Columns.Add(CreateColumn("ModifiedOn", "System.DateTime", 3, false, false, false, false, -1, null));
		settings.Columns.Add(CreateColumn("Name", "System.String", 4, false, false, false, false, -1, null));
		settings.Columns.Add(CreateColumn("Value", "System.String", 6, false, false, false, false, -1, null));
		settings.Indexes.Add(CreateIndex("IX_Settings_ModifiedOn", false, "ModifiedOn"));
		settings.Indexes.Add(CreateIndex("IX_Settings_SyncId", true, "SyncId"));

	}

	#endregion
}
