// <auto-generated />

#region References

using Cornerstone.Storage.Sql.Migrations;

#endregion

namespace Cornerstone.Sample.Storage.Migrations;

public partial class SampleSqlDatabaseModelSnapshot : Snapshot_20260914120000_Initial
{
}
