#region References

using NUnit.Framework;

#endregion

namespace Cornerstone.Generators.UnitTests.RelayCommand;

[TestFixture]
public class RelayCommandTests : GeneratorUnitTest
{
	#region Methods

	[Test]
	public void Attribute()
	{
		var source = """
					namespace Cornerstone.Test.Models;

					public partial class AccountService
					{
						[RelayCommand]
						public void Save()
						{
						}
					}
					""";

		// Generated Code - Expected
		var expected = new[]
		{
			"""
			using System;
			using System.Collections.Generic;
			// <auto-generated>
			// Auto-generated by Cornerstone.Generators
			// </auto-generated>
			namespace Cornerstone.Test.Models
			{
				partial class AccountService
				{
					private global::Cornerstone.Presentation.RelayCommand _saveCommand;
					public global::System.Windows.Input.ICommand SaveCommand
					{
						get { return _saveCommand ??= new global::Cornerstone.Presentation.RelayCommand(_ => Save()); }
					}
				}
			}
			""",
			"""
			// <auto-generated>
			// Auto-generated by Cornerstone.Generators
			// </auto-generated>
			internal static partial class __CornerstoneSourceReflectorInitializer
			{
				[global::System.Runtime.CompilerServices.ModuleInitializer]
				public static void Initialize()
				{
				}
			}
			"""
		};
		// Generated Code - /Expected

		ValidateSource(source, expected);
	}

	#endregion
}