#region References

using NUnit.Framework;

#endregion

namespace Cornerstone.Generators.UnitTests.Comparable;

[TestFixture]
public class ComparableTests : GeneratorUnitTest
{
	#region Methods

	[Test]
	public void BuildComparable()
	{
		var source = """
					namespace Cornerstone.Test.Models;

					public partial class Account : IComparable
					{
						public string Name { get; set; }
						public int Age { get; set; }
						public DateTime CreatedOn { get; set; }
					}
					""";

		// Generated Code - Expected
		var expected = new[]
		{
			"""
			using System;
			using System.Collections.Generic;
			// <auto-generated>
			// Auto-generated by Cornerstone.Generators
			// </auto-generated>
			namespace Cornerstone.Test.Models
			{
				partial class Account
				{
					public int CompareTo(object other)
					{
						if (other is not global::Cornerstone.Test.Models.Account value)
						{
							throw new ArgumentException("Object is not a Account", nameof(other));
						}
			
						if (value == null)
						{
							return 1;
						}
						var cmp = this.Age.CompareTo(value.Age);
						if (cmp != 0) return cmp;
			
						cmp = this.CreatedOn.CompareTo(value.CreatedOn);
						if (cmp != 0) return cmp;
			
						cmp = this.Name.CompareTo(value.Name);
						if (cmp != 0) return cmp;
			
						return 0;
					}
				}
			}
			""",
			"""
			// <auto-generated>
			// Auto-generated by Cornerstone.Generators
			// </auto-generated>
			internal static partial class __CornerstoneSourceReflectorInitializer
			{
				[global::System.Runtime.CompilerServices.ModuleInitializer]
				public static void Initialize()
				{
				}
			}
			"""
		};
		// Generated Code - /Expected

		ValidateSource(source, expected);
	}
	
	[Test]
	public void BuildComparableGeneric()
	{
		var source = """
					namespace Cornerstone.Test.Models;

					public partial class Account : IComparable<Account>
					{
						public string Name { get; set; }
						public int Age { get; set; }
						public DateTime CreatedOn { get; set; }
					}
					""";

		// Generated Code - Expected
		var expected = new[]
		{
			"""
			using System;
			using System.Collections.Generic;
			// <auto-generated>
			// Auto-generated by Cornerstone.Generators
			// </auto-generated>
			namespace Cornerstone.Test.Models
			{
				partial class Account
				{
					public int CompareTo(object other)
					{
						if (other is not global::Cornerstone.Test.Models.Account value)
						{
							throw new ArgumentException("Object is not a Account", nameof(other));
						}
			
						return CompareTo(value);
					}
			
					public int CompareTo(Account value)
					{
						if (value == null)
						{
							return 1;
						}
						var cmp = this.Age.CompareTo(value.Age);
						if (cmp != 0) return cmp;
			
						cmp = this.CreatedOn.CompareTo(value.CreatedOn);
						if (cmp != 0) return cmp;
			
						cmp = this.Name.CompareTo(value.Name);
						if (cmp != 0) return cmp;
			
						return 0;
					}
				}
			}
			""",
			"""
			// <auto-generated>
			// Auto-generated by Cornerstone.Generators
			// </auto-generated>
			internal static partial class __CornerstoneSourceReflectorInitializer
			{
				[global::System.Runtime.CompilerServices.ModuleInitializer]
				public static void Initialize()
				{
				}
			}
			"""
		};
		// Generated Code - /Expected

		ValidateSource(source, expected);
	}

	#endregion
}