<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFrameworks>net10.0-android</TargetFrameworks>
		<SupportedOSPlatformVersion>34</SupportedOSPlatformVersion>
		<ApplicationId>com.bobbycannon.cornerstone.sample</ApplicationId>
		<AndroidPackageFormat>apk</AndroidPackageFormat>
		<AndroidEnableProfiledAot>False</AndroidEnableProfiledAot>
		<ApplicationVersion>1</ApplicationVersion>
		<ApplicationDisplayVersion>3.0.0</ApplicationDisplayVersion>
	</PropertyGroup>
	<ItemGroup>
		<AndroidResource Include="Icon.png">
			<Link>Resources\drawable\Icon.png</Link>
		</AndroidResource>
		<None Remove="hs_err_pid*.log" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="Avalonia.Android" Version="$(AvaloniaVersion)" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\Cornerstone.Sample\Cornerstone.Sample.csproj" />
	</ItemGroup>
</Project>