#region References

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Cornerstone.Generators.Models;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

#endregion

namespace Cornerstone.Generators.Processors;

internal static class ChannelMessageEmitter
{
	#region Methods

	public static void Emit(SourceProductionContext context, ImmutableArray<ChannelMessageModel> messages)
	{
		if (messages.IsDefaultOrEmpty)
		{
			return;
		}

		foreach (var group in messages.GroupBy(x => x.ChannelFullyQualifiedName, StringComparer.Ordinal))
		{
			var first = group.First();
			var builder = new CSharpCodeBuilder();
			builder.WriteAutoGeneratedComment();
			builder.IndentWriteLine("using System;");
			builder.IndentWriteLine("using Cornerstone.Presentation;");
			builder.WriteLine();

			if (first.ChannelNamespace.Length > 0)
			{
				builder.IndentWriteLine($"namespace {first.ChannelNamespace}");
				builder.IndentWriteLine("{");
				builder.IncreaseIndent();
			}

			for (var i = 0; i < first.ChannelOuterTypes.Length; i++)
			{
				builder.IndentWriteLine($"partial {first.ChannelOuterTypes[i]}");
				builder.IndentWriteLine("{");
				builder.IncreaseIndent();
			}

			builder.IndentWriteLine($"partial class {first.ChannelTypeName}");
			builder.IndentWriteLine("{");
			builder.IncreaseIndent();

			foreach (var message in group.OrderBy(x => x.MethodName, StringComparer.Ordinal))
			{
				if (!message.RelayCommand)
				{
					WritePublish(builder, message);
					builder.WriteLine();
				}

				WriteSubscribe(builder, message);
				builder.WriteLine();
				WriteUnsubscribe(builder, message);
				builder.WriteLine();
			}

			builder.DecreaseIndent();
			builder.IndentWriteLine("}");

			for (var i = 0; i < first.ChannelOuterTypes.Length; i++)
			{
				builder.DecreaseIndent();
				builder.IndentWriteLine("}");
			}

			if (first.ChannelNamespace.Length > 0)
			{
				builder.DecreaseIndent();
				builder.IndentWriteLine("}");
			}

			var hint = first.ChannelFullyQualifiedName.Replace(".", "_") + ".ChannelMessages.g.cs";
			context.AddSource(hint, builder.ToString());
		}
	}

	public static ChannelMessageModel Transform(GeneratorAttributeSyntaxContext context)
	{
		if (context.TargetSymbol is not INamedTypeSymbol messageType)
		{
			return default;
		}

		if (context.Attributes.Length == 0)
		{
			return default;
		}

		var attribute = context.Attributes[0];
		if (attribute.AttributeClass is not { TypeArguments.Length: 1 } attributeClass)
		{
			return default;
		}

		if (attributeClass.TypeArguments[0] is not INamedTypeSymbol channelType)
		{
			return default;
		}

		var methodName = string.Empty;
		if ((attribute.ConstructorArguments.Length > 0) && (attribute.ConstructorArguments[0].Value is string named) && (named.Length > 0))
		{
			methodName = named;
		}

		if (methodName.Length == 0)
		{
			methodName = InferMethodName(messageType.Name);
		}

		var relayCommand = false;
		foreach (var namedArg in attribute.NamedArguments)
		{
			if ((namedArg.Key == "RelayCommand") && (namedArg.Value.Value is true))
			{
				relayCommand = true;
			}
		}

		var parameters = GetParameters(messageType);
		var outerTypes = GetOuterTypeDeclarations(channelType);

		return new ChannelMessageModel(
			channelType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat).Replace("global::", string.Empty),
			channelType.ContainingNamespace.IsGlobalNamespace
				? string.Empty
				: channelType.ContainingNamespace.ToDisplayString(),
			channelType.Name,
			outerTypes,
			messageType.ToDisplayString(SymbolDisplayFormats.GlobalFullyQualifiedName),
			methodName,
			parameters,
			relayCommand);
	}

	private static string CamelCase(string name)
	{
		if (string.IsNullOrEmpty(name))
		{
			return name;
		}

		if (name.Length == 1)
		{
			return name.ToLowerInvariant();
		}

		return char.ToLowerInvariant(name[0]) + name.Substring(1);
	}

	private static ImmutableArray<string> GetOuterTypeDeclarations(INamedTypeSymbol channelType)
	{
		var stack = new Stack<string>();
		var current = channelType.ContainingType;
		while (current != null)
		{
			var kind = current.TypeKind == TypeKind.Struct ? "struct" : "class";
			if (current.IsRecord)
			{
				kind = current.TypeKind == TypeKind.Struct ? "record struct" : "record";
			}

			stack.Push($"{kind} {current.Name}");
			current = current.ContainingType;
		}

		return stack.ToImmutableArray();
	}

	private static ImmutableArray<ChannelMessageParameter> GetParameters(INamedTypeSymbol messageType)
	{
		var ctor = messageType.InstanceConstructors
			.Where(x => !x.IsStatic && (x.DeclaredAccessibility == Accessibility.Public))
			.OrderByDescending(x => x.Parameters.Length)
			.FirstOrDefault();

		if (ctor is null)
		{
			return ImmutableArray<ChannelMessageParameter>.Empty;
		}

		var builder = ImmutableArray.CreateBuilder<ChannelMessageParameter>(ctor.Parameters.Length);
		foreach (var parameter in ctor.Parameters)
		{
			var defaultLiteral = string.Empty;
			if (parameter.HasExplicitDefaultValue)
			{
				defaultLiteral = CSharpCodeBuilder.GetConstantLiteral(parameter.ExplicitDefaultValue);
			}

			builder.Add(new ChannelMessageParameter(
				parameter.Type.ToDisplayString(SymbolDisplayFormats.GlobalFullyQualifiedName),
				CamelCase(parameter.Name),
				defaultLiteral));
		}

		return builder.ToImmutable();
	}

	private static string InferMethodName(string typeName)
	{
		const string suffix = "Message";
		if (typeName.EndsWith(suffix, StringComparison.Ordinal) && (typeName.Length > suffix.Length))
		{
			return typeName.Substring(0, typeName.Length - suffix.Length);
		}

		return typeName;
	}

	private static void WriteParameterList(CSharpCodeBuilder builder, ImmutableArray<ChannelMessageParameter> parameters)
	{
		if (parameters.Length == 0)
		{
			builder.Write("()");
			return;
		}

		builder.Write("(");
		for (var i = 0; i < parameters.Length; i++)
		{
			if (i > 0)
			{
				builder.Write(", ");
			}

			var parameter = parameters[i];
			builder.Write(parameter.TypeGlobal);
			builder.Write(" ");
			builder.Write(parameter.Name);
			if (parameter.DefaultLiteral.Length > 0)
			{
				builder.Write(" = ");
				builder.Write(parameter.DefaultLiteral);
			}
		}

		builder.Write(")");
	}

	private static void WritePublish(CSharpCodeBuilder builder, ChannelMessageModel message)
	{
		if (message.RelayCommand)
		{
			builder.IndentWriteLine("[RelayCommand]");
		}

		builder.IndentWrite($"public void {message.MethodName}");
		WriteParameterList(builder, message.Parameters);
		builder.WriteLine();
		builder.IndentWriteLine("{");
		builder.IncreaseIndent();

		if (message.Parameters.Length == 0)
		{
			builder.IndentWriteLine($"Publish(new {message.MessageGlobalName}());");
		}
		else
		{
			var args = new StringBuilder();
			for (var i = 0; i < message.Parameters.Length; i++)
			{
				if (i > 0)
				{
					args.Append(", ");
				}

				args.Append(message.Parameters[i].Name);
			}

			builder.IndentWriteLine($"Publish(new {message.MessageGlobalName}({args}));");
		}

		builder.DecreaseIndent();
		builder.IndentWriteLine("}");
	}

	private static void WriteSubscribe(CSharpCodeBuilder builder, ChannelMessageModel message)
	{
		builder.IndentWriteLine($"public void SubscribeTo{message.MethodName}(Action<{message.MessageGlobalName}> handler)");
		builder.IndentWriteLine("{");
		builder.IncreaseIndent();
		builder.IndentWriteLine("Subscribe(handler);");
		builder.DecreaseIndent();
		builder.IndentWriteLine("}");
	}

	private static void WriteUnsubscribe(CSharpCodeBuilder builder, ChannelMessageModel message)
	{
		builder.IndentWriteLine($"public void UnsubscribeTo{message.MethodName}(Action<{message.MessageGlobalName}> handler)");
		builder.IndentWriteLine("{");
		builder.IncreaseIndent();
		builder.IndentWriteLine("Unsubscribe(handler);");
		builder.DecreaseIndent();
		builder.IndentWriteLine("}");
	}

	#endregion
}

internal readonly record struct ChannelMessageModel(
	string ChannelFullyQualifiedName,
	string ChannelNamespace,
	string ChannelTypeName,
	ImmutableArray<string> ChannelOuterTypes,
	string MessageGlobalName,
	string MethodName,
	ImmutableArray<ChannelMessageParameter> Parameters,
	bool RelayCommand)
{
	public bool IsDefault => string.IsNullOrEmpty(ChannelFullyQualifiedName);
}

internal readonly record struct ChannelMessageParameter(
	string TypeGlobal,
	string Name,
	string DefaultLiteral);
