#region References

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Diagnostics;
using System.Linq;
using Cornerstone.Generators.Models;
using Microsoft.CodeAnalysis;
using static Cornerstone.Generators.Generator;
using SourceAttributeInfo = Cornerstone.Generators.Models.SourceAttributeInfo;
using SourceTypeInfo = Cornerstone.Generators.Models.SourceTypeInfo;

#endregion

namespace Cornerstone.Generators.Processors;

/// <summary>
/// Discovers <c> [DependencyInjected] </c> types and emits factory-only default registration
/// into <c> {AssemblyName}.CornerstoneGenerated.RegisterDependencies </c>.
/// Closed generic AddSingleton/AddTransient calls are AOT and ReadyToRun safe.
/// </summary>
internal sealed class DependencyInjectedProcessor : ITypeProcessor
{
	#region Constants

	private const string GlobalDependencyProvider = "global::Cornerstone.Runtime.DependencyProvider";
	private const int LifetimeScoped = 1;
	private const int LifetimeSingleton = 2;
	private const int LifetimeTransient = 0;

	#endregion

	#region Properties

	/// <summary>
	/// Registration is emitted as a single assembly-level method, not into each type.
	/// </summary>
	public bool EmitsInsideTypeBlock => false;

	#endregion

	#region Methods

	/// <summary>
	/// Emit <c> RegisterDependencies </c> when any type in the compilation is attributed.
	/// </summary>
	public static void Generate(SourceProductionContext spc, Compilation compilation, ImmutableArray<SourceTypeInfo> typesToProcess)
	{
		var registrations = typesToProcess
			.Where(ShouldProcess)
			.SelectMany(GetRegistrations)
			.ToList();

		if (registrations.Count == 0)
		{
			return;
		}

		var builder = new CSharpCodeBuilder();
		builder.WriteAutoGeneratedComment();
		WriteCornerstoneGeneratedClass(builder, compilation, () =>
		{
			builder.IndentWriteLine("/// <summary>");
			builder.IndentWriteLine("/// Registers default factory services discovered via [DependencyInjected].");
			builder.IndentWriteLine("/// Call before any <c>SetSingleton</c> overrides and before first resolve.");
			builder.IndentWriteLine("/// Hosts may call this for each referenced assembly (e.g. Cornerstone, Cornerstone.Avalonia).");
			builder.IndentWriteLine("/// </summary>");
			builder.IndentWriteLine($"public static void RegisterDependencies({GlobalDependencyProvider} provider)");
			builder.IndentWriteLine("{");
			builder.Indent++;
			builder.IndentWriteLine("if (provider == null)");
			builder.IndentWriteLine("{");
			builder.Indent++;
			builder.IndentWriteLine("throw new global::System.ArgumentNullException(nameof(provider));");
			builder.Indent--;
			builder.IndentWriteLine("}");
			builder.WriteLine();

			// Stable, readable order: namespace/type then service type
			foreach (var registration in registrations
						.OrderBy(x => x.ImplementationGlobalName, StringComparer.Ordinal)
						.ThenBy(x => x.ServiceGlobalName ?? string.Empty, StringComparer.Ordinal))
			{
				builder.IndentWriteLine(registration.ToRegistrationStatement());
			}

			builder.Indent--;
			builder.IndentWriteLine("}");
		});

		var source = builder.ToString();
		Trace.WriteLine(source);
		spc.AddSource("__Cornerstone.DependencyInjection.g.cs", source);
	}

	public void Initialize(Compilation compilation)
	{
	}

	/// <summary>
	/// No per-type body emission; use <see cref="Generate" />.
	/// </summary>
	public void Process(CSharpCodeBuilder builder, SourceTypeInfo type)
	{
	}

	internal static bool ShouldProcess(SourceTypeInfo sourceTypeInfo)
	{
		return sourceTypeInfo.Attributes.Any(IsDependencyInjectedAttribute);
	}

	private static IEnumerable<Registration> GetRegistrations(SourceTypeInfo typeInfo)
	{
		var implementation = typeInfo.TypeSymbol;
		if (implementation == null)
		{
			yield break;
		}

		if (implementation.IsStatic || implementation.IsAbstract || implementation.IsGenericType)
		{
			DiagnosticReporter.WriteLine(
				$"Cornerstone DI: skipping '{implementation.ToDisplayString()}' (static, abstract, or open generic).");
			yield break;
		}

		var implementationGlobal = typeInfo.FullyGlobalQualifiedName
			?? implementation.ToDisplayString(SymbolDisplayFormats.GlobalFullyQualifiedName);

		foreach (var attribute in typeInfo.Attributes.Where(IsDependencyInjectedAttribute))
		{
			if (!TryParseAttribute(attribute, implementation, out var serviceType, out var lifetime, out var skip))
			{
				if (!skip)
				{
					DiagnosticReporter.WriteLine(
						$"Cornerstone DI: could not parse [DependencyInjected] on '{implementationGlobal}'.");
				}
				continue;
			}

			if (lifetime == LifetimeScoped)
			{
				DiagnosticReporter.WriteLine(
					$"Cornerstone DI: Scoped lifetime is not supported; skipping '{implementationGlobal}'.");
				continue;
			}

			string serviceGlobal = null;
			if (serviceType != null)
			{
				if (!IsValidServiceMapping(serviceType, implementation))
				{
					DiagnosticReporter.WriteLine(
						$"Cornerstone DI: '{implementationGlobal}' is not assignable to service '{serviceType.ToDisplayString()}'; skipping.");
					continue;
				}

				serviceGlobal = serviceType.ToDisplayString(SymbolDisplayFormats.GlobalFullyQualifiedName);

				// Self-as-service is the same as default registration
				if (SymbolEqualityComparer.Default.Equals(serviceType, implementation))
				{
					serviceGlobal = null;
				}
			}

			yield return new Registration(implementationGlobal, serviceGlobal, lifetime);
		}
	}

	private static bool IsDependencyInjectedAttribute(SourceAttributeInfo attribute)
	{
		return attribute.Name is NameDependencyInjectedAttribute
			|| (attribute.FullyQualifiedName == FullNameDependencyInjectedAttribute)
			|| (attribute.FullyGlobalQualifiedName == $"global::{FullNameDependencyInjectedAttribute}");
	}

	private static bool IsValidServiceMapping(ITypeSymbol serviceType, INamedTypeSymbol implementation)
	{
		if (SymbolEqualityComparer.Default.Equals(serviceType, implementation))
		{
			return true;
		}

		// interface or base type
		if (serviceType.TypeKind == TypeKind.Interface)
		{
			return implementation.AllInterfaces.Any(i => SymbolEqualityComparer.Default.Equals(i, serviceType));
		}

		var current = implementation.BaseType;
		while (current != null)
		{
			if (SymbolEqualityComparer.Default.Equals(current, serviceType))
			{
				return true;
			}
			current = current.BaseType;
		}

		return false;
	}

	private static bool TryParseAttribute(
		SourceAttributeInfo attribute,
		INamedTypeSymbol implementation,
		out ITypeSymbol serviceType,
		out int lifetime,
		out bool skipQuietly)
	{
		serviceType = null;
		lifetime = LifetimeSingleton;
		skipQuietly = false;

		// Prefer Roslyn AttributeData for accurate TypedConstant kinds
		var data = attribute.Data;
		if (data != null)
		{
			var args = data.ConstructorArguments;
			if (args.Length == 0)
			{
				return true;
			}

			if (args.Length == 1)
			{
				var only = args[0];
				if (only.Kind == TypedConstantKind.Type)
				{
					serviceType = only.Value as ITypeSymbol;
					return serviceType != null;
				}

				if (only.Kind == TypedConstantKind.Enum)
				{
					lifetime = Convert.ToInt32(only.Value);
					return true;
				}

				// Defaulted TypeLifetime may surface as primitive int
				if (only.Value is int intLifetime)
				{
					lifetime = intLifetime;
					return true;
				}

				return false;
			}

			if (args.Length >= 2)
			{
				if (args[0].Kind == TypedConstantKind.Type)
				{
					serviceType = args[0].Value as ITypeSymbol;
				}

				if (args[1].Value != null)
				{
					lifetime = Convert.ToInt32(args[1].Value);
				}

				return serviceType != null;
			}

			return false;
		}

		// Fallback: values already projected into ConstructorArguments
		var projected = attribute.ConstructorArguments;
		if ((projected == null) || (projected.Length == 0))
		{
			return true;
		}

		if (projected.Length == 1)
		{
			if (projected[0] is ITypeSymbol typeOnly)
			{
				serviceType = typeOnly;
				return true;
			}

			if (projected[0] is int enumAsInt)
			{
				lifetime = enumAsInt;
				return true;
			}

			return false;
		}

		if (projected.Length >= 2)
		{
			serviceType = projected[0] as ITypeSymbol;
			if (projected[1] is int life)
			{
				lifetime = life;
			}
			return serviceType != null;
		}

		skipQuietly = true;
		return false;
	}

	#endregion

	#region Structures

	private readonly struct Registration
	{
		#region Constructors

		public Registration(string implementationGlobalName, string serviceGlobalName, int lifetime)
		{
			ImplementationGlobalName = implementationGlobalName;
			ServiceGlobalName = serviceGlobalName;
			Lifetime = lifetime;
		}

		#endregion

		#region Properties

		public string ImplementationGlobalName { get; }
		public int Lifetime { get; }
		public string ServiceGlobalName { get; }

		#endregion

		#region Methods

		public string ToRegistrationStatement()
		{
			var method = Lifetime == LifetimeTransient ? "AddTransient" : "AddSingleton";

			if (string.IsNullOrEmpty(ServiceGlobalName))
			{
				return $"provider.{method}<{ImplementationGlobalName}>();";
			}

			return $"provider.{method}<{ServiceGlobalName}, {ImplementationGlobalName}>();";
		}

		#endregion
	}

	#endregion
}