#region References

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

#endregion

namespace Cornerstone.Generators.Processors;

internal static class ProcessorSubscriptionEmitter
{
	#region Methods

	public static void Emit(SourceProductionContext context, ImmutableArray<ProcessorSubscriptionModel> models)
	{
		if (models.IsDefaultOrEmpty)
		{
			return;
		}

		foreach (var model in models)
		{
			if (model.Handlers.Length == 0)
			{
				continue;
			}

			var builder = new CSharpCodeBuilder();
			builder.WriteAutoGeneratedComment();
			builder.IndentWriteLine("using System;");
			builder.WriteLine();

			if (model.Namespace.Length > 0)
			{
				builder.IndentWriteLine($"namespace {model.Namespace}");
				builder.IndentWriteLine("{");
				builder.IncreaseIndent();
			}

			builder.IndentWriteLine($"partial class {model.TypeName}");
			builder.IndentWriteLine("{");
			builder.IncreaseIndent();

			builder.IndentWriteLine("protected override void SubscribeGeneratedHandlers()");
			builder.IndentWriteLine("{");
			builder.IncreaseIndent();
			foreach (var handler in model.Handlers)
			{
				builder.IndentWriteLine($"Bus.{handler.ChannelProperty}.{handler.SubscribeMethod}({handler.MethodName});");
			}

			builder.DecreaseIndent();
			builder.IndentWriteLine("}");
			builder.WriteLine();

			builder.IndentWriteLine("protected override void UnsubscribeGeneratedHandlers()");
			builder.IndentWriteLine("{");
			builder.IncreaseIndent();
			foreach (var handler in model.Handlers)
			{
				builder.IndentWriteLine($"Bus.{handler.ChannelProperty}.{handler.UnsubscribeMethod}({handler.MethodName});");
			}

			builder.DecreaseIndent();
			builder.IndentWriteLine("}");

			builder.DecreaseIndent();
			builder.IndentWriteLine("}");

			if (model.Namespace.Length > 0)
			{
				builder.DecreaseIndent();
				builder.IndentWriteLine("}");
			}

			var hint = model.FullyQualifiedName.Replace(".", "_") + ".ChannelHandlers.g.cs";
			context.AddSource(hint, builder.ToString());
		}
	}

	public static ProcessorSubscriptionModel Transform(GeneratorSyntaxContext context)
	{
		if (context.Node is not ClassDeclarationSyntax)
		{
			return default;
		}

		if (context.SemanticModel.GetDeclaredSymbol(context.Node) is not INamedTypeSymbol type)
		{
			return default;
		}

		if (!HasChannelHandlersAttribute(type) || !IsKeystoneProcessor(type, out var busType))
		{
			return default;
		}

		var handlers = new List<ProcessorHandlerModel>();
		foreach (var method in type.GetMembers().OfType<IMethodSymbol>())
		{
			if (method.IsStatic
				|| (method.MethodKind != MethodKind.Ordinary)
				|| (method.Parameters.Length != 1)
				|| !method.Name.StartsWith("On", StringComparison.Ordinal)
				|| (method.Name.Length <= 2))
			{
				continue;
			}

			var messageType = method.Parameters[0].Type as INamedTypeSymbol;
			if (messageType == null)
			{
				continue;
			}

			if (!TryGetChannelType(messageType, out var channelType))
			{
				continue;
			}

			var channelProperty = FindChannelProperty(busType, channelType);
			if (channelProperty.Length == 0)
			{
				continue;
			}

			var operation = method.Name.Substring(2);
			handlers.Add(new ProcessorHandlerModel(
				method.Name,
				channelProperty,
				"SubscribeTo" + operation,
				"UnsubscribeTo" + operation));
		}

		if (handlers.Count == 0)
		{
			return default;
		}

		return new ProcessorSubscriptionModel(
			type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat).Replace("global::", string.Empty),
			type.ContainingNamespace.IsGlobalNamespace
				? string.Empty
				: type.ContainingNamespace.ToDisplayString(),
			type.Name,
			handlers.ToImmutableArray());
	}

	private static bool HasChannelHandlersAttribute(INamedTypeSymbol type)
	{
		foreach (var attribute in type.GetAttributes())
		{
			if (attribute.AttributeClass?.Name == "ChannelHandlersAttribute")
			{
				return true;
			}
		}

		return false;
	}

	private static string FindChannelProperty(INamedTypeSymbol busType, INamedTypeSymbol channelType)
	{
		foreach (var member in busType.GetMembers().OfType<IPropertySymbol>())
		{
			if (SymbolEqualityComparer.Default.Equals(member.Type, channelType))
			{
				return member.Name;
			}
		}

		return string.Empty;
	}

	private static bool IsKeystoneProcessor(INamedTypeSymbol type, out INamedTypeSymbol busType)
	{
		busType = null;
		var current = type.BaseType;
		while (current != null)
		{
			if (current.IsGenericType
				&& (current.Name == "KeystoneProcessor")
				&& (current.TypeArguments.Length >= 1)
				&& current.TypeArguments[0] is INamedTypeSymbol bus)
			{
				busType = bus;
				return true;
			}

			current = current.BaseType;
		}

		return false;
	}

	private static bool TryGetChannelType(INamedTypeSymbol messageType, out INamedTypeSymbol channelType)
	{
		channelType = null;
		foreach (var attribute in messageType.GetAttributes())
		{
			if (attribute.AttributeClass is not { Name: "ChannelMessageAttribute", TypeArguments.Length: 1 } named)
			{
				continue;
			}

			if (named.TypeArguments[0] is INamedTypeSymbol channel)
			{
				channelType = channel;
				return true;
			}
		}

		return false;
	}

	#endregion
}

internal readonly record struct ProcessorSubscriptionModel(
	string FullyQualifiedName,
	string Namespace,
	string TypeName,
	ImmutableArray<ProcessorHandlerModel> Handlers)
{
	public bool IsDefault => string.IsNullOrEmpty(FullyQualifiedName);
}

internal readonly record struct ProcessorHandlerModel(
	string MethodName,
	string ChannelProperty,
	string SubscribeMethod,
	string UnsubscribeMethod);
