#region References

using System.Collections.Generic;
using System.Linq;
using Cornerstone.Reflection;
using Microsoft.CodeAnalysis;
using static Cornerstone.Generators.Generator;
using SourceAttributeInfo = Cornerstone.Generators.Models.SourceAttributeInfo;
using SourceConstructorInfo = Cornerstone.Generators.Models.SourceConstructorInfo;
using SourceFieldInfo = Cornerstone.Generators.Models.SourceFieldInfo;
using SourceInterfaceInfo = Cornerstone.Generators.Models.SourceInterfaceInfo;
using SourceMethodInfo = Cornerstone.Generators.Models.SourceMethodInfo;
using SourceParameterInfo = Cornerstone.Generators.Models.SourceParameterInfo;
using SourcePropertyInfo = Cornerstone.Generators.Models.SourcePropertyInfo;
using SourceTypeInfo = Cornerstone.Generators.Models.SourceTypeInfo;
using SymbolDisplayFormats = Cornerstone.Generators.Models.SymbolDisplayFormats;

#endregion

namespace Cornerstone.Generators.Processors;

/// <summary>
/// Emits compiled construct/get/set for source reflection. Native AOT is the point; do not emit GetConstructor or ConstructorInfo.Invoke as the invoke path.
/// </summary>
internal sealed class SourceReflectionProcessor : ITypeProcessor
{
	#region Fields

	private string _generatedNamespace;
	private bool _hasUnsafeAccessor;

	#endregion

	#region Properties

	public bool EmitsInsideTypeBlock => false;

	#endregion

	#region Methods

	public void Process(CSharpCodeBuilder builder, SourceTypeInfo type)
	{
		if (!ShouldProcess(type))
		{
			return;
		}

		builder.WriteAutoGeneratedComment();
		var constructorAccessors = new List<(string MethodName, SourceConstructorInfo Constructor)>();
		WriteCornerstoneGeneratedClass(builder, _generatedNamespace, () =>
			{
				builder.WriteBlock($"private static readonly {GlobalSourceTypeInfo} {type.FullyQualifiedSourceReflectorName} = new {GlobalSourceTypeInfo}()",
					() =>
					{
						builder.IndentWriteLine($"Accessibility = {GlobalSourceAccessibility}.{type.Accessibility},");

						AppendAttributes(builder, type.Attributes);

						if (type.BaseFullyGlobalQualifiedTypeName != null)
						{
							builder.IndentWriteLine($"BaseType = typeof({type.BaseFullyGlobalQualifiedTypeName}),");
						}

						if (type.Constructors.Count > 0)
						{
							builder.WriteBlock($"DeclaredConstructorsInitializer = static () => new {GlobalSourceConstructorInfo}[]", () =>
							{
								for (var i = 0; i < type.Constructors.Count; i++)
								{
									WriteConstructor(builder, type, type.Constructors[i], i, constructorAccessors);
								}
							}, ",");
						}
						else
						{
							builder.IndentWriteLine($"DeclaredConstructorsInitializer = static () => {GlobalSystemArrayEmpty}<{GlobalSourceConstructorInfo}>(),");
						}

						if (type.Fields.Count > 0)
						{
							builder.WriteBlock($"DeclaredFieldsInitializer = static () => new {GlobalSourceFieldInfo}[]", () =>
							{
								foreach (var field in type.Fields)
								{
									WriteField(builder, type, field);
								}
							}, ",");
						}
						else
						{
							builder.IndentWriteLine($"DeclaredFieldsInitializer = static () => {GlobalSystemArrayEmpty}<{GlobalSourceFieldInfo}>(),");
						}

						if (type.Interfaces.Count > 0)
						{
							builder.WriteBlock($"DeclaredInterfacesInitializer = static () => new {GlobalSourceInterfaceInfo}[]", () =>
							{
								foreach (var field in type.Interfaces)
								{
									WriteInterface(builder, type, field);
								}
							}, ",");
						}
						else
						{
							builder.IndentWriteLine($"DeclaredInterfacesInitializer = static () => {GlobalSystemArrayEmpty}<{GlobalSourceInterfaceInfo}>(),");
						}

						if (type.Methods.Count > 0)
						{
							builder.WriteBlock($"DeclaredMethodsInitializer = static () => new {GlobalSourceMethodInfo}[]", () =>
							{
								foreach (var method in type.Methods)
								{
									WriteMethod(builder, type, method);
								}
							}, ",");
						}
						else
						{
							builder.IndentWriteLine($"DeclaredMethodsInitializer = static () => {GlobalSystemArrayEmpty}<{GlobalSourceMethodInfo}>(),");
						}

						if (type.Properties.Count > 0)
						{
							builder.WriteBlock($"DeclaredPropertiesInitializer = static () => new {GlobalSourcePropertyInfo}[]", () =>
							{
								foreach (var property in type.Properties)
								{
									WriteProperty(builder, type, property);
								}
							}, ",");
						}
						else
						{
							builder.IndentWriteLine($"DeclaredPropertiesInitializer = static () => {GlobalSystemArrayEmpty}<{GlobalSourcePropertyInfo}>(),");
						}

						builder.WriteAssignment("IsEnum", type.IsEnum);
						builder.WriteAssignment("IsReadOnly", type.IsReadOnly);
						builder.WriteAssignment("IsStatic", type.IsStatic);
						builder.WriteAssignment("IsStruct", type.IsStruct);
						builder.WriteAssignment("Name", type.Name);
						builder.IndentWriteLine($"Type = typeof({ForTypeOf(type.TypeSymbol)})");
					}, ";");

				foreach (var accessor in constructorAccessors)
				{
					WriteUnsafeConstructorAccessor(builder, type, accessor.MethodName, accessor.Constructor);
				}
			});
	}

	/// <summary>
	/// Also used by the module initializer to decide whether to register a type.
	/// </summary>
	internal static bool ShouldProcess(SourceTypeInfo sourceTypeInfo)
	{
		return sourceTypeInfo.Attributes.Any(x => x.Name is NameSourceReflectionAttribute)
			|| sourceTypeInfo.IsSourceReflectionType;
	}

	private static void AppendAttributes(CSharpCodeBuilder builder, List<SourceAttributeInfo> attributes)
	{
		if (attributes.Count <= 0)
		{
			builder.IndentWriteLine("Attributes = [],");
			return;
		}

		builder.WriteBlock("Attributes = new[]",
			() =>
			{
				var end = attributes.Count - 1;
				for (var index = 0; index < attributes.Count; index++)
				{
					var attribute = attributes[index];
					builder.WriteBlock($"new {GlobalSourceAttributeInfo}",
						() =>
						{
							builder.WriteAssignment(nameof(attribute.ConstructorArguments), attribute.ConstructorArguments);
							builder.WriteAssignment(nameof(attribute.FullyQualifiedName), attribute.FullyQualifiedName);
							builder.WriteAssignment(nameof(attribute.FullyGlobalQualifiedName), attribute.FullyGlobalQualifiedName);
							builder.WriteAssignment(nameof(attribute.Name), attribute.Name);
							builder.WriteAssignment(nameof(attribute.NamedArguments), attribute.NamedArguments);
							builder.WriteAssignmentRaw(nameof(attribute.Type), $"typeof({attribute.FullyGlobalQualifiedName})", lastAssignment: true);
						},
						index < end ? "," : null
					);
				}
			},
			",");
	}

	private static void AppendBindingFlags(CSharpCodeBuilder builder, Accessibility accessibility, bool isStatic)
	{
		builder.Write(isStatic
			? "global::System.Reflection.BindingFlags.DeclaredOnly | global::System.Reflection.BindingFlags.Static"
			: "global::System.Reflection.BindingFlags.DeclaredOnly | global::System.Reflection.BindingFlags.Instance"
		);

		builder.Write(accessibility == Accessibility.Public
			? " | global::System.Reflection.BindingFlags.Public"
			: " | global::System.Reflection.BindingFlags.NonPublic"
		);
	}

	private static string ForTypeOf(INamedTypeSymbol typeSymbol)
	{
		if (!typeSymbol.IsGenericType)
		{
			return typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
		}

		var openDefinition = typeSymbol.OriginalDefinition;

		var formatNoGenerics = SymbolDisplayFormat.FullyQualifiedFormat
			.WithGenericsOptions(SymbolDisplayGenericsOptions.None);

		var baseName = openDefinition.ToDisplayString(formatNoGenerics);

		var arity = openDefinition.Arity;
		if (arity > 0)
		{
			baseName += "<" + new string(',', arity - 1) + ">";
		}

		return baseName;
	}

	/// <summary>
	/// True when a nested type cannot appear in typeof(...) from a sibling type in the same assembly
	/// (private / protected / private protected nested types).
	/// </summary>
	private static bool IsInaccessibleNestedType(INamedTypeSymbol type)
	{
		for (var current = type; current != null; current = current.ContainingType)
		{
			switch (current.DeclaredAccessibility)
			{
				case Accessibility.Private:
				case Accessibility.Protected:
				case Accessibility.ProtectedAndInternal:
				{
					return true;
				}
			}
		}

		return false;
	}

	private static bool RequiresDynamicCode(SourceMethodInfo member)
	{
		return member.Attributes.Any(a =>
			(a.Name is "RequiresDynamicCodeAttribute" or "RequiresUnreferencedCodeAttribute")
			|| (a.FullyQualifiedName?.Contains("RequiresDynamicCode") == true)
			|| (a.FullyQualifiedName?.Contains("RequiresUnreferencedCode") == true)
		);
	}

	private static bool UsesJsonElement(SourceMethodInfo member)
	{
		return member.Parameters.Any(p =>
			(p.ParameterType is "System.Text.Json.JsonElement" or "global::System.Text.Json.JsonElement")
			|| (p.DisplayType?.Contains("JsonElement") == true)
		);
	}

	/// <summary>
	/// True when the type can appear in a typeof(...) expression (no MakeArrayType).
	/// </summary>
	private static bool CanEmitTypeof(ITypeSymbol type)
	{
		if (type is IArrayTypeSymbol arrayType)
		{
			return CanEmitTypeof(arrayType.ElementType);
		}

		return type is not INamedTypeSymbol namedType || !IsInaccessibleNestedType(namedType);
	}

	/// <summary>
	/// Expression that evaluates to System.Type for the parameter type (not by-ref).
	/// Private nested types cannot use typeof(Outer.Nested) outside Outer, so resolve them with
	/// GetNestedType from an accessible root.
	/// </summary>
	private static string TypeOfExpression(SourceParameterInfo parameter)
	{
		return parameter.ParameterSymbol != null
			? TypeOfExpression(parameter.ParameterSymbol)
			: $"typeof({parameter.ParameterType})";
	}

	/// <summary>
	/// Type expression for MethodInfo.GetMethod parameter arrays (includes MakeByRefType for ref/out).
	/// </summary>
	private static string TypeOfExpressionForMethodLookup(SourceParameterInfo parameter)
	{
		var expression = TypeOfExpression(parameter);
		return parameter.IsRef || parameter.IsOut
			? $"{expression}.MakeByRefType()"
			: expression;
	}

	/// <summary>
	/// Expression that evaluates to System.Type for the symbol from generated sibling code.
	/// </summary>
	private static string TypeOfExpression(ITypeSymbol typeSymbol)
	{
		if (typeSymbol is IArrayTypeSymbol arrayType)
		{
			if (CanEmitTypeof(arrayType))
			{
				return $"typeof({arrayType.ToDisplayString(SymbolDisplayFormats.GlobalFullyQualifiedName)})";
			}

			var element = TypeOfExpression(arrayType.ElementType);
			return arrayType.Rank == 1
				? $"{element}.MakeArrayType()"
				: $"{element}.MakeArrayType({arrayType.Rank})";
		}

		if (typeSymbol is not INamedTypeSymbol namedType)
		{
			return $"typeof({typeSymbol.ToDisplayString(SymbolDisplayFormats.GlobalFullyQualifiedName)})";
		}

		if (!IsInaccessibleNestedType(namedType))
		{
			return $"typeof({namedType.ToDisplayString(SymbolDisplayFormats.GlobalFullyQualifiedName)})";
		}

		// Walk Outer.Inner.Nested → typeof(Outer).GetNestedType("Inner", …).GetNestedType("Nested", …)
		var chain = new List<INamedTypeSymbol>();
		for (var current = namedType; current != null; current = current.ContainingType)
		{
			chain.Add(current);
		}

		chain.Reverse();

		var expression = $"typeof({chain[0].ToDisplayString(SymbolDisplayFormats.GlobalFullyQualifiedName)})";
		const string nestedFlags =
			"global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.NonPublic";

		for (var index = 1; index < chain.Count; index++)
		{
			// MetadataName includes arity suffix for open generics (e.g. Nested`1).
			expression = $"{expression}.GetNestedType(\"{chain[index].MetadataName}\", {nestedFlags})";
		}

		return expression;
	}

	void ITypeProcessor.Initialize(Compilation compilation)
	{
		_generatedNamespace = GetCornerstoneGeneratedNamespace(compilation);
		_hasUnsafeAccessor = compilation.GetTypeByMetadataName("System.Runtime.CompilerServices.UnsafeAccessorAttribute") != null;
	}

	// CornerstoneGenerated is another type in the same assembly, so only these visibilities can use `new T(...)`.
	private static bool CanCallConstructorDirectly(SourceConstructorInfo constructor)
	{
		return constructor.Accessibility is Accessibility.Public
			or Accessibility.Internal
			or Accessibility.ProtectedOrInternal;
	}

	private static bool CanEmitCompiledConstructor(SourceTypeInfo type, SourceConstructorInfo constructor)
	{
		return !type.IsGenericTypeDefinition
			&& !type.IsRefLikeType
			&& !constructor.IsStatic
			&& (constructor.ContainingType is not { IsAbstract: true })
			&& !constructor.Parameters.Any(x => x.IsParameterTypeRefLike || x.IsParameterTypePointer)
			&& !type.Properties.Any(x => x.IsRequired)
			&& !type.Fields.Any(x => x.IsRequired)
			&& !type.HasBaseRequiredMembers;
	}

	private void WriteConstructor(
		CSharpCodeBuilder builder,
		SourceTypeInfo type,
		SourceConstructorInfo constructor,
		int constructorIndex,
		List<(string MethodName, SourceConstructorInfo Constructor)> constructorAccessors)
	{
		builder.IndentWriteLine($"new {GlobalSourceConstructorInfo}()");
		builder.WriteBlock(() =>
		{
			builder.IndentWriteLine($"Accessibility = {GlobalSourceAccessibility}.{constructor.Accessibility},");
			builder.WriteAssignment("Name", constructor.Name);
			builder.WriteAssignment("IsStatic", constructor.IsStatic);
			builder.WriteAssignment("IsDependencyConstructor", constructor.IsDependencyConstructor);

			WriteParametersProperty(builder, "Parameters", constructor.Parameters);

			if (!CanEmitCompiledConstructor(type, constructor))
			{
				return;
			}

			if (CanCallConstructorDirectly(constructor))
			{
				builder.WriteIndent();
				builder.Write($"Invoke = static (parameters) => new {type.FullyGlobalQualifiedName}(");
				WriteMethodArguments(builder, constructor.Parameters);
				builder.Write(")");
				builder.WriteLine();
				return;
			}

			if (!_hasUnsafeAccessor)
			{
				return;
			}

			var methodName = $"SourceReflectionConstruct_{type.FullyQualifiedSourceReflectorName}_{constructorIndex}";
			constructorAccessors.Add((methodName, constructor));

			builder.WriteIndent();
			builder.Write($"Invoke = static (parameters) => {methodName}(");
			WriteMethodArguments(builder, constructor.Parameters);
			builder.Write(")");
			builder.WriteLine();
		}, ",");
	}

	// Private constructors cannot be `new`'d from CornerstoneGenerated. UnsafeAccessor is AOT-legal; GetConstructor is not.
	private static void WriteUnsafeConstructorAccessor(
		CSharpCodeBuilder builder,
		SourceTypeInfo type,
		string methodName,
		SourceConstructorInfo constructor)
	{
		builder.WriteLine();
		builder.IndentWriteLine("[global::System.Runtime.CompilerServices.UnsafeAccessor(global::System.Runtime.CompilerServices.UnsafeAccessorKind.Constructor)]");
		builder.WriteIndent();
		builder.Write($"extern static {type.FullyGlobalQualifiedName} {methodName}(");

		for (var i = 0; i < constructor.Parameters.Length; i++)
		{
			var parameter = constructor.Parameters[i];
			builder.Write($"{parameter.ParameterType} {parameter.Name}");
			if (i < (constructor.Parameters.Length - 1))
			{
				builder.Write(", ");
			}
		}

		builder.WriteLine(");");
	}

	private static void WriteField(CSharpCodeBuilder builder, SourceTypeInfo type, SourceFieldInfo member)
	{
		builder.IndentWriteLine($"new {GlobalSourceFieldInfo}()");
		builder.WriteBlock(
			() =>
			{
				builder.IndentWriteLine($"Accessibility = {GlobalSourceAccessibility}.{member.Accessibility},");

				AppendAttributes(builder, member.Attributes);

				builder.IndentWrite($"FieldInfo = typeof({ForTypeOf(type.TypeSymbol)}).GetField(\"{member.Name}\", ");
				AppendBindingFlags(builder, member.Accessibility, member.IsStatic);
				builder.WriteLine("),");

				if (member.IsConstant && (member.Accessibility == Accessibility.Public))
				{
					builder.IndentWriteLine($"GetValue = static _ => {type.FullyGlobalQualifiedName}.{member.Name},");
				}

				builder.WriteAssignment(nameof(SourceFieldInfo.IsConstant), member.IsConstant);
				builder.WriteAssignment(nameof(SourceFieldInfo.IsReadOnly), member.IsReadOnly);
				builder.WriteAssignment(nameof(SourceFieldInfo.IsRequired), member.IsRequired);
				builder.WriteAssignment(nameof(SourceFieldInfo.IsStatic), member.IsStatic);
				builder.WriteAssignment(nameof(SourceFieldInfo.Name), member.Name);
				builder.WriteAssignmentRaw(nameof(SourceFieldInfo.NullableAnnotation), $"{GlobalSourceNullableAnnotation}.{member.NullableAnnotation}", false, true);
			},
			","
		);
	}

	private static void WriteInterface(CSharpCodeBuilder builder, SourceTypeInfo type, SourceInterfaceInfo member)
	{
		builder.IndentWriteLine($"new {GlobalSourceInterfaceInfo}()");
		builder.WriteBlock(
			() =>
			{
				builder.WriteAssignment(nameof(SourceInterfaceInfo.FullyGlobalQualifiedName), member.FullyGlobalQualifiedName);
				builder.WriteAssignment(nameof(SourceInterfaceInfo.FullyQualifiedName), member.FullyQualifiedName);
				builder.WriteAssignment(nameof(SourceInterfaceInfo.Name), member.Name, lastAssignment: true);
			},
			","
		);
	}

	private static void WriteMethod(CSharpCodeBuilder builder, SourceTypeInfo type, SourceMethodInfo member)
	{
		builder.IndentWriteLine($"new {GlobalSourceMethodInfo}()");
		builder.WriteBlock(
			() =>
			{
				builder.WriteAssignment(nameof(SourceFieldInfo.Name), member.Name);
				builder.IndentWriteLine($"Accessibility = {GlobalSourceAccessibility}.{member.Accessibility},");
				builder.WriteAssignment(nameof(SourceFieldInfo.FullyQualifiedTypeName), member.FullyQualifiedTypeName);
				builder.WriteAssignment(nameof(SourceFieldInfo.IsStatic), member.IsStatic);

				if (RequiresDynamicCode(member) || UsesJsonElement(member) || (member.Name == "FromJsonElement"))
				{
					builder.IndentWriteLine("MethodInfo = null,");
				}
				else if (member.IsGenericMethod)
				{
					builder.IndentWrite($"MethodInfo = {GlobalReflectionExtensions}.FindGenericMethod(typeof({ForTypeOf(type.TypeSymbol)}), \"{member.Name}\", {member.TypeParameters?.Length}, ");
					builder.WriteArrayInitializer("global::System.String", member.Parameters.Select(x => $"\"{x.DisplayType}\"").ToArray());
					builder.WriteLine("),");
				}
				else
				{
					builder.IndentWrite($"MethodInfo = typeof({ForTypeOf(type.TypeSymbol)}).GetMethod(\"{member.Name}\", ");
					AppendBindingFlags(builder, member.Accessibility, member.IsStatic);
					builder.Write(", ");
					builder.WriteArrayInitializer("global::System.Type",
						member.Parameters
							.Select(TypeOfExpressionForMethodLookup)
							.ToArray()
					);
					builder.WriteLine("),");
				}

				AppendAttributes(builder, member.Attributes);

				if (!type.IsGenericTypeDefinition
					&& !type.IsRefLikeType
					&& member.CanInvoke()
					&& member.Parameters.All(p => !p.IsOut)
					&& !RequiresDynamicCode(member)
					&& !UsesJsonElement(member)
					&& (member.Name != "FromJsonElement"))
				{
					builder.IndentWrite("Invoke = static (instance, parameters) => ");

					var isVoid = member.ReturnType == "void";
					var isReadOnlySpanChar = member.ReturnType
						is "System.ReadOnlySpan<System.Char>"
						or "global::System.ReadOnlySpan<System.Char>";

					if (isVoid)
					{
						builder.Write("{ ");
					}

					builder.Write(member.IsStatic
						? $"{type.FullyGlobalQualifiedName}.{member.Name}("
						: $"(({type.FullyGlobalQualifiedName}) instance).{member.Name}(");

					for (var i = 0; i < member.Parameters.Length; i++)
					{
						var parameter = member.Parameters[i];
						if (parameter.IsTypeParameter)
						{
							var typeParameter = member.TypeParameters.First(x => x.Name == parameter.ParameterType);
							builder.Write(
								typeParameter.ConstraintTypes?.Length == 0
									? $"parameters[{i}]"
									: $"({typeParameter.ConstraintTypes?[0]}) parameters[{i}]"
							);
						}
						else
						{
							builder.Write($"({parameter.ParameterType}) parameters[{i}]");
						}

						if (i < (member.Parameters.Length - 1))
						{
							builder.Write(", ");
						}
					}

					builder.Write(")");

					if (isReadOnlySpanChar)
					{
						builder.Write(".ToString()");
					}
					else if (isVoid)
					{
						builder.Write("; return null; }");
					}

					builder.WriteLine();
				}
			},
			","
		);
	}

	private static void WriteMethodArguments(CSharpCodeBuilder builder, SourceParameterInfo[] parameters)
	{
		for (var i = 0; i < parameters.Length; i++)
		{
			var parameter = parameters[i];
			builder.Write($"({parameter.ParameterType}) parameters[{i}]");
			if (i < (parameters.Length - 1))
			{
				builder.Write(", ");
			}
		}
	}

	private static void WriteParametersProperty(CSharpCodeBuilder builder, string propertyName, SourceParameterInfo[] parameters)
	{
		if (parameters.Length == 0)
		{
			builder.IndentWriteLine($"{propertyName} = {GlobalSystemArrayEmpty}<{GlobalSourceParameterInfo}>(),");
		}
		else
		{
			builder.WriteBlock($"{propertyName} = new {GlobalSourceParameterInfo}[]", () =>
			{
				foreach (var member in parameters)
				{
					builder.WriteBlock($"new {GlobalSourceParameterInfo}()", () =>
					{
						builder.WriteAssignment("Name", member.Name);
						builder.WriteAssignment("HasDefaultValue", member.HasDefaultValue);
						builder.WriteAssignment("DefaultValue", member.DefaultValue);
						builder.WriteAssignment("IsRef", member.IsRef);
						builder.WriteAssignment("IsOut", member.IsOut);

						if (!member.HasNestedTypeParameter)
						{
							// Private nested parameter types cannot use typeof(Outer.Nested) from generated code.
							builder.IndentWriteLine($"ParameterType = {TypeOfExpression(member)},");
						}

						builder.WriteAssignmentRaw(nameof(SourceFieldInfo.NullableAnnotation), $"{GlobalSourceNullableAnnotation}.{member.NullableAnnotation}", false, true);
					}, ",");
				}
			}, ",");
		}
	}

	private static void WriteProperty(CSharpCodeBuilder builder, SourceTypeInfo type, SourcePropertyInfo member)
	{
		builder.IndentWriteLine($"new {GlobalSourcePropertyInfo}()");
		builder.WriteBlock(
			() =>
			{
				builder.IndentWriteLine($"Accessibility = {GlobalSourceAccessibility}.{member.Accessibility},");

				AppendAttributes(builder, member.Attributes);

				builder.WriteAssignment(nameof(SourcePropertyInfo.CanRead), member.CanRead);
				builder.WriteAssignment(nameof(SourcePropertyInfo.CanWrite), member.CanWrite);

				builder.WriteAssignment(nameof(SourcePropertyInfo.IsAbstract), member.IsAbstract);
				builder.WriteAssignment(nameof(SourcePropertyInfo.IsDependencyInjected), member.IsDependencyInjected);
				builder.WriteAssignment(nameof(SourcePropertyInfo.IsIndexer), member.IsIndexer);
				builder.WriteAssignment(nameof(SourcePropertyInfo.IsInitOnly), member.IsInitOnly);
				builder.WriteAssignment(nameof(SourcePropertyInfo.IsReadOnly), member.IsReadOnly);
				builder.WriteAssignment(nameof(SourcePropertyInfo.IsRequired), member.IsRequired);
				builder.WriteAssignment(nameof(SourcePropertyInfo.IsStatic), member.IsStatic);
				builder.WriteAssignment(nameof(SourcePropertyInfo.IsVirtual), member.IsVirtual);

				builder.IndentWrite($"PropertyInfo = typeof({ForTypeOf(type.TypeSymbol)}).GetProperty(\"{member.Name}\", ");
				AppendBindingFlags(builder, member.Accessibility, member.IsStatic);
				builder.WriteLine("),");

				builder.WriteAssignment("Name", member.Name);

				if (!type.IsGenericTypeDefinition
					&& !type.IsRefLikeType
					&& (member.Accessibility != Accessibility.Private)
					&& (member.Accessibility != Accessibility.Protected))
				{
					if (member.CanRead && member.GetMethodAccessibility is Accessibility.Public)
					{
						if (member.IsStatic)
						{
							builder.IndentWriteLine($"GetValue = static instance => {type.FullyGlobalQualifiedName}.{member.Name},");
						}
						else
						{
							if (member.IsIndexer)
							{
								builder.IndentWrite($"GetIndexerValue = static (instance, parameters) => (({type.FullyGlobalQualifiedName})instance)[");
								builder.WriteMethodArguments(builder, member.Parameters);
								builder.WriteLine("],");
							}
							else
							{
								builder.IndentWriteLine($"GetValue = static instance => (({type.FullyGlobalQualifiedName})instance).{member.Name},");
							}
						}
					}

					if (!type.IsStruct
						&& !member.IsInitOnly
						&& member.CanWrite
						&& member.SetMethodAccessibility is Accessibility.Public)
					{
						if (member.IsStatic)
						{
							builder.IndentWriteLine($"SetValue = static (instance, value) => {type.FullyGlobalQualifiedName}.{member.Name} = ({member.GlobalFullyQualifiedName}) value");
						}
						else
						{
							if (member.IsIndexer)
							{
								builder.IndentWrite($"SetIndexerValue = static (instance, value, parameters) => (({type.FullyGlobalQualifiedName})instance)[");
								builder.WriteMethodArguments(builder, member.Parameters);
								builder.WriteLine($"] = ({member.GlobalFullyQualifiedName}) value");
							}
							else
							{
								builder.IndentWriteLine($"SetValue = static (instance, value) => (({type.FullyGlobalQualifiedName}) instance).{member.Name} = ({member.GlobalFullyQualifiedName}) value");
							}
						}
					}
				}
			},
			","
		);
	}

	#endregion
}