#region References

using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.CodeAnalysis;
using static Cornerstone.Generators.Generator;
using SourceAttributeInfo = Cornerstone.Generators.Models.SourceAttributeInfo;
using SourcePropertyInfo = Cornerstone.Generators.Models.SourcePropertyInfo;
using SourceTypeInfo = Cornerstone.Generators.Models.SourceTypeInfo;

#endregion

namespace Cornerstone.Generators.Processors;

internal sealed class SqlReflectionsProcessor : ITypeProcessor
{
	#region Fields

	private string _generatedNamespace;

	#endregion

	#region Properties

	public bool EmitsInsideTypeBlock => false;

	#endregion

	#region Methods

	public void Process(CSharpCodeBuilder builder, SourceTypeInfo type)
	{
		if (!ShouldProcess(type))
		{
			return;
		}

		builder.WriteAutoGeneratedComment();
		WriteCornerstoneGeneratedClass(builder, _generatedNamespace, () =>
			{
				var tableName = GetSqlTableName(type);
				var columns = GetSqlColumnProperties(type);

				builder.IndentWriteLine($"private static readonly string {type.FullyQualifiedSourceReflectorName}CreateTableSqlite =");
				builder.IncreaseIndent();
				builder.IndentWriteLine("\"\"\"");
				AppendTableSqlite(builder, tableName, columns);
				builder.IndentWriteLine("\"\"\";");
				builder.DecreaseIndent();
				builder.WriteLine();

				builder.IndentWriteLine($"private static readonly string {type.FullyQualifiedSourceReflectorName}CreateTableSqlServer =");
				builder.IncreaseIndent();
				builder.IndentWriteLine("\"\"\"");
				AppendTableSqlServer(builder, tableName, columns);
				builder.IndentWriteLine("\"\"\";");
				builder.DecreaseIndent();
				builder.WriteLine();

				builder.IndentWriteLine($"private static readonly string {type.FullyQualifiedSourceReflectorName}UpsertSqlite =");
				builder.IncreaseIndent();
				builder.IndentWriteLine("\"\"\"");
				var sqliteParamMap = AppendUpsertSqlite(builder, tableName, columns);
				builder.IndentWriteLine("\"\"\";");
				builder.DecreaseIndent();
				builder.WriteLine();

				builder.IndentWriteLine($"private static readonly string {type.FullyQualifiedSourceReflectorName}UpsertSqlServer =");
				builder.IncreaseIndent();
				builder.IndentWriteLine("\"\"\"");
				var sqlServerParamMap = AppendUpsertSqlServer(builder, tableName, columns);
				builder.IndentWriteLine("\"\"\";");
				builder.DecreaseIndent();
				builder.WriteLine();

				builder.IndentWriteLine($"private static readonly string {type.FullyQualifiedSourceReflectorName}DeleteSqlite =");
				builder.IncreaseIndent();
				builder.IndentWriteLine("\"\"\"");
				AppendDeleteSqlite(builder, tableName, columns);
				builder.IndentWriteLine("\"\"\";");
				builder.DecreaseIndent();
				builder.WriteLine();

				builder.IndentWriteLine($"private static readonly string {type.FullyQualifiedSourceReflectorName}DeleteSqlServer =");
				builder.IncreaseIndent();
				builder.IndentWriteLine("\"\"\"");
				AppendDeleteSqlServer(builder, tableName, columns);
				builder.IndentWriteLine("\"\"\";");
				builder.DecreaseIndent();
				builder.WriteLine();

				Dictionary<string, string> syncParamMap = null;
				if (ShouldProcessSyncUpsert(columns))
				{
					builder.IndentWriteLine($"private static readonly string {type.FullyQualifiedSourceReflectorName}SyncUpsertSqlite =");
					builder.IncreaseIndent();
					builder.IndentWriteLine("\"\"\"");
					syncParamMap = AppendSyncUpsertSqlite(builder, tableName, columns);
					builder.IndentWriteLine("\"\"\";");
					builder.DecreaseIndent();
					builder.WriteLine();

					builder.IndentWriteLine($"private static readonly string {type.FullyQualifiedSourceReflectorName}SyncUpsertSqlServer =");
					builder.IncreaseIndent();
					builder.IndentWriteLine("\"\"\"");
					AppendSyncUpsertSqlServer(builder, tableName, columns);
					builder.IndentWriteLine("\"\"\";");
					builder.DecreaseIndent();
					builder.WriteLine();
				}

				EmitGetPrimaryKeyParameters(builder, type, columns);
				EmitGetInsertParameters(builder, type, columns, sqliteParamMap, "GetUpsertParamsSqlite");
				EmitGetInsertParameters(builder, type, columns, sqlServerParamMap, "GetUpsertParamsSqlServer");
				if (syncParamMap != null)
				{
					EmitGetInsertParameters(builder, type, columns, syncParamMap, "GetSyncUpsertParams");
				}
			});
	}

	/// <summary>
	/// Also used by the module initializer to decide whether to register SQL scripts.
	/// </summary>
	internal static bool ShouldProcess(SourceTypeInfo sourceTypeInfo)
	{
		return sourceTypeInfo.Attributes.Any(x => x.Name is NameSqlTableAttribute);
	}

	/// <summary>
	/// True when the type has SyncId + ModifiedOn and SyncId is not the primary key.
	/// </summary>
	internal static bool ShouldProcessSyncUpsert(SourceTypeInfo sourceTypeInfo)
	{
		return ShouldProcess(sourceTypeInfo) && ShouldProcessSyncUpsert(GetSqlColumnProperties(sourceTypeInfo));
	}

	/// <summary>
	/// True when the type inherits SyncEntity&lt;TKey&gt;. Used to emit a closed
	/// SqlSyncableRepository&lt;T, TKey&gt; factory (AOT-safe, no MakeGenericType).
	/// </summary>
	internal static bool TryGetSyncEntityKeyGlobalName(SourceTypeInfo sourceTypeInfo, out string keyGlobalName)
	{
		keyGlobalName = null;
		if (!ShouldProcess(sourceTypeInfo))
		{
			return false;
		}

		for (var current = sourceTypeInfo.TypeSymbol; current != null; current = current.BaseType)
		{
			if ((current.OriginalDefinition.Name == "SyncEntity") && (current.TypeArguments.Length == 1))
			{
				keyGlobalName = current.TypeArguments[0].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
				return true;
			}
		}

		return false;
	}

	private static void AppendDeleteSqlite(CSharpCodeBuilder builder, string tableName, List<SourcePropertyInfo> columns)
	{
		var pkColumn = FindPrimaryKeyColumn(columns);
		var pkColumnName = GetSqlColumnName(pkColumn, GetSqlColumnAttributeInfo(pkColumn));
		builder.IndentWriteLine($"DELETE FROM \"{tableName}\" WHERE \"{pkColumnName}\" = @p0;");
	}

	private static void AppendDeleteSqlServer(CSharpCodeBuilder builder, string tableName, List<SourcePropertyInfo> columns)
	{
		var pkColumn = FindPrimaryKeyColumn(columns);
		var pkColumnName = GetSqlColumnName(pkColumn, GetSqlColumnAttributeInfo(pkColumn));
		builder.IndentWriteLine($"DELETE FROM [{tableName}] WHERE [{pkColumnName}] = @p0;");
	}

	private static void AppendTableSqlite(CSharpCodeBuilder builder, string tableName, List<SourcePropertyInfo> columns)
	{
		builder.IndentWriteLine($"CREATE TABLE \"{tableName}\"");
		builder.IndentWrite("(");
		builder.IncreaseIndent();

		for (var index = 0; index < columns.Count; index++)
		{
			builder.WriteLine(index > 0 ? "," : string.Empty);

			var prop = columns[index];
			var columnAttr = GetSqlColumnAttributeInfo(prop);
			var columnName = GetSqlColumnName(prop, columnAttr);
			var sqlType = GetSqliteTypeFromSymbol(prop.PropertySymbol.Type);
			builder.IndentWrite($"\"{columnName}\" {sqlType}");

			if (ShouldWriteNotNull(prop, columnAttr))
			{
				builder.Write(" NOT NULL");
			}

			if ((columnAttr != null) && TryGetNamedArg(columnAttr, "IsPrimaryKey", out bool isPk) && isPk)
			{
				var isAutoIncrement = TryGetNamedArg(columnAttr, "IsAutoIncrement", out bool autoInc) && autoInc;
				builder.Write(isAutoIncrement
					? " PRIMARY KEY AUTOINCREMENT"
					: " PRIMARY KEY"
				);
			}
			else if (IsUniqueColumn(columnAttr))
			{
				builder.Write(" UNIQUE");
			}
		}

		AppendForeignKeys(builder, tableName, columns, false);
		builder.WriteLine();
		builder.DecreaseIndent();
		builder.IndentWriteLine(");");
	}

	private static void AppendTableSqlServer(CSharpCodeBuilder builder, string tableName, List<SourcePropertyInfo> columns)
	{
		builder.IndentWriteLine($"CREATE TABLE [{tableName}]");
		builder.IndentWrite("(");
		builder.IncreaseIndent();

		var primaryKeys = new List<(SourcePropertyInfo prop, string columnName)>();
		for (var index = 0; index < columns.Count; index++)
		{
			builder.WriteLine(index > 0 ? "," : string.Empty);

			var prop = columns[index];
			var columnAttr = GetSqlColumnAttributeInfo(prop);
			var columnName = GetSqlColumnName(prop, columnAttr);
			var sqlType = GetSqlServerTypeFromSymbol(prop, columnAttr);
			builder.IndentWrite($"\"{columnName}\" {sqlType}");

			if (ShouldWriteNotNull(prop, columnAttr))
			{
				builder.Write(" NOT NULL");
			}

			if ((columnAttr != null) && TryGetNamedArg(columnAttr, "IsPrimaryKey", out bool isPk) && isPk)
			{
				if (TryGetNamedArg(columnAttr, "IsAutoIncrement", out bool autoInc) && autoInc)
				{
					builder.Write(" IDENTITY(1,1)");
				}
				primaryKeys.Add((prop, columnName));
			}
		}

		if (primaryKeys.Count > 0)
		{
			builder.WriteLine(",");
			builder.IndentWrite($"CONSTRAINT PK_{tableName} PRIMARY KEY CLUSTERED (");
			foreach (var key in primaryKeys)
			{
				builder.Write($"[{key.columnName}]");
			}
			builder.Write(")");
		}

		foreach (var uniqueColumn in columns
			.Select(c => (prop: c, attr: GetSqlColumnAttributeInfo(c)))
			.Where(c => IsUniqueColumn(c.attr) && !IsPrimaryKeyColumn(c.attr))
			.Select(c => GetSqlColumnName(c.prop, c.attr)))
		{
			builder.WriteLine(",");
			builder.IndentWrite($"CONSTRAINT UQ_{tableName}_{uniqueColumn} UNIQUE ([{uniqueColumn}])");
		}

		AppendForeignKeys(builder, tableName, columns, true);
		builder.WriteLine();
		builder.DecreaseIndent();
		builder.IndentWriteLine(");");
	}

	private static void AppendForeignKeys(CSharpCodeBuilder builder, string tableName, List<SourcePropertyInfo> columns, bool sqlServer)
	{
		foreach (var prop in columns)
		{
			var fkAttr = prop.Attributes.FirstOrDefault(a =>
				(a.Name == "SqlForeignKeyAttribute") || (a.Name == "SqlForeignKey"));
			if (fkAttr == null)
			{
				continue;
			}

			var principalTable = fkAttr.ConstructorArguments.Length > 0
				? fkAttr.ConstructorArguments[0] as string
				: null;
			if (string.IsNullOrWhiteSpace(principalTable))
			{
				continue;
			}

			var principalColumn = "Id";
			if (TryGetNamedArg(fkAttr, "PrincipalColumn", out string named) && !string.IsNullOrWhiteSpace(named))
			{
				principalColumn = named;
			}

			var columnAttr = GetSqlColumnAttributeInfo(prop);
			var columnName = GetSqlColumnName(prop, columnAttr);
			builder.WriteLine(",");
			if (sqlServer)
			{
				builder.IndentWrite(
					$"CONSTRAINT FK_{tableName}_{principalTable}_{columnName} FOREIGN KEY ([{columnName}]) REFERENCES [{principalTable}]([{principalColumn}])");
			}
			else
			{
				builder.IndentWrite(
					$"FOREIGN KEY (\"{columnName}\") REFERENCES \"{principalTable}\" (\"{principalColumn}\")");
			}
		}
	}

	private static Dictionary<string, string> AppendUpsertSqlite(CSharpCodeBuilder builder, string tableName, List<SourcePropertyInfo> columns)
	{
		var pkColumn = FindPrimaryKeyColumn(columns);
		var pkColumnName = GetSqlColumnName(pkColumn, GetSqlColumnAttributeInfo(pkColumn));

		var nonPkColumns = columns.Where(c => c.Name != pkColumn.Name).ToList();
		var columnNames = nonPkColumns.Select(c => GetSqlColumnName(c, GetSqlColumnAttributeInfo(c))).ToArray();
		var paramMap = new Dictionary<string, string>();
		var index = 0;
		foreach (var col in nonPkColumns)
		{
			paramMap[$"@p{index++}"] = col.Name;
		}

		builder.IndentWrite($"INSERT INTO \"{tableName}\" (\"");
		builder.Write(string.Join("\", \"", columnNames));
		builder.WriteLine("\")");
		builder.IncreaseIndent();
		builder.IndentWrite("VALUES (");
		builder.Write(string.Join(", ", paramMap.Keys));
		builder.WriteLine(")");
		builder.DecreaseIndent();

		builder.IndentWrite($"ON CONFLICT(\"{pkColumnName}\") DO UPDATE SET");
		builder.IncreaseIndent();

		var assignments = columnNames.Zip(paramMap.Keys, (col, param) => $"\"{col}\" = {param}").ToArray();
		for (var i = 0; i < assignments.Length; i++)
		{
			builder.WriteLine(i > 0 ? "," : string.Empty);
			builder.IndentWrite(assignments[i]);
		}

		builder.WriteLine();
		builder.DecreaseIndent();
		builder.IndentWriteLine($"RETURNING \"{pkColumnName}\";");

		return paramMap.ToDictionary(x => x.Key, x => x.Value);
	}

	private static Dictionary<string, string> AppendSyncUpsertSqlite(CSharpCodeBuilder builder, string tableName, List<SourcePropertyInfo> columns)
	{
		var pkColumn = FindPrimaryKeyColumn(columns);
		var syncIdColumn = FindSyncIdColumn(columns);
		var modifiedOnColumn = FindModifiedOnColumn(columns);
		var syncIdColumnName = GetSqlColumnName(syncIdColumn, GetSqlColumnAttributeInfo(syncIdColumn));
		var modifiedOnColumnName = GetSqlColumnName(modifiedOnColumn, GetSqlColumnAttributeInfo(modifiedOnColumn));

		var nonPkColumns = columns.Where(c => c.Name != pkColumn.Name).ToList();
		var paramMap = new Dictionary<string, string>();
		var index = 0;
		foreach (var col in nonPkColumns)
		{
			paramMap[$"@p{index++}"] = col.Name;
		}

		var insertColumnNames = nonPkColumns
			.Select(c => GetSqlColumnName(c, GetSqlColumnAttributeInfo(c)))
			.ToArray();
		var updateAssignments = paramMap
			.Where(kvp => kvp.Value != syncIdColumn.Name)
			.Select(kvp =>
			{
				var col = nonPkColumns.First(c => c.Name == kvp.Value);
				var columnName = GetSqlColumnName(col, GetSqlColumnAttributeInfo(col));
				return $"\"{columnName}\" = {kvp.Key}";
			})
			.ToArray();
		var modifiedOnParam = paramMap.First(kvp => kvp.Value == modifiedOnColumn.Name).Key;

		builder.IndentWrite($"INSERT INTO \"{tableName}\" (\"");
		builder.Write(string.Join("\", \"", insertColumnNames));
		builder.WriteLine("\")");
		builder.IncreaseIndent();
		builder.IndentWrite("VALUES (");
		builder.Write(string.Join(", ", paramMap.Keys));
		builder.WriteLine(")");
		builder.DecreaseIndent();

		builder.IndentWrite($"ON CONFLICT(\"{syncIdColumnName}\") DO UPDATE SET");
		builder.IncreaseIndent();
		for (var i = 0; i < updateAssignments.Length; i++)
		{
			builder.WriteLine(i > 0 ? "," : string.Empty);
			builder.IndentWrite(updateAssignments[i]);
		}

		builder.WriteLine();
		builder.DecreaseIndent();
		builder.IndentWriteLine($"WHERE {modifiedOnParam} > \"{tableName}\".\"{modifiedOnColumnName}\"");
		builder.IndentWriteLine($"RETURNING \"{GetSqlColumnName(pkColumn, GetSqlColumnAttributeInfo(pkColumn))}\";");

		return paramMap;
	}

	private static Dictionary<string, string> AppendSyncUpsertSqlServer(CSharpCodeBuilder builder, string tableName, List<SourcePropertyInfo> columns)
	{
		var pkColumn = FindPrimaryKeyColumn(columns);
		var syncIdColumn = FindSyncIdColumn(columns);
		var modifiedOnColumn = FindModifiedOnColumn(columns);
		var pkColumnName = GetSqlColumnName(pkColumn, GetSqlColumnAttributeInfo(pkColumn));
		var syncIdColumnName = GetSqlColumnName(syncIdColumn, GetSqlColumnAttributeInfo(syncIdColumn));
		var modifiedOnColumnName = GetSqlColumnName(modifiedOnColumn, GetSqlColumnAttributeInfo(modifiedOnColumn));

		var nonPkColumns = columns.Where(c => c.Name != pkColumn.Name).ToList();
		var nonPkColumnNames = nonPkColumns.Select(c => GetSqlColumnName(c, GetSqlColumnAttributeInfo(c))).ToList();
		var updateColumnNames = nonPkColumns
			.Where(c => c.Name != syncIdColumn.Name)
			.Select(c => GetSqlColumnName(c, GetSqlColumnAttributeInfo(c)))
			.ToList();

		var paramMap = new Dictionary<string, string>();
		var paramNames = new List<string>();
		var index = 0;
		foreach (var col in nonPkColumns)
		{
			var paramName = $"@p{index++}";
			paramMap[paramName] = col.Name;
			paramNames.Add(paramName);
		}

		builder.IndentWriteLine($"MERGE INTO [{tableName}] AS x");
		builder.IndentWrite("USING (VALUES (");
		builder.Write(string.Join(", ", paramNames));
		builder.WriteLine("))");
		builder.IncreaseIndent();
		builder.IndentWrite("AS y ([");
		builder.Write(string.Join("], [", nonPkColumnNames));
		builder.WriteLine("])");
		builder.DecreaseIndent();

		builder.IndentWriteLine($"ON x.[{syncIdColumnName}] = y.[{syncIdColumnName}]");
		builder.IndentWriteLine($"WHEN MATCHED AND y.[{modifiedOnColumnName}] > x.[{modifiedOnColumnName}] THEN");
		builder.IncreaseIndent();
		builder.IndentWrite("UPDATE SET");
		builder.IncreaseIndent();
		for (var i = 0; i < updateColumnNames.Count; i++)
		{
			builder.WriteLine(i > 0 ? "," : string.Empty);
			builder.IndentWrite($"[{updateColumnNames[i]}] = y.[{updateColumnNames[i]}]");
		}

		builder.DecreaseIndent();
		builder.WriteLine();
		builder.DecreaseIndent();
		builder.IndentWriteLine("WHEN NOT MATCHED THEN");
		builder.IncreaseIndent();
		builder.IndentWrite("INSERT ([");
		builder.Write(string.Join("], [", nonPkColumnNames));
		builder.WriteLine("])");
		builder.IndentWrite("VALUES (");
		builder.Write(string.Join(", ", nonPkColumnNames.Select(n => $"y.[{n}]")));
		builder.WriteLine(")");
		builder.IndentWriteLine($"OUTPUT inserted.[{pkColumnName}];");
		builder.DecreaseIndent();

		return paramMap;
	}

	private static Dictionary<string, string> AppendUpsertSqlServer(CSharpCodeBuilder builder, string tableName, List<SourcePropertyInfo> columns)
	{
		var pkColumn = FindPrimaryKeyColumn(columns);
		var pkColumnName = GetSqlColumnName(pkColumn, GetSqlColumnAttributeInfo(pkColumn));
		var nonPkColumns = columns.Where(c => GetSqlColumnName(c, GetSqlColumnAttributeInfo(c)) != pkColumnName).ToList();
		var nonPkColumnNames = nonPkColumns.Select(c => GetSqlColumnName(c, GetSqlColumnAttributeInfo(c))).ToList();

		var paramMap = new Dictionary<string, string>();
		var nonPkParamNames = new List<string>();
		var index = 0;
		foreach (var col in nonPkColumns)
		{
			var paramName = $"@p{index++}";
			paramMap[paramName] = col.Name;
			nonPkParamNames.Add(paramName);
		}

		var pkParamName = $"@p{index}";
		paramMap[pkParamName] = pkColumn.Name;

		builder.IndentWriteLine($"MERGE INTO [{tableName}] AS x");
		builder.IndentWrite("USING (VALUES (");
		builder.Write(string.Join(", ", nonPkParamNames));
		builder.WriteLine("))");
		builder.IncreaseIndent();
		builder.IndentWrite("AS y ([");
		builder.Write(string.Join("], [", nonPkColumnNames));
		builder.WriteLine("])");
		builder.DecreaseIndent();

		builder.IndentWriteLine($"ON x.[{pkColumnName}] = {pkParamName}");

		builder.IndentWriteLine("WHEN MATCHED THEN");
		builder.IncreaseIndent();
		builder.IndentWrite("UPDATE SET");
		builder.IncreaseIndent();

		for (var i = 0; i < nonPkColumnNames.Count; i++)
		{
			builder.WriteLine(i > 0 ? "," : string.Empty);
			builder.IndentWrite($"[{nonPkColumnNames[i]}] = y.[{nonPkColumnNames[i]}]");
		}

		builder.DecreaseIndent();
		builder.WriteLine();
		builder.IndentWriteLine("WHEN NOT MATCHED THEN");
		builder.IndentWrite("INSERT ([");
		builder.Write(string.Join("], [", nonPkColumnNames));
		builder.WriteLine("])");
		builder.IndentWrite("VALUES (");
		builder.Write(string.Join(", ", nonPkColumnNames.Select(n => $"y.[{n}]")));
		builder.WriteLine(")");
		builder.IndentWriteLine($"OUTPUT inserted.[{pkColumnName}];");
		builder.DecreaseIndent();

		return paramMap.ToDictionary(x => x.Key, x => x.Value);
	}

	private static void EmitGetInsertParameters(CSharpCodeBuilder builder, SourceTypeInfo type,
		List<SourcePropertyInfo> columns, Dictionary<string, string> paramToProperty, string methodName)
	{
		builder.WriteBlock(
			$"public static global::System.Collections.Generic.IDictionary<string, (object, global::System.Type)> {type.FullyQualifiedSourceReflectorName}{methodName}(object obj)",
			() =>
			{
				builder.IndentWriteLine($"var entity = ({type.FullyGlobalQualifiedName}) obj;");
				builder.WriteBlock("return new global::System.Collections.Generic.Dictionary<string, (object, global::System.Type)>",
					() =>
					{
						foreach (var kvp in paramToProperty)
						{
							var prop = columns.First(c => c.Name == kvp.Value);
							builder.IndentWriteLine($"[\"{kvp.Key}\"] = (entity.{prop.Name}, typeof({prop.GlobalFullyQualifiedName})),");
						}
					}, ";");
			});
	}

	private static void EmitGetPrimaryKeyParameters(CSharpCodeBuilder builder, SourceTypeInfo type, List<SourcePropertyInfo> columns)
	{
		var pkColumn = FindPrimaryKeyColumn(columns);

		builder.WriteBlock(
			$"public static (object, global::System.Type) {type.FullyQualifiedSourceReflectorName}GetPrimaryKey(object obj)",
			() =>
			{
				builder.IndentWriteLine($"var entity = ({type.FullyGlobalQualifiedName}) obj;");
				builder.IndentWriteLine($"return (entity.{pkColumn.Name}, typeof({pkColumn.GlobalFullyQualifiedName}));");
			});
	}

	private static SourcePropertyInfo FindColumnByName(List<SourcePropertyInfo> columns, string name)
	{
		return columns.FirstOrDefault(c => c.Name == name);
	}

	private static SourcePropertyInfo FindModifiedOnColumn(List<SourcePropertyInfo> columns)
	{
		return FindColumnByName(columns, "ModifiedOn");
	}

	private static SourcePropertyInfo FindPrimaryKeyColumn(List<SourcePropertyInfo> columns)
	{
		return columns.FirstOrDefault(p => IsPrimaryKeyColumn(GetSqlColumnAttributeInfo(p)))
			?? columns.FirstOrDefault(x => x.Name == "Id")
			?? columns.FirstOrDefault();
	}

	private static SourcePropertyInfo FindSyncIdColumn(List<SourcePropertyInfo> columns)
	{
		return FindColumnByName(columns, "SyncId");
	}

	private static bool IsPrimaryKeyColumn(SourceAttributeInfo columnAttr)
	{
		return (columnAttr != null) && TryGetNamedArg(columnAttr, "IsPrimaryKey", out bool isPk) && isPk;
	}

	private static bool IsUniqueColumn(SourceAttributeInfo columnAttr)
	{
		return (columnAttr != null) && TryGetNamedArg(columnAttr, "IsUnique", out bool isUnique) && isUnique;
	}

	private static bool ShouldProcessSyncUpsert(List<SourcePropertyInfo> columns)
	{
		var pkColumn = FindPrimaryKeyColumn(columns);
		var syncIdColumn = FindSyncIdColumn(columns);
		var modifiedOnColumn = FindModifiedOnColumn(columns);
		return (syncIdColumn != null)
			&& (modifiedOnColumn != null)
			&& (pkColumn != null)
			&& (syncIdColumn.Name != pkColumn.Name);
	}

	private static IList<IPropertySymbol> GetAllProperties(INamedTypeSymbol type)
	{
		return GetAllMembers(type)
			.Where(x => x is IPropertySymbol)
			.Cast<IPropertySymbol>()
			.ToList();
	}

	private static SourceAttributeInfo GetSqlColumnAttributeInfo(SourcePropertyInfo prop)
	{
		return prop.Attributes.FirstOrDefault(a => a.Name == NameSqlTableColumnAttribute);
	}

	private static string GetSqlColumnName(SourcePropertyInfo prop, SourceAttributeInfo columnAttr)
	{
		if ((columnAttr != null)
			&& TryGetNamedArg(columnAttr, "Name", out string name)
			&& !string.IsNullOrWhiteSpace(name))
		{
			return name;
		}

		return prop.Name;
	}

	private static List<SourcePropertyInfo> GetSqlColumnProperties(SourceTypeInfo type)
	{
		var declaredByName = type.Properties.ToDictionary(p => p.Name);

		return GetAllProperties(type.TypeSymbol)
			.Where(p => !p.IsStatic
				&& !p.IsIndexer
				&& (p.GetMethod != null)
				&& (p.SetMethod != null))
			.GroupBy(p => p.Name)
			.Select(g => declaredByName.TryGetValue(g.Key, out var existing) ? existing : CreatePropertyInfo(g.First()))
			.OrderBy(p => p.Name)
			.ToList();
	}

	private static string GetSqliteTypeFromSymbol(ITypeSymbol typeSymbol)
	{
		var type = UnwrapEnum(UnwrapNullable(typeSymbol));

		return type.SpecialType switch
		{
			SpecialType.System_String => "TEXT",
			SpecialType.System_Int32 or SpecialType.System_UInt32 or
				SpecialType.System_Int64 or SpecialType.System_UInt64 or
				SpecialType.System_Int16 or SpecialType.System_UInt16 or
				SpecialType.System_Byte or SpecialType.System_SByte or
				SpecialType.System_Boolean => "INTEGER",
			SpecialType.System_DateTime => "DATE",
			SpecialType.System_Decimal or SpecialType.System_Double or
				SpecialType.System_Single => "REAL",
			_ => MapNonSpecialTypeToSqlite(type)
		};
	}

	private static string GetSqlServerTypeFromSymbol(SourcePropertyInfo prop, SourceAttributeInfo columnAttr)
	{
		var typeSymbol = UnwrapEnum(UnwrapNullable(prop.PropertySymbol.Type));

		if (typeSymbol.SpecialType == SpecialType.System_String)
		{
			var maxLength = 0;
			if ((columnAttr != null) && TryGetNamedArg(columnAttr, "MaxLength", out int ml))
			{
				maxLength = ml;
			}

			return maxLength is > 0 and <= 4000
				? $"NVARCHAR({maxLength})"
				: "NVARCHAR(MAX)";
		}

		return typeSymbol.SpecialType switch
		{
			SpecialType.System_Int32 or SpecialType.System_UInt32 => "INT",
			SpecialType.System_Int64 or SpecialType.System_UInt64 => "BIGINT",
			SpecialType.System_Int16 or SpecialType.System_UInt16 => "SMALLINT",
			SpecialType.System_Byte or SpecialType.System_SByte => "TINYINT",
			SpecialType.System_Boolean => "BIT",
			SpecialType.System_DateTime => "DATETIME2",
			SpecialType.System_Decimal => "DECIMAL(18,6)",
			SpecialType.System_Double or SpecialType.System_Single => "FLOAT",
			_ => MapNonSpecialTypeToSqlServer(typeSymbol)
		};
	}

	private static string GetSqlTableName(SourceTypeInfo type)
	{
		var attr = type.Attributes.FirstOrDefault(a => a.Name == NameSqlTableAttribute);
		if (attr != null)
		{
			if (attr.NamedArguments.TryGetValue("TableName", out var tableNameObj)
				&& tableNameObj is string tableName
				&& !string.IsNullOrWhiteSpace(tableName))
			{
				return tableName;
			}

			if ((attr.ConstructorArguments.Length > 0)
				&& attr.ConstructorArguments[0] is string ctorName
				&& !string.IsNullOrWhiteSpace(ctorName))
			{
				return ctorName;
			}
		}

		return $"{type.Name}s";
	}

	void ITypeProcessor.Initialize(Compilation compilation)
	{
		_generatedNamespace = GetCornerstoneGeneratedNamespace(compilation);
	}

	private static bool IsNullableSymbol(ITypeSymbol typeSymbol)
	{
		if (typeSymbol is INamedTypeSymbol { OriginalDefinition.SpecialType: SpecialType.System_Nullable_T })
		{
			return true;
		}

		return typeSymbol.IsReferenceType;
	}

	/// <summary>
	/// NOT NULL when the CLR type cannot be null, or [SqlTableColumn(IsNullable = false)] is set.
	/// </summary>
	private static bool ShouldWriteNotNull(SourcePropertyInfo prop, SourceAttributeInfo columnAttr)
	{
		if (!IsNullableSymbol(prop.PropertySymbol.Type))
		{
			return true;
		}

		return (columnAttr != null)
			&& TryGetNamedArg(columnAttr, "IsNullable", out bool isNullable)
			&& !isNullable;
	}

	private static string MapNonSpecialTypeToSqlite(ITypeSymbol type)
	{
		var fqn = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
		return fqn switch
		{
			"global::System.Guid" => "TEXT",
			"byte[]" => "BLOB",
			_ when type is IArrayTypeSymbol { ElementType.SpecialType: SpecialType.System_Byte } => "BLOB",
			_ => throw new NotSupportedException($"Type not supported for SQLite mapping: {fqn}")
		};
	}

	private static string MapNonSpecialTypeToSqlServer(ITypeSymbol type)
	{
		var fqn = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
		return fqn switch
		{
			"global::System.Guid" => "UNIQUEIDENTIFIER",
			_ when type is IArrayTypeSymbol { ElementType.SpecialType: SpecialType.System_Byte } => "VARBINARY(MAX)",
			_ => throw new NotSupportedException($"Type not supported for SQL Server mapping: {fqn}")
		};
	}

	private static bool TryGetNamedArg<T>(SourceAttributeInfo attr, string argName, out T value)
	{
		if (attr.NamedArguments.TryGetValue(argName, out var obj) && obj is T typed)
		{
			value = typed;
			return true;
		}

		value = default;
		return false;
	}

	private static ITypeSymbol UnwrapEnum(ITypeSymbol typeSymbol)
	{
		if ((typeSymbol.TypeKind == TypeKind.Enum) && typeSymbol is INamedTypeSymbol namedType)
		{
			return namedType.EnumUnderlyingType ?? typeSymbol;
		}

		return typeSymbol;
	}

	private static ITypeSymbol UnwrapNullable(ITypeSymbol typeSymbol)
	{
		if (typeSymbol is INamedTypeSymbol { OriginalDefinition.SpecialType: SpecialType.System_Nullable_T } nullable)
		{
			return nullable.TypeArguments[0];
		}

		return typeSymbol;
	}

	#endregion
}