#region References

using Microsoft.VisualStudio.TestTools.UnitTesting;

#endregion

namespace Cornerstone.Generators.UnitTests.Cornerstone;

[TestClass]
public class StyledPropertyTests : GeneratorUnitTest
{
	#region Methods

	[TestMethod]
	public void Styled()
	{
		var input = """
					public partial class Test : Control
					{
						[StyledProperty]
						public partial int Bar { get; set; }
					}
					""";

		// Generated Code - Expected
		var expected = new[]
		{
			"""
			using System;
			using System.Collections.Generic;
			// <auto-generated>
			// Auto-generated by Cornerstone.Generators
			// </auto-generated>
			partial class Test
			{
				public static readonly global::Cornerstone.Presentation.StyledProperty<global::System.Int32> BarProperty = global::Cornerstone.Presentation.PresentationProperty.Register<global::Test, global::System.Int32>(nameof(Bar));
				public partial global::System.Int32 Bar
				{
					get => GetValue(BarProperty);
					set => SetValue(BarProperty, value);
				}
			}
			""",
			"""
			// <auto-generated>
			// Auto-generated by Cornerstone.Generators
			// </auto-generated>
			namespace TestCompilation
			{
				public static partial class CornerstoneGenerated
				{
					[global::System.Runtime.CompilerServices.ModuleInitializer]
					public static void Initialize()
					{
					}
				}
			}
			"""
		};
		// Generated Code - /Expected

		ValidateSource(input, expected);
	}

	[TestMethod]
	public void StyledCoerceCallback()
	{
		var input = """
					public partial class Test : Control
					{
						[StyledProperty(Coerce = "Coerce")]
						public partial int Bar { get; set; }
						
						private static int Coerce(PresentationObject arg1, int arg2)
						{
							return 456;
						}
					}
					""";

		// Generated Code - Expected
		var expected = new[]
		{
			"""
			using System;
			using System.Collections.Generic;
			// <auto-generated>
			// Auto-generated by Cornerstone.Generators
			// </auto-generated>
			partial class Test
			{
				public static readonly global::Cornerstone.Presentation.StyledProperty<global::System.Int32> BarProperty = global::Cornerstone.Presentation.PresentationProperty.Register<global::Test, global::System.Int32>(nameof(Bar), coerce: Coerce);
				public partial global::System.Int32 Bar
				{
					get => GetValue(BarProperty);
					set => SetValue(BarProperty, value);
				}
			}
			""",
			"""
			// <auto-generated>
			// Auto-generated by Cornerstone.Generators
			// </auto-generated>
			namespace TestCompilation
			{
				public static partial class CornerstoneGenerated
				{
					[global::System.Runtime.CompilerServices.ModuleInitializer]
					public static void Initialize()
					{
					}
				}
			}
			"""
		};
		// Generated Code - /Expected

		ValidateSource(input, expected);
	}

	[TestMethod]
	public void StyledDefaultBindingMode()
	{
		var input = """
					public partial class Test : Control
					{
						[StyledProperty(DefaultBindingMode = BindingMode.TwoWay)]
						public partial int Bar { get; set; }
					}
					""";

		// Generated Code - Expected
		var expected = new[]
		{
			"""
			using System;
			using System.Collections.Generic;
			// <auto-generated>
			// Auto-generated by Cornerstone.Generators
			// </auto-generated>
			partial class Test
			{
				public static readonly global::Cornerstone.Presentation.StyledProperty<global::System.Int32> BarProperty = global::Cornerstone.Presentation.PresentationProperty.Register<global::Test, global::System.Int32>(nameof(Bar), defaultBindingMode: global::Cornerstone.Presentation.Data.BindingMode.TwoWay);
				public partial global::System.Int32 Bar
				{
					get => GetValue(BarProperty);
					set => SetValue(BarProperty, value);
				}
			}
			""",
			"""
			// <auto-generated>
			// Auto-generated by Cornerstone.Generators
			// </auto-generated>
			namespace TestCompilation
			{
				public static partial class CornerstoneGenerated
				{
					[global::System.Runtime.CompilerServices.ModuleInitializer]
					public static void Initialize()
					{
					}
				}
			}
			"""
		};
		// Generated Code - /Expected

		ValidateSource(input, expected);
	}

	[TestMethod]
	public void StyledDefaultValue()
	{
		var input = """
					public partial class Test : Control
					{
						[StyledProperty(DefaultValue = 123)]
						public partial int Bar { get; set; }
					}
					""";

		// Generated Code - Expected
		var expected = new[]
		{
			"""
			using System;
			using System.Collections.Generic;
			// <auto-generated>
			// Auto-generated by Cornerstone.Generators
			// </auto-generated>
			partial class Test
			{
				public static readonly global::Cornerstone.Presentation.StyledProperty<global::System.Int32> BarProperty = global::Cornerstone.Presentation.PresentationProperty.Register<global::Test, global::System.Int32>(nameof(Bar), defaultValue: 123);
				public partial global::System.Int32 Bar
				{
					get => GetValue(BarProperty);
					set => SetValue(BarProperty, value);
				}
			}
			""",
			"""
			// <auto-generated>
			// Auto-generated by Cornerstone.Generators
			// </auto-generated>
			namespace TestCompilation
			{
				public static partial class CornerstoneGenerated
				{
					[global::System.Runtime.CompilerServices.ModuleInitializer]
					public static void Initialize()
					{
					}
				}
			}
			"""
		};
		// Generated Code - /Expected

		ValidateSource(input, expected);
	}

	[TestMethod]
	public void StyledDefaultValueCallback()
	{
		var input = """
					public partial class Test : Control
					{
						[StyledProperty(DefaultValueCallback = "GetDefaultValue")]
						public partial int Bar { get; set; }
						
						public static int GetDefaultValue()
						{
							return 123;
						}
					}
					""";

		// Generated Code - Expected
		var expected = new[]
		{
			"""
			using System;
			using System.Collections.Generic;
			// <auto-generated>
			// Auto-generated by Cornerstone.Generators
			// </auto-generated>
			partial class Test
			{
				public static readonly global::Cornerstone.Presentation.StyledProperty<global::System.Int32> BarProperty = global::Cornerstone.Presentation.PresentationProperty.Register<global::Test, global::System.Int32>(nameof(Bar), defaultValue: GetDefaultValue());
				public partial global::System.Int32 Bar
				{
					get => GetValue(BarProperty);
					set => SetValue(BarProperty, value);
				}
			}
			""",
			"""
			// <auto-generated>
			// Auto-generated by Cornerstone.Generators
			// </auto-generated>
			namespace TestCompilation
			{
				public static partial class CornerstoneGenerated
				{
					[global::System.Runtime.CompilerServices.ModuleInitializer]
					public static void Initialize()
					{
					}
				}
			}
			"""
		};
		// Generated Code - /Expected

		ValidateSource(input, expected);
	}

	[TestMethod]
	public void StyledEnableDataValidation()
	{
		var input = """
					public partial class Test : Control
					{
						[StyledProperty(EnableDataValidation = true)]
						public partial int Bar { get; set; }
					}
					""";

		// Generated Code - Expected
		var expected = new[]
		{
			"""
			using System;
			using System.Collections.Generic;
			// <auto-generated>
			// Auto-generated by Cornerstone.Generators
			// </auto-generated>
			partial class Test
			{
				public static readonly global::Cornerstone.Presentation.StyledProperty<global::System.Int32> BarProperty = global::Cornerstone.Presentation.PresentationProperty.Register<global::Test, global::System.Int32>(nameof(Bar), enableDataValidation: true);
				public partial global::System.Int32 Bar
				{
					get => GetValue(BarProperty);
					set => SetValue(BarProperty, value);
				}
			}
			""",
			"""
			// <auto-generated>
			// Auto-generated by Cornerstone.Generators
			// </auto-generated>
			namespace TestCompilation
			{
				public static partial class CornerstoneGenerated
				{
					[global::System.Runtime.CompilerServices.ModuleInitializer]
					public static void Initialize()
					{
					}
				}
			}
			"""
		};
		// Generated Code - /Expected

		ValidateSource(input, expected);
	}

	[TestMethod]
	public void StyledInherits()
	{
		var input = """
					public partial class Test : Control
					{
						[StyledProperty(Inherits = true)]
						public partial int Bar { get; set; }
					}
					""";

		// Generated Code - Expected
		var expected = new[]
		{
			"""
			using System;
			using System.Collections.Generic;
			// <auto-generated>
			// Auto-generated by Cornerstone.Generators
			// </auto-generated>
			partial class Test
			{
				public static readonly global::Cornerstone.Presentation.StyledProperty<global::System.Int32> BarProperty = global::Cornerstone.Presentation.PresentationProperty.Register<global::Test, global::System.Int32>(nameof(Bar), inherits: true);
				public partial global::System.Int32 Bar
				{
					get => GetValue(BarProperty);
					set => SetValue(BarProperty, value);
				}
			}
			""",
			"""
			// <auto-generated>
			// Auto-generated by Cornerstone.Generators
			// </auto-generated>
			namespace TestCompilation
			{
				public static partial class CornerstoneGenerated
				{
					[global::System.Runtime.CompilerServices.ModuleInitializer]
					public static void Initialize()
					{
					}
				}
			}
			"""
		};
		// Generated Code - /Expected

		ValidateSource(input, expected);
	}

	[TestMethod]
	public void StyledValidate()
	{
		var input = """
					public partial class Test : Control
					{
						[StyledProperty(Validate = nameof(Validate))]
						public partial int Bar { get; set; }
						
						private static bool Validate(int arg)
						{
							return true;
						}
					}
					""";

		// Generated Code - Expected
		var expected = new[]
		{
			"""
			using System;
			using System.Collections.Generic;
			// <auto-generated>
			// Auto-generated by Cornerstone.Generators
			// </auto-generated>
			partial class Test
			{
				public static readonly global::Cornerstone.Presentation.StyledProperty<global::System.Int32> BarProperty = global::Cornerstone.Presentation.PresentationProperty.Register<global::Test, global::System.Int32>(nameof(Bar), validate: Validate);
				public partial global::System.Int32 Bar
				{
					get => GetValue(BarProperty);
					set => SetValue(BarProperty, value);
				}
			}
			""",
			"""
			// <auto-generated>
			// Auto-generated by Cornerstone.Generators
			// </auto-generated>
			namespace TestCompilation
			{
				public static partial class CornerstoneGenerated
				{
					[global::System.Runtime.CompilerServices.ModuleInitializer]
					public static void Initialize()
					{
					}
				}
			}
			"""
		};
		// Generated Code - /Expected

		ValidateSource(input, expected);
	}

	#endregion
}