#region References

using Microsoft.VisualStudio.TestTools.UnitTesting;

#endregion

namespace Cornerstone.Generators.UnitTests.SqlReflection;

[TestClass]
public class SqlReflectionTests : GeneratorUnitTest
{
	#region Methods

	[TestMethod]
	public void TypeQueries()
	{
		var source = """
					namespace Cornerstone.Test.Models;

					[SqlTable]
					public partial class Account : SyncEntity<int>
					{
						[SqlTableColumn]
						public int Age { get; set; }
						
						[SqlTableColumn]
						public string Name { get; set; }
					}
					""";

		// Generated Code - Expected
		var expected = new[]
		{
			""""
			using System;
			using System.Collections.Generic;
			// <auto-generated>
			// Auto-generated by Cornerstone.Generators
			// </auto-generated>
			namespace Cornerstone.Test.Models
			{
				partial class Account
				{
					public override global::System.Collections.Generic.HashSet<string> GetDefaultIncludedProperties(global::Cornerstone.Data.UpdateableAction action)
					{
						var response = base.GetDefaultIncludedProperties(action);
						switch (action)
						{
							case global::Cornerstone.Data.UpdateableAction.SyncIncomingAdd:
							case global::Cornerstone.Data.UpdateableAction.SyncOutgoing:
							{
								response.Add("CreatedOn");
								response.Add("IsDeleted");
								response.Add("ModifiedOn");
								break;
							}
							case global::Cornerstone.Data.UpdateableAction.SyncIncomingUpdate:
							{
								response.Add("IsDeleted");
								break;
							}
							case global::Cornerstone.Data.UpdateableAction.UnwrapProxyEntity:
							case global::Cornerstone.Data.UpdateableAction.Updateable:
							case global::Cornerstone.Data.UpdateableAction.PropertyChangeTracking:
							case global::Cornerstone.Data.UpdateableAction.PartialUpdate:
							{
								response.Add("CreatedOn");
								response.Add("Id");
								response.Add("IsDeleted");
								response.Add("ModifiedOn");
								break;
							}
						}
						return response;
					}
					
					public virtual bool UpdateWith(global::Cornerstone.Test.Models.Account update, global::Cornerstone.Data.IncludeExcludeSettings settings)
					{
						if (update == null)
						{
							return false;
						}
						TryUpdateProperty(CreatedOn, update.CreatedOn, settings.ShouldProcessProperty(nameof(CreatedOn)), x => CreatedOn = x);
						TryUpdateProperty(Id, update.Id, settings.ShouldProcessProperty(nameof(Id)), x => Id = x);
						TryUpdateProperty(IsDeleted, update.IsDeleted, settings.ShouldProcessProperty(nameof(IsDeleted)), x => IsDeleted = x);
						TryUpdateProperty(ModifiedOn, update.ModifiedOn, settings.ShouldProcessProperty(nameof(ModifiedOn)), x => ModifiedOn = x);
						return true;
					}
					
					public override bool UpdatePropertyWith(string propertyName, object value)
					{
						return propertyName switch
						{
							nameof(CreatedOn) => TryUpdateProperty(CreatedOn, (global::System.DateTime)value, true, x => CreatedOn = x),
							nameof(Id) => TryUpdateProperty(Id, (int)value, true, x => Id = x),
							nameof(IsDeleted) => TryUpdateProperty(IsDeleted, (bool)value, true, x => IsDeleted = x),
							nameof(ModifiedOn) => TryUpdateProperty(ModifiedOn, (global::System.DateTime)value, true, x => ModifiedOn = x),
							_ => base.UpdatePropertyWith(propertyName, value)
						};
					}
					
					public override bool UpdateWith(object update, global::Cornerstone.Data.IncludeExcludeSettings settings)
					{
						return update switch
						{
							global::Cornerstone.Test.Models.Account value => UpdateWith(value, settings),
							_ => base.UpdateWith(update, settings)
						};
					}
				}
			}
			// <auto-generated>
			// Auto-generated by Cornerstone.Generators
			// </auto-generated>
			namespace TestCompilation
			{
				public static partial class CornerstoneGenerated
				{
					private static readonly string CornerstoneTestModelsAccountCreateTableSqlite =
						"""
						CREATE TABLE IF NOT EXISTS "Accounts"
						(
							"Age" INTEGER,
							"CreatedOn" DATE NOT NULL,
							"Id" INTEGER PRIMARY KEY AUTOINCREMENT,
							"IsDeleted" INTEGER NOT NULL,
							"ModifiedOn" DATE NOT NULL,
							"Name" TEXT,
							"SyncId" TEXT
						);
						""";
			
					private static readonly string CornerstoneTestModelsAccountCreateTableSqlServer =
						"""
						IF NOT EXISTS (SELECT * FROM [sys].[tables] WHERE [name] = 'Accounts')
						BEGIN
							CREATE TABLE [Accounts]
							(
								"Age" INT NOT NULL,
								"CreatedOn" DATETIME2 NOT NULL,
								"Id" INT NOT NULL IDENTITY(1,1),
								"IsDeleted" BIT NOT NULL,
								"ModifiedOn" DATETIME2 NOT NULL,
								"Name" NVARCHAR(MAX),
								"SyncId" UNIQUEIDENTIFIER NOT NULL,
								CONSTRAINT PK_Accounts PRIMARY KEY CLUSTERED ([Id])
							)
						END
						""";
			
					private static readonly string CornerstoneTestModelsAccountUpsertSqlite =
						"""
						INSERT INTO "Accounts" ("Age", "CreatedOn", "IsDeleted", "ModifiedOn", "Name", "SyncId")
							VALUES (@p0, @p1, @p2, @p3, @p4, @p5)
						ON CONFLICT("Id") DO UPDATE SET
							"Age" = @p0,
							"CreatedOn" = @p1,
							"IsDeleted" = @p2,
							"ModifiedOn" = @p3,
							"Name" = @p4,
							"SyncId" = @p5
						RETURNING "Id";
						""";
			
					private static readonly string CornerstoneTestModelsAccountUpsertSqlServer =
						"""
						MERGE INTO [Accounts] AS x
						USING (VALUES (@p0, @p1, @p2, @p3, @p4, @p5))
							AS y ([Age], [CreatedOn], [IsDeleted], [ModifiedOn], [Name], [SyncId])
						ON x.[Id] = @p6
						WHEN MATCHED THEN
							UPDATE SET
								[Age] = y.[Age],
								[CreatedOn] = y.[CreatedOn],
								[IsDeleted] = y.[IsDeleted],
								[ModifiedOn] = y.[ModifiedOn],
								[Name] = y.[Name],
								[SyncId] = y.[SyncId]
							WHEN NOT MATCHED THEN
							INSERT ([Age], [CreatedOn], [IsDeleted], [ModifiedOn], [Name], [SyncId])
							VALUES (y.[Age], y.[CreatedOn], y.[IsDeleted], y.[ModifiedOn], y.[Name], y.[SyncId])
							OUTPUT inserted.[Id];
						""";
			
					private static readonly string CornerstoneTestModelsAccountDeleteSqlite =
						"""
						DELETE FROM "Accounts" WHERE "Id" = @p0;
						""";
			
					private static readonly string CornerstoneTestModelsAccountDeleteSqlServer =
						"""
						DELETE FROM [Accounts] WHERE [Id] = @p0;
						""";
			
					public static (object, global::System.Type) CornerstoneTestModelsAccountGetPrimaryKey(object obj)
					{
						var entity = (global::Cornerstone.Test.Models.Account) obj;
						return (entity.Id, typeof(global::System.Int32));
					}
					public static global::System.Collections.Generic.IDictionary<string, (object, global::System.Type)> CornerstoneTestModelsAccountGetUpsertParamsSqlite(object obj)
					{
						var entity = (global::Cornerstone.Test.Models.Account) obj;
						return new global::System.Collections.Generic.Dictionary<string, (object, global::System.Type)>
						{
							["@p0"] = (entity.Age, typeof(global::System.Int32)),
							["@p1"] = (entity.CreatedOn, typeof(global::System.DateTime)),
							["@p2"] = (entity.IsDeleted, typeof(global::System.Boolean)),
							["@p3"] = (entity.ModifiedOn, typeof(global::System.DateTime)),
							["@p4"] = (entity.Name, typeof(global::System.String)),
							["@p5"] = (entity.SyncId, typeof(global::System.Guid)),
						};
					}
					public static global::System.Collections.Generic.IDictionary<string, (object, global::System.Type)> CornerstoneTestModelsAccountGetUpsertParamsSqlServer(object obj)
					{
						var entity = (global::Cornerstone.Test.Models.Account) obj;
						return new global::System.Collections.Generic.Dictionary<string, (object, global::System.Type)>
						{
							["@p0"] = (entity.Age, typeof(global::System.Int32)),
							["@p1"] = (entity.CreatedOn, typeof(global::System.DateTime)),
							["@p2"] = (entity.IsDeleted, typeof(global::System.Boolean)),
							["@p3"] = (entity.ModifiedOn, typeof(global::System.DateTime)),
							["@p4"] = (entity.Name, typeof(global::System.String)),
							["@p5"] = (entity.SyncId, typeof(global::System.Guid)),
							["@p6"] = (entity.Id, typeof(global::System.Int32)),
						};
					}
				}
			}
			"""",
			"""
			// <auto-generated>
			// Auto-generated by Cornerstone.Generators
			// </auto-generated>
			namespace TestCompilation
			{
				public static partial class CornerstoneGenerated
				{
					[global::System.Runtime.CompilerServices.ModuleInitializer]
					public static void Initialize()
					{
						global::Cornerstone.Storage.Sql.SqlGenerator.RegisterCreateTableScript(typeof(global::Cornerstone.Test.Models.Account), global::Cornerstone.Storage.Sql.SqlProvider.Sqlite, CornerstoneTestModelsAccountCreateTableSqlite);
						global::Cornerstone.Storage.Sql.SqlGenerator.RegisterCreateTableScript(typeof(global::Cornerstone.Test.Models.Account), global::Cornerstone.Storage.Sql.SqlProvider.SqlServer, CornerstoneTestModelsAccountCreateTableSqlServer);
						global::Cornerstone.Storage.Sql.SqlGenerator.RegisterDeleteQuery(typeof(global::Cornerstone.Test.Models.Account), global::Cornerstone.Storage.Sql.SqlProvider.Sqlite, CornerstoneTestModelsAccountDeleteSqlite, CornerstoneTestModelsAccountGetPrimaryKey);
						global::Cornerstone.Storage.Sql.SqlGenerator.RegisterDeleteQuery(typeof(global::Cornerstone.Test.Models.Account), global::Cornerstone.Storage.Sql.SqlProvider.SqlServer, CornerstoneTestModelsAccountDeleteSqlServer, CornerstoneTestModelsAccountGetPrimaryKey);
						global::Cornerstone.Storage.Sql.SqlGenerator.RegisterInsertQuery(typeof(global::Cornerstone.Test.Models.Account), global::Cornerstone.Storage.Sql.SqlProvider.Sqlite, CornerstoneTestModelsAccountUpsertSqlite, CornerstoneTestModelsAccountGetUpsertParamsSqlite);
						global::Cornerstone.Storage.Sql.SqlGenerator.RegisterInsertQuery(typeof(global::Cornerstone.Test.Models.Account), global::Cornerstone.Storage.Sql.SqlProvider.SqlServer, CornerstoneTestModelsAccountUpsertSqlServer, CornerstoneTestModelsAccountGetUpsertParamsSqlServer);
					}
				}
			}
			"""
		};
		// Generated Code - /Expected

		ValidateSource(source, expected);
	}

	#endregion
}