#region References

using Microsoft.VisualStudio.TestTools.UnitTesting;

#endregion

namespace Cornerstone.Generators.UnitTests.SqlReflection;

[TestClass]
public class SqlReflectionTests : GeneratorUnitTest
{
	#region Methods

	[TestMethod]
	public void TypeQueries()
	{
		var source = """
					namespace Cornerstone.Test.Models;

					[SqlTable]
					public partial class Account : SyncEntity<int>
					{
						[SqlTableColumn]
						public int Age { get; set; }
						
						[SqlTableColumn]
						public string Name { get; set; }
					}
					""";

		// Generated Code - Expected
		var expected = new[]
		{
			""""
			using System;
			using System.Collections.Generic;
			// <auto-generated>
			// Auto-generated by Cornerstone.Generators
			// </auto-generated>
			internal static partial class __CornerstoneGeneratedInitializer
			{
				private static readonly string CornerstoneTestModelsAccountCreateTableSqlite =
					"""
					CREATE TABLE IF NOT EXISTS "Accounts"
					(
						"Age" INTEGER NOT NULL,
						"CreatedOn" DATE NOT NULL,
						"Id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
						"IsDeleted" INTEGER NOT NULL,
						"ModifiedOn" DATE NOT NULL,
						"Name" TEXT,
						"SyncId" TEXT NOT NULL
					);
					""";
			
				private static readonly string CornerstoneTestModelsAccountCreateTableSqlServer =
					"""
					IF NOT EXISTS (SELECT * FROM [sys].[tables] WHERE [name] = 'Accounts')
					BEGIN
						CREATE TABLE [Accounts]
						(
							"Age" INT NOT NULL,
							"CreatedOn" DATETIME2 NOT NULL,
							"Id" INT NOT NULL IDENTITY(1,1),
							"IsDeleted" BIT NOT NULL,
							"ModifiedOn" DATETIME2 NOT NULL,
							"Name" NVARCHAR(MAX),
							"SyncId" UNIQUEIDENTIFIER NOT NULL,
							CONSTRAINT PK_Accounts PRIMARY KEY CLUSTERED ([Id])
						)
					END
					""";
			
				private static readonly string CornerstoneTestModelsAccountUpsertSqlite =
					"""
					INSERT INTO "Accounts" ("Age", "CreatedOn", "IsDeleted", "ModifiedOn", "Name", "SyncId")
						VALUES (@p0, @p1, @p2, @p3, @p4, @p5)
					ON CONFLICT("Id") DO UPDATE SET
						"Age" = @p0,
						"CreatedOn" = @p1,
						"IsDeleted" = @p2,
						"ModifiedOn" = @p3,
						"Name" = @p4,
						"SyncId" = @p5
					RETURNING "Id";
					""";
			
				private static readonly string CornerstoneTestModelsAccountUpsertSqlServer =
					"""
					MERGE INTO [Accounts] AS x
					USING (VALUES (@p0, @p1, @p2, @p3, @p4, @p5))
						AS y ([Age], [CreatedOn], [IsDeleted], [ModifiedOn], [Name], [SyncId])
					ON x.[Id] = @p6
					WHEN MATCHED THEN
						UPDATE SET
							[Age] = y.[Age],
							[CreatedOn] = y.[CreatedOn],
							[IsDeleted] = y.[IsDeleted],
							[ModifiedOn] = y.[ModifiedOn],
							[Name] = y.[Name],
							[SyncId] = y.[SyncId]
						WHEN NOT MATCHED THEN
						INSERT ([Age], [CreatedOn], [IsDeleted], [ModifiedOn], [Name], [SyncId])
						VALUES (y.[Age], y.[CreatedOn], y.[IsDeleted], y.[ModifiedOn], y.[Name], y.[SyncId])
						OUTPUT inserted.[Id];
					""";
			
				private static readonly string CornerstoneTestModelsAccountDeleteSqlite =
					"""
					DELETE FROM "Accounts" WHERE "Id" = @p0;
					""";
			
				private static readonly string CornerstoneTestModelsAccountDeleteSqlServer =
					"""
					DELETE FROM [Accounts] WHERE [Id] = @p0;
					""";
			
				public static (object, global::System.Type) CornerstoneTestModelsAccountGetPrimaryKey(object obj)
				{
					var entity = (global::Cornerstone.Test.Models.Account) obj;
					return (entity.Id, typeof(global::System.Int32));
				}
				public static global::System.Collections.Generic.IDictionary<string, (object, global::System.Type)> CornerstoneTestModelsAccountGetUpsertParamsSqlite(object obj)
				{
					var entity = (global::Cornerstone.Test.Models.Account) obj;
					return new global::System.Collections.Generic.Dictionary<string, (object, global::System.Type)>
					{
						["@p0"] = (entity.Age, typeof(global::System.Int32)),
						["@p1"] = (entity.CreatedOn, typeof(global::System.DateTime)),
						["@p2"] = (entity.IsDeleted, typeof(global::System.Boolean)),
						["@p3"] = (entity.ModifiedOn, typeof(global::System.DateTime)),
						["@p4"] = (entity.Name, typeof(global::System.String)),
						["@p5"] = (entity.SyncId, typeof(global::System.Guid)),
					};
				}
				public static global::System.Collections.Generic.IDictionary<string, (object, global::System.Type)> CornerstoneTestModelsAccountGetUpsertParamsSqlServer(object obj)
				{
					var entity = (global::Cornerstone.Test.Models.Account) obj;
					return new global::System.Collections.Generic.Dictionary<string, (object, global::System.Type)>
					{
						["@p0"] = (entity.Age, typeof(global::System.Int32)),
						["@p1"] = (entity.CreatedOn, typeof(global::System.DateTime)),
						["@p2"] = (entity.IsDeleted, typeof(global::System.Boolean)),
						["@p3"] = (entity.ModifiedOn, typeof(global::System.DateTime)),
						["@p4"] = (entity.Name, typeof(global::System.String)),
						["@p5"] = (entity.SyncId, typeof(global::System.Guid)),
						["@p6"] = (entity.Id, typeof(global::System.Int32)),
					};
				}
			};
			"""",
			"""
			// <auto-generated>
			// Auto-generated by Cornerstone.Generators
			// </auto-generated>
			internal static partial class __CornerstoneGeneratedInitializer
			{
				[global::System.Runtime.CompilerServices.ModuleInitializer]
				public static void Initialize()
				{
					global::Cornerstone.Storage.Sql.SqlGenerator.RegisterCreateTableScript(typeof(global::Cornerstone.Test.Models.Account), global::Cornerstone.Storage.Sql.SqlProvider.Sqlite, CornerstoneTestModelsAccountCreateTableSqlite);
					global::Cornerstone.Storage.Sql.SqlGenerator.RegisterCreateTableScript(typeof(global::Cornerstone.Test.Models.Account), global::Cornerstone.Storage.Sql.SqlProvider.SqlServer, CornerstoneTestModelsAccountCreateTableSqlServer);
					global::Cornerstone.Storage.Sql.SqlGenerator.RegisterDeleteQuery(typeof(global::Cornerstone.Test.Models.Account), global::Cornerstone.Storage.Sql.SqlProvider.Sqlite, CornerstoneTestModelsAccountDeleteSqlite, CornerstoneTestModelsAccountGetPrimaryKey);
					global::Cornerstone.Storage.Sql.SqlGenerator.RegisterDeleteQuery(typeof(global::Cornerstone.Test.Models.Account), global::Cornerstone.Storage.Sql.SqlProvider.SqlServer, CornerstoneTestModelsAccountDeleteSqlServer, CornerstoneTestModelsAccountGetPrimaryKey);
					global::Cornerstone.Storage.Sql.SqlGenerator.RegisterInsertQuery(typeof(global::Cornerstone.Test.Models.Account), global::Cornerstone.Storage.Sql.SqlProvider.Sqlite, CornerstoneTestModelsAccountUpsertSqlite, CornerstoneTestModelsAccountGetUpsertParamsSqlite);
					global::Cornerstone.Storage.Sql.SqlGenerator.RegisterInsertQuery(typeof(global::Cornerstone.Test.Models.Account), global::Cornerstone.Storage.Sql.SqlProvider.SqlServer, CornerstoneTestModelsAccountUpsertSqlServer, CornerstoneTestModelsAccountGetUpsertParamsSqlServer);
				}
			}
			"""
		};
		// Generated Code - /Expected

		ValidateSource(source, expected);
	}

	#endregion
}