#region References

using Microsoft.VisualStudio.TestTools.UnitTesting;

#endregion

namespace Cornerstone.Generators.UnitTests.Sync;

[TestClass]
public class SyncModelTests : GeneratorUnitTest
{
	#region Methods

	[TestMethod]
	public void PackableAttribute()
	{
		var source = """
					namespace Cornerstone.Test.Models;

					[Packable(1, [nameof(Name),nameof(Age)])]
					[Packable(2, ["*"])]
					public partial class Account : SyncModel
					{
						public int Age { get; set; }
						public string Name { get; set; }
					}
					""";

		// Generated Code - Expected
		var expected = new[]
		{
			"""
			using System;
			using System.Collections.Generic;
			// <auto-generated>
			// Auto-generated by Cornerstone.Generators
			// </auto-generated>
			namespace Cornerstone.Test.Models
			{
				partial class Account
				{
					public override global::Cornerstone.Serialization.SpeedyPacket ToSpeedyPacket()
					{
						return new global::Cornerstone.Serialization.SpeedyPacket([(byte) 2, Age, CreatedOn, IsDeleted, ModifiedOn, Name, SyncId]);
					}
					public override void FromSpeedyPacket(global::Cornerstone.Serialization.SpeedyPacket values)
					{
						var version = (byte) values[0];
						if (version == 1)
						{
							Name = (System.String) values[1];
							Age = (System.Int32) values[2];
						}
						if (version == 2)
						{
							Age = (System.Int32) values[1];
							CreatedOn = (System.DateTime) values[2];
							IsDeleted = (System.Boolean) values[3];
							ModifiedOn = (System.DateTime) values[4];
							Name = (System.String) values[5];
							SyncId = (System.Guid) values[6];
						}
					}
				}
			}
			""",
			"""
			// <auto-generated>
			// Auto-generated by Cornerstone.Generators
			// </auto-generated>
			internal static partial class __CornerstoneGeneratedInitializer
			{
				[global::System.Runtime.CompilerServices.ModuleInitializer]
				public static void Initialize()
				{
				}
			}
			"""
		};
		// Generated Code - /Expected

		ValidateSource(source, expected);
	}

	#endregion
}