#region References

using Microsoft.VisualStudio.TestTools.UnitTesting;

#endregion

namespace Cornerstone.Generators.UnitTests.Sync;

[TestClass]
public class SyncModelTests : GeneratorUnitTest
{
	#region Methods

	[TestMethod]
	public void PackableAttribute()
	{
		var source = """
					namespace Cornerstone.Test.Models;

					[Packable(1, [nameof(Name),nameof(Age)])]
					[Packable(2, ["*"])]
					[Updateable(UpdateableAction.All, ["*"])]
					public partial class Account : SyncModel
					{
						public int Age { get; set; }
						public string Name { get; set; }
					}
					""";

		// Generated Code - Expected
		var expected = new[]
		{
			"""
			using System;
			using System.Collections.Generic;
			// <auto-generated>
			// Auto-generated by Cornerstone.Generators
			// </auto-generated>
			namespace Cornerstone.Test.Models
			{
				partial class Account
				{
					public override global::Cornerstone.Serialization.SpeedyPacket ToSpeedyPacket()
					{
						return new global::Cornerstone.Serialization.SpeedyPacket([(byte) 2, Age, CreatedOn, IsDeleted, ModifiedOn, Name, SyncId]);
					}
					public override void FromSpeedyPacket(global::Cornerstone.Serialization.SpeedyPacket values)
					{
						var version = (byte) values[0];
						if (version == 1)
						{
							Name = (System.String) values[1];
							Age = (System.Int32) values[2];
						}
						if (version == 2)
						{
							Age = (System.Int32) values[1];
							CreatedOn = (System.DateTime) values[2];
							IsDeleted = (System.Boolean) values[3];
							ModifiedOn = (System.DateTime) values[4];
							Name = (System.String) values[5];
							SyncId = (System.Guid) values[6];
						}
					}
					public override global::System.Collections.Generic.HashSet<string> GetDefaultIncludedProperties(global::Cornerstone.Data.UpdateableAction action)
					{
						var response = base.GetDefaultIncludedProperties(action);
						switch (action)
						{
							case global::Cornerstone.Data.UpdateableAction.SyncIncomingAdd:
							case global::Cornerstone.Data.UpdateableAction.SyncIncomingUpdate:
							case global::Cornerstone.Data.UpdateableAction.SyncOutgoing:
							case global::Cornerstone.Data.UpdateableAction.UnwrapProxyEntity:
							case global::Cornerstone.Data.UpdateableAction.Updateable:
							case global::Cornerstone.Data.UpdateableAction.PropertyChangeTracking:
							case global::Cornerstone.Data.UpdateableAction.PartialUpdate:
							{
								response.Add("Age");
								response.Add("CreatedOn");
								response.Add("IsDeleted");
								response.Add("ModifiedOn");
								response.Add("Name");
								response.Add("SyncId");
								break;
							}
						}
						return response;
					}
					
					public virtual bool UpdateWith(global::Cornerstone.Test.Models.Account update, global::Cornerstone.Data.IncludeExcludeSettings settings)
					{
						if (update == null)
						{
							return false;
						}
						TryUpdateProperty(Age, update.Age, settings.ShouldProcessProperty(nameof(Age)), x => Age = x);
						TryUpdateProperty(CreatedOn, update.CreatedOn, settings.ShouldProcessProperty(nameof(CreatedOn)), x => CreatedOn = x);
						TryUpdateProperty(IsDeleted, update.IsDeleted, settings.ShouldProcessProperty(nameof(IsDeleted)), x => IsDeleted = x);
						TryUpdateProperty(ModifiedOn, update.ModifiedOn, settings.ShouldProcessProperty(nameof(ModifiedOn)), x => ModifiedOn = x);
						TryUpdateProperty(Name, update.Name, settings.ShouldProcessProperty(nameof(Name)), x => Name = x);
						TryUpdateProperty(SyncId, update.SyncId, settings.ShouldProcessProperty(nameof(SyncId)), x => SyncId = x);
						return true;
					}
					
					public override bool UpdatePropertyWith(string propertyName, object value)
					{
						return propertyName switch
						{
							nameof(Age) => TryUpdateProperty(Age, (int)value, true, x => Age = x),
							nameof(CreatedOn) => TryUpdateProperty(CreatedOn, (global::System.DateTime)value, true, x => CreatedOn = x),
							nameof(IsDeleted) => TryUpdateProperty(IsDeleted, (bool)value, true, x => IsDeleted = x),
							nameof(ModifiedOn) => TryUpdateProperty(ModifiedOn, (global::System.DateTime)value, true, x => ModifiedOn = x),
							nameof(Name) => TryUpdateProperty(Name, (string)value, true, x => Name = x),
							nameof(SyncId) => TryUpdateProperty(SyncId, (global::System.Guid)value, true, x => SyncId = x),
							_ => base.UpdatePropertyWith(propertyName, value)
						};
					}
					
					public override bool UpdateWith(object update, global::Cornerstone.Data.IncludeExcludeSettings settings)
					{
						return update switch
						{
							global::Cornerstone.Test.Models.Account value => UpdateWith(value, settings),
							_ => base.UpdateWith(update, settings)
						};
					}
				}
			}
			""",
			"""
			// <auto-generated>
			// Auto-generated by Cornerstone.Generators
			// </auto-generated>
			namespace TestCompilation
			{
				public static partial class CornerstoneGenerated
				{
					[global::System.Runtime.CompilerServices.ModuleInitializer]
					public static void Initialize()
					{
					}
				}
			}
			"""
		};
		// Generated Code - /Expected

		ValidateSource(source, expected);
	}

	#endregion
}