#region References

using Cornerstone.Presentation.Diagnostics;
using Cornerstone.Presentation.Controls.Chrome;

#endregion

// note: this must be here due to code generated by
//		Cornerstone.Generators.Presentation.NameGenerator.InitializeComponentCodeGenerator
// ReSharper disable once CheckNamespace
namespace Cornerstone.Presentation.Controls;

/// <summary>
/// Extension methods for attaching DiagnosticTools.
/// </summary>
public static class DiagnosticToolsExtensions
{
	#region Methods

	/// <summary>
	/// Attaches DiagnosticTools to a window, to be opened with the F12 key.
	/// </summary>
	/// <param name="root"> The window to attach DiagnosticTools to. </param>
	public static void AttachDevTools(this TopLevel root)
	{
		// note: disabled auto connect from generated code
		// - Cornerstone.Generators.Presentation.NameGenerator.InitializeComponentCodeGenerator
		// - we do not want to auto connect.
		//DiagnosticTools.Attach(root, new DiagnosticToolsOptions());
	}

	/// <summary>
	/// Attaches DiagnosticTools to an Application, to be opened with the specified options.
	/// </summary>
	/// <param name="application"> The Application to attach DiagnosticTools to. </param>
	public static void AttachDevTools(this Application application)
	{
		DiagnosticTools.Attach(application, new DiagnosticToolsOptions());
	}

	/// <summary>
	/// Attaches DiagnosticTools to an Application, to be opened with the specified options.
	/// </summary>
	/// <param name="application"> The Application to attach DiagnosticTools to. </param>
	/// <param name="options"> Additional settings of DiagnosticTools. </param>
	/// <remarks>
	/// Attach DiagnosticTools should only be called after application initialization is complete.
	/// A good point is <see cref="Application.OnFrameworkInitializationCompleted" />
	/// </remarks>
	public static void AttachDevTools(this Application application, DiagnosticToolsOptions options)
	{
		DiagnosticTools.Attach(application, options);
	}

	#endregion
}