<Project Sdk="Microsoft.NET.Sdk.WebAssembly">
	<PropertyGroup>
		<TargetFramework>net10.0-browser</TargetFramework>
		<OutputType>Exe</OutputType>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	</PropertyGroup>
	<ItemGroup>
		<ProjectReference Include="..\Company.AppName\Company.AppName.csproj" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="Cornerstone.Presentation" Version="CornerstoneVersionTemplateParameter" />
	</ItemGroup>
</Project>