#region References

using NUnit.Framework;

#endregion

namespace Cornerstone.Generators.UnitTests.Updateable;

[TestFixture]
public class ClassTests : GeneratorUnitTest
{
	#region Methods

	[Test]
	public void UpdateableAction()
	{
		var source = """
					namespace Cornerstone.Test.Models;

					public partial class Account : Notifiable
					{
						[UpdateableAction(UpdateableAction.All)]
						public string Name { get; set; }

						[UpdateableAction(UpdateableAction.All)]
						public int Age { get; set; }
					}
					""";

		// Generated Code - Expected
		var expected = new[]
		{
			"""
			using System;
			using System.Collections.Generic;
			// <auto-generated>
			// Auto-generated by Cornerstone.Generators
			// </auto-generated>
			namespace Cornerstone.Test.Models
			{
				partial class Account
				{
					public override global::System.Collections.Generic.HashSet<string> GetDefaultIncludedProperties(global::Cornerstone.Data.UpdateableAction action)
					{
						var response = base.GetDefaultIncludedProperties(action);
						switch (action)
						{
							case global::Cornerstone.Data.UpdateableAction.SyncIncomingAdd:
							case global::Cornerstone.Data.UpdateableAction.SyncIncomingUpdate:
							case global::Cornerstone.Data.UpdateableAction.SyncOutgoing:
							case global::Cornerstone.Data.UpdateableAction.UnwrapProxyEntity:
							case global::Cornerstone.Data.UpdateableAction.Updateable:
							case global::Cornerstone.Data.UpdateableAction.PropertyChangeTracking:
							case global::Cornerstone.Data.UpdateableAction.PartialUpdate:
							{
								response.Add("Age");
								response.Add("Name");
								break;
							}
						}
						return response;
					}
					
					public virtual bool UpdateWith(global::Cornerstone.Test.Models.Account update, global::Cornerstone.Data.IncludeExcludeSettings settings)
					{
						if (update == null)
						{
							return false;
						}
						UpdateProperty(Age, update.Age, settings.ShouldProcessProperty(nameof(Age )), x => Age = x);
						UpdateProperty(Name, update.Name, settings.ShouldProcessProperty(nameof(Name )), x => Name = x);
						return true;
					}
					
					public override bool UpdateWith(object update, global::Cornerstone.Data.IncludeExcludeSettings settings)
					{
						return update switch
						{
							global::Cornerstone.Test.Models.Account value => UpdateWith(value, settings),
							_ => base.UpdateWith(update, settings)
						};
					}
				}
			}
			""",
			"""
			// <auto-generated>
			// Auto-generated by Cornerstone.Generators
			// </auto-generated>
			internal static partial class __CornerstoneSourceReflectorInitializer
			{
				[global::System.Runtime.CompilerServices.ModuleInitializer]
				public static void Initialize()
				{
				}
			}
			"""
		};
		// Generated Code - /Expected

		ValidateSource(source, expected);
	}

	#endregion
}