#region References

using System.Collections.Generic;
using System.Collections.Immutable;
using System.Diagnostics;
using System.Linq;
using Cornerstone.Generators.Models;
using Microsoft.CodeAnalysis;

#endregion

namespace Cornerstone.Generators;

public partial class Generator
{
	#region Methods

	public static void ProcessSourceReflection(CSharpCodeBuilder builder, SourceTypeInfo type)
	{
		if (!ShouldGenerateSourceReflector(type))
		{
			return;
		}

		//builder.IndentWriteLine("#pragma warning disable CS0612");
		//builder.IndentWriteLine("#pragma warning disable CS0618 ");
		builder.WriteAutoGeneratedComment();
		builder.WriteBlock("internal static partial class __CornerstoneSourceReflectorInitializer",
			() =>
			{
				builder.WriteBlock($"private static readonly {GlobalSourceTypeInfo} {type.FullyQualifiedSourceReflectorName} = new {GlobalSourceTypeInfo}()",
					() =>
					{
						builder.IndentWriteLine($"Accessibility = {GlobalSourceAccessibility}.{type.Accessibility},");

						AppendAttributes(builder, type.Attributes);

						if (type.BaseFullyGlobalQualifiedTypeName != null)
						{
							builder.IndentWriteLine($"BaseType = typeof({type.BaseFullyGlobalQualifiedTypeName}),");
						}

						if (type.Constructors.Count > 0)
						{
							builder.WriteBlock($"DeclaredConstructorsInitializer = static () => new {GlobalSourceConstructorInfo}[]", () =>
							{
								foreach (var constructor in type.Constructors)
								{
									WriteConstructor(builder, type, constructor);
								}
							}, ",");
						}
						else
						{
							builder.IndentWriteLine($"DeclaredConstructorsInitializer = static () => {GlobalSystemArrayEmpty}<{GlobalSourceConstructorInfo}>(),");
						}

						if (type.Fields.Count > 0)
						{
							builder.WriteBlock($"DeclaredFieldsInitializer = static () => new {GlobalSourceFieldInfo}[]", () =>
							{
								foreach (var field in type.Fields)
								{
									WriteField(builder, type, field);
								}
							}, ",");
						}
						else
						{
							builder.IndentWriteLine($"DeclaredFieldsInitializer = static () => {GlobalSystemArrayEmpty}<{GlobalSourceFieldInfo}>(),");
						}

						if (type.Interfaces.Count > 0)
						{
							builder.WriteBlock($"DeclaredInterfacesInitializer = static () => new {GlobalSourceInterfaceInfo}[]", () =>
							{
								foreach (var field in type.Interfaces)
								{
									WriteInterface(builder, type, field);
								}
							}, ",");
						}
						else
						{
							builder.IndentWriteLine($"DeclaredInterfacesInitializer = static () => {GlobalSystemArrayEmpty}<{GlobalSourceInterfaceInfo}>(),");
						}

						if (type.Methods.Count > 0)
						{
							builder.WriteBlock($"DeclaredMethodsInitializer = static () => new {GlobalSourceMethodInfo}[]", () =>
							{
								foreach (var method in type.Methods)
								{
									WriteMethod(builder, type, method);
								}
							}, ",");
						}
						else
						{
							builder.IndentWriteLine($"DeclaredMethodsInitializer = static () => {GlobalSystemArrayEmpty}<{GlobalSourceMethodInfo}>(),");
						}

						if (type.Properties.Count > 0)
						{
							builder.WriteBlock($"DeclaredPropertiesInitializer = static () => new {GlobalSourcePropertyInfo}[]", () =>
							{
								foreach (var property in type.Properties)
								{
									WriteProperty(builder, type, property);
								}
							}, ",");
						}
						else
						{
							builder.IndentWriteLine($"DeclaredPropertiesInitializer = static () => {GlobalSystemArrayEmpty}<{GlobalSourcePropertyInfo}>(),");
						}

						builder.WriteAssignment("IsEnum", type.IsEnum);
						builder.WriteAssignment("IsReadOnly", type.IsReadOnly);
						builder.WriteAssignment("IsStatic", type.IsStatic);
						builder.WriteAssignment("IsStruct", type.IsStruct);
						builder.WriteAssignment("Name", type.Name);
						builder.IndentWriteLine($"Type = typeof({ForTypeOf(type.TypeSymbol)})");
					}, ";");
			}, ";");
	}

	private static void AppendAttributes(CSharpCodeBuilder builder, List<SourceAttributeInfo> attributes)
	{
		if (attributes.Count <= 0)
		{
			builder.IndentWriteLine("Attributes = [],");
			return;
		}

		builder.WriteBlock("Attributes = new[]",
			() =>
			{
				var end = attributes.Count - 1;
				for (var index = 0; index < attributes.Count; index++)
				{
					var attribute = attributes[index];
					builder.WriteBlock($"new {GlobalSourceAttributeInfo}",
						() =>
						{
							builder.WriteAssignment(nameof(attribute.ConstructorArguments), attribute.ConstructorArguments);
							builder.WriteAssignment(nameof(attribute.FullyQualifiedName), attribute.FullyQualifiedName);
							builder.WriteAssignment(nameof(attribute.FullyGlobalQualifiedName), attribute.FullyGlobalQualifiedName);
							builder.WriteAssignment(nameof(attribute.Name), attribute.Name);
							builder.WriteAssignment(nameof(attribute.NamedArguments), attribute.NamedArguments);
							builder.WriteAssignmentRaw(nameof(attribute.Type), $"typeof({attribute.FullyGlobalQualifiedName})", lastAssignment: true);
						},
						index < end ? "," : null
					);
				}
			},
			",");
	}

	private static void AppendBindingFlags(CSharpCodeBuilder builder, Accessibility accessibility, bool isStatic)
	{
		builder.Write(isStatic
			? "global::System.Reflection.BindingFlags.DeclaredOnly | global::System.Reflection.BindingFlags.Static"
			: "global::System.Reflection.BindingFlags.DeclaredOnly | global::System.Reflection.BindingFlags.Instance"
		);

		builder.Write(accessibility == Accessibility.Public
			? " | global::System.Reflection.BindingFlags.Public"
			: " | global::System.Reflection.BindingFlags.NonPublic"
		);
	}

	private static string ForTypeOf(INamedTypeSymbol typeSymbol)
	{
		if (!typeSymbol.IsGenericType)
		{
			// Non-generic: just use standard fully qualified with global::
			return typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
		}

		var openDefinition = typeSymbol.OriginalDefinition;

		// 1. Get fully qualified name WITHOUT any generic parameters (no <T> and no <> yet)
		var formatNoGenerics = SymbolDisplayFormat.FullyQualifiedFormat
			.WithGenericsOptions(SymbolDisplayGenericsOptions.None);

		var baseName = openDefinition.ToDisplayString(formatNoGenerics);

		// 2. Append empty brackets matching the arity
		var arity = openDefinition.Arity;
		if (arity > 0)
		{
			baseName += "<" + new string(',', arity - 1) + ">";
		}

		return baseName;
	}

	/// <summary>
	/// Files should have already been source generated. This is just a module initialize to call the previously generated files.
	/// </summary>
	private void GenerateModuleInitializer(SourceProductionContext spc, ImmutableArray<SourceTypeInfo> typesToProcess)
	{
		var builder = new CSharpCodeBuilder();
		builder.WriteAutoGeneratedComment();
		builder.IndentWriteLine("internal static partial class __CornerstoneSourceReflectorInitializer");
		builder.IndentWriteLine("{");
		builder.Indent++;
		builder.IndentWriteLine("[global::System.Runtime.CompilerServices.ModuleInitializer]");
		builder.IndentWriteLine("public static void Initialize()");
		builder.IndentWriteLine("{");
		builder.Indent++;
		foreach (var typeInfo in typesToProcess)
		{
			if (!ShouldGenerateSourceReflector(typeInfo))
			{
				continue;
			}

			builder.IndentWrite($"{GlobalSourceReflector}.Add(");
			builder.Write(typeInfo.FullyQualifiedSourceReflectorName);
			builder.WriteLine(");");
		}
		builder.Indent--;
		builder.IndentWriteLine("}");
		builder.Indent--;
		builder.IndentWriteLine("}");

		var source = builder.ToString();
		Trace.WriteLine(source);
		spc.AddSource("__Cornerstone.SourceReflector.g.cs", source);
	}

	private static bool ShouldGenerateSourceReflector(SourceTypeInfo sourceTypeInfo)
	{
		return sourceTypeInfo.Attributes.Any(x => x.Name is "SourceReflectionAttribute")
			|| sourceTypeInfo.IsSourceReflectionType;
	}

	private static void WriteConstructor(CSharpCodeBuilder builder, SourceTypeInfo type, SourceConstructorInfo constructor)
	{
		builder.IndentWriteLine($"new {GlobalSourceConstructorInfo}()");
		builder.WriteBlock(() =>
		{
			builder.IndentWriteLine($"Accessibility = {GlobalSourceAccessibility}.{constructor.Accessibility},");
			builder.WriteAssignment("Name", constructor.Name);
			builder.WriteAssignment("IsStatic", constructor.IsStatic);
			builder.WriteAssignment("IsDependencyConstructor", constructor.IsDependencyConstructor);

			WriteParametersProperty(builder, "Parameters", constructor.Parameters);

			if (!type.IsGenericTypeDefinition
				&& !type.IsRefLikeType
				&& !constructor.ContainingType.IsAbstract
				&& !constructor.Parameters.Any(x => x.IsParameterTypeRefLike || x.IsParameterTypePointer)
				&& (constructor.Accessibility != Accessibility.Private)
				&& (constructor.Accessibility != Accessibility.Protected)
				&& !type.Properties.Any(x => x.IsRequired)
				&& !type.Fields.Any(x => x.IsRequired)
				&& !type.HasBaseRequiredMembers)
			{
				builder.WriteIndent();
				builder.Write($"Invoke = static (parameters) => new {type.FullyGlobalQualifiedName}(");
				WriteMethodArguments(builder, constructor.Parameters);
				builder.Write(")");
				builder.WriteLine();
			}
		}, ",");
	}

	private static void WriteField(CSharpCodeBuilder builder, SourceTypeInfo type, SourceFieldInfo member)
	{
		builder.IndentWriteLine($"new {GlobalSourceFieldInfo}()");
		builder.WriteBlock(
			() =>
			{
				builder.IndentWriteLine($"Accessibility = {GlobalSourceAccessibility}.{member.Accessibility},");

				AppendAttributes(builder, member.Attributes);

				builder.IndentWrite($"FieldInfo = typeof({ForTypeOf(type.TypeSymbol)}).GetField(\"{member.Name}\", ");
				AppendBindingFlags(builder, member.Accessibility, member.IsStatic);
				builder.WriteLine("),");

				if (member.IsConstant)
				{
					builder.IndentWrite("GetValue = static _ => ");
					builder.WriteLine(
						type.IsEnum
							? $"{type.FullyGlobalQualifiedName}.{member.Name},"
							: $"{CSharpCodeBuilder.GetConstantLiteral(member.ConstantValue)},"
					);
				}

				builder.WriteAssignment(nameof(SourceFieldInfo.IsConstant), member.IsConstant);
				builder.WriteAssignment(nameof(SourceFieldInfo.IsReadOnly), member.IsReadOnly);
				builder.WriteAssignment(nameof(SourceFieldInfo.IsRequired), member.IsRequired);
				builder.WriteAssignment(nameof(SourceFieldInfo.IsStatic), member.IsStatic);
				builder.WriteAssignment(nameof(SourceFieldInfo.Name), member.Name);
				builder.WriteAssignmentRaw(nameof(SourceFieldInfo.NullableAnnotation), $"{GlobalSourceNullableAnnotation}.{member.NullableAnnotation}", false, true);
			},
			","
		);
	}

	private static void WriteInterface(CSharpCodeBuilder builder, SourceTypeInfo type, SourceInterfaceInfo member)
	{
		builder.IndentWriteLine($"new {GlobalSourceInterfaceInfo}()");
		builder.WriteBlock(
			() =>
			{
				builder.WriteAssignment(nameof(SourceInterfaceInfo.FullyGlobalQualifiedName), member.FullyGlobalQualifiedName);
				builder.WriteAssignment(nameof(SourceInterfaceInfo.FullyQualifiedName), member.FullyQualifiedName);
				builder.WriteAssignment(nameof(SourceInterfaceInfo.Name), member.Name, lastAssignment: true);
			},
			","
		);
	}

	private static void WriteMethod(CSharpCodeBuilder builder, SourceTypeInfo type, SourceMethodInfo member)
	{
		builder.IndentWriteLine($"new {GlobalSourceMethodInfo}()");
		builder.WriteBlock(
			() =>
			{
				builder.WriteAssignment(nameof(SourceFieldInfo.Name), member.Name);
				builder.IndentWriteLine($"Accessibility = {GlobalSourceAccessibility}.{member.Accessibility},");
				builder.WriteAssignment(nameof(SourceFieldInfo.FullyQualifiedTypeName), member.FullyQualifiedTypeName);
				builder.WriteAssignment(nameof(SourceFieldInfo.IsStatic), member.IsStatic);

				if (member.IsGenericMethod)
				{
					builder.IndentWrite($"MethodInfo = {GlobalReflectionExtensions}.FindGenericMethod(typeof({ForTypeOf(type.TypeSymbol)}), \"{member.Name}\", {member.TypeParameters?.Length}, ");
					builder.WriteArrayInitializer("global::System.String", member.Parameters.Select(x => $"\"{x.DisplayType}\"").ToArray());
				}
				else
				{
					// todo: support generics
					// https://x.com/i/grok?conversation=2024292903107928350
					builder.IndentWrite($"MethodInfo = typeof({ForTypeOf(type.TypeSymbol)}).GetMethod(\"{member.Name}\", ");
					AppendBindingFlags(builder, member.Accessibility, member.IsStatic);
					builder.Write(", ");
					builder.WriteArrayInitializer("global::System.Type",
						member.Parameters
							.Select(x => $"typeof({x.ParameterType})")
							.ToArray()
					);
				}
				builder.WriteLine("),");

				AppendAttributes(builder, member.Attributes);

				if (!type.IsGenericTypeDefinition
					&& !type.IsRefLikeType
					&& member.CanInvoke()
					&& member.Parameters.All(p => !p.IsOut))
				{
					builder.IndentWrite("Invoke = static (instance, parameters) => ");

					if (member.ReturnType == "void")
					{
						builder.Write("{ ");
					}

					builder.Write(member.IsStatic
						? $"{type.FullyGlobalQualifiedName}.{member.Name}("
						: $"(({type.FullyGlobalQualifiedName}) instance).{member.Name}(");

					for (var i = 0; i < member.Parameters.Length; i++)
					{
						var parameter = member.Parameters[i];
						if (parameter.IsTypeParameter)
						{
							var typeParameter = member.TypeParameters.First(x => x.Name == parameter.ParameterType);
							builder.Write(
								typeParameter.ConstraintTypes?.Length == 0
									? $"parameters[{i}]"
									: $"({typeParameter.ConstraintTypes?[0]}) parameters[{i}]"
							);
						}
						else
						{
							builder.Write($"({parameter.ParameterType}) parameters[{i}]");
						}

						if (i < (member.Parameters.Length - 1))
						{
							builder.Write(", ");
						}
					}

					builder.Write(")");

					if (member.ReturnType == "void")
					{
						builder.Write("; return null; }");
					}

					builder.WriteLine();
				}
			},
			","
		);
	}

	private static void WriteMethodArguments(CSharpCodeBuilder builder, SourceParameterInfo[] parameters)
	{
		for (var i = 0; i < parameters.Length; i++)
		{
			var parameter = parameters[i];
			builder.Write($"({parameter.ParameterType}) parameters[{i}]");
			if (i < (parameters.Length - 1))
			{
				builder.Write(", ");
			}
		}
	}

	private static void WriteParametersProperty(CSharpCodeBuilder builder, string propertyName, SourceParameterInfo[] parameters)
	{
		if (parameters.Length == 0)
		{
			builder.IndentWriteLine($"{propertyName} = {GlobalSystemArrayEmpty}<{GlobalSourceParameterInfo}>(),");
		}
		else
		{
			builder.WriteBlock($"{propertyName} = new {GlobalSourceParameterInfo}[]", () =>
			{
				foreach (var member in parameters)
				{
					builder.WriteBlock($"new {GlobalSourceParameterInfo}()", () =>
					{
						builder.WriteAssignment("Name", member.Name);
						builder.WriteAssignment("HasDefaultValue", member.HasDefaultValue);
						builder.WriteAssignment("DefaultValue", member.DefaultValue);
						builder.WriteAssignment("IsRef", member.IsRef);
						builder.WriteAssignment("IsOut", member.IsOut);

						if (!member.HasNestedTypeParameter)
						{
							builder.IndentWriteLine($"ParameterType = typeof({member.ParameterType}),");
						}

						builder.WriteAssignmentRaw(nameof(SourceFieldInfo.NullableAnnotation), $"{GlobalSourceNullableAnnotation}.{member.NullableAnnotation}", false, true);
					}, ",");
				}
			}, ",");
		}
	}

	private static void WriteProperty(CSharpCodeBuilder builder, SourceTypeInfo type, SourcePropertyInfo member)
	{
		builder.IndentWriteLine($"new {GlobalSourcePropertyInfo}()");
		builder.WriteBlock(
			() =>
			{
				builder.IndentWriteLine($"Accessibility = {GlobalSourceAccessibility}.{member.Accessibility},");

				AppendAttributes(builder, member.Attributes);

				builder.WriteAssignment(nameof(SourcePropertyInfo.CanRead), member.CanRead);
				builder.WriteAssignment(nameof(SourcePropertyInfo.CanWrite), member.CanWrite);

				builder.WriteAssignment(nameof(SourcePropertyInfo.IsAbstract), member.IsAbstract);
				builder.WriteAssignment(nameof(SourcePropertyInfo.IsDependencyInjected), member.IsDependencyInjected);
				builder.WriteAssignment(nameof(SourcePropertyInfo.IsReadOnly), member.IsReadOnly);
				builder.WriteAssignment(nameof(SourcePropertyInfo.IsRequired), member.IsRequired);
				builder.WriteAssignment(nameof(SourcePropertyInfo.IsStatic), member.IsStatic);
				builder.WriteAssignment(nameof(SourcePropertyInfo.IsVirtual), member.IsVirtual);

				builder.IndentWrite($"PropertyInfo = typeof({ForTypeOf(type.TypeSymbol)}).GetProperty(\"{member.Name}\", ");
				AppendBindingFlags(builder, member.Accessibility, member.IsStatic);
				builder.WriteLine("),");

				builder.WriteAssignment("Name", member.Name);

				if (!type.IsGenericTypeDefinition
					&& !type.IsRefLikeType
					&& (member.Accessibility != Accessibility.Private)
					&& (member.Accessibility != Accessibility.Protected))
				{
					if (member.CanRead && member.GetMethodAccessibility is Accessibility.Public)
					{
						if (member.IsStatic)
						{
							builder.IndentWriteLine($"GetValue = static instance => {type.FullyGlobalQualifiedName}.{member.Name},");
						}
						else
						{
							if (member.IsIndexer)
							{
								builder.IndentWrite($"GetIndexerValue = static (instance, parameters) => (({type.FullyGlobalQualifiedName})instance)[");
								builder.WriteMethodArguments(builder, member.Parameters);
								builder.WriteLine("],");
							}
							else
							{
								builder.IndentWriteLine($"GetValue = static instance => (({type.FullyGlobalQualifiedName})instance).{member.Name},");
							}
						}
					}

					if (!type.IsStruct
						&& !member.IsInitOnly
						&& member.CanWrite
						&& member.SetMethodAccessibility is Accessibility.Public)
					{
						if (member.IsStatic)
						{
							builder.IndentWriteLine($"SetValue = static (instance, value) => {type.FullyGlobalQualifiedName}.{member.Name} = ({member.GlobalFullyQualifiedName}) value");
						}
						else
						{
							if (member.IsIndexer)
							{
								builder.IndentWrite($"SetIndexerValue = static (instance, value, parameters) => (({type.FullyGlobalQualifiedName})instance)[");
								builder.WriteMethodArguments(builder, member.Parameters);
								builder.WriteLine($"] = ({member.FullyQualifiedName}) value");
							}
							else
							{
								builder.IndentWriteLine($"SetValue = static (instance, value) => (({type.FullyGlobalQualifiedName}) instance).{member.Name} = ({member.FullyQualifiedName}) value");
							}
						}
					}
				}
			},
			","
		);
	}

	#endregion
}