#region References

using System.Globalization;
using Cornerstone.Storage.Sql.Data;
using Cornerstone.Text;

#endregion

namespace Cornerstone.Storage.Sql.Migrations;

/// <summary>
/// Writes a <see cref="SchemaSnapshot" /> as compilable C#.
/// </summary>
public static class SchemaSnapshotWriter
{
	#region Methods

	public static string FormatCreateColumnArguments(SqlTableColumn column)
	{
		using var rented = StringBuilderPool.Rent();
		var builder = rented.Value;
		builder.Append(Quote(column.Name));
		builder.Append(", ");
		builder.Append(Quote(column.ClrTypeName));
		builder.Append(", ");
		builder.Append(column.Order.ToString(CultureInfo.InvariantCulture));
		builder.Append(", ");
		builder.Append(ToLiteral(column.IsNullable));
		builder.Append(", ");
		builder.Append(ToLiteral(column.IsPrimaryKey));
		builder.Append(", ");
		builder.Append(ToLiteral(column.IsAutoIncrement));
		builder.Append(", ");
		builder.Append(ToLiteral(column.IsUnique));
		builder.Append(", ");
		builder.Append(column.MaxLength.ToString(CultureInfo.InvariantCulture));
		builder.Append(", ");
		builder.Append(column.DefaultValue == null ? "null" : Quote(column.DefaultValue));
		return builder.ToString();
	}

	public static string Write(SchemaSnapshot snapshot, string namespaceName, string className)
	{
		using var rented = StringBuilderPool.Rent();
		var builder = rented.Value;

		builder.AppendLine("// <auto-generated />");
		builder.AppendLine();
		builder.AppendLine("#region References");
		builder.AppendLine();
		builder.AppendLine("using Cornerstone.Storage.Sql.Data;");
		builder.AppendLine("using Cornerstone.Storage.Sql.Migrations;");
		builder.AppendLine();
		builder.AppendLine("#endregion");
		builder.AppendLine();
		builder.Append("namespace ");
		builder.Append(namespaceName);
		builder.AppendLine(";");
		builder.AppendLine();
		builder.Append("public partial class ");
		builder.Append(className);
		builder.AppendLine(" : SchemaSnapshot");
		builder.AppendLine("{");
		builder.AppendLine("	#region Constructors");
		builder.AppendLine();
		builder.Append("	public ");
		builder.Append(className);
		builder.AppendLine("()");
		builder.AppendLine("	{");

		foreach (var table in snapshot.Tables)
		{
			builder.Append("		var ");
			builder.Append(ToLocalName(table.Name));
			builder.Append(" = AddTable(");
			builder.Append(Quote(table.Name));
			builder.Append(", ");
			builder.Append(Quote(table.Schema ?? string.Empty));
			builder.AppendLine(");");

			foreach (var column in table.Columns)
			{
				builder.Append("		");
				builder.Append(ToLocalName(table.Name));
				builder.Append(".Columns.Add(CreateColumn(");
				builder.Append(FormatCreateColumnArguments(column));
				builder.AppendLine("));");
			}

			foreach (var index in table.Indexes)
			{
				var columnName = index.Columns.Count > 0 ? index.Columns[0].ColumnName : string.Empty;
				builder.Append("		");
				builder.Append(ToLocalName(table.Name));
				builder.Append(".Indexes.Add(CreateIndex(");
				builder.Append(Quote(index.Name));
				builder.Append(", ");
				builder.Append(ToLiteral(index.IsUnique));
				builder.Append(", ");
				builder.Append(Quote(columnName));
				builder.AppendLine("));");
			}

			foreach (var fk in table.ForeignKeys)
			{
				var columnName = fk.Columns.Count > 0 ? fk.Columns[0].ColumnName : string.Empty;
				builder.Append("		");
				builder.Append(ToLocalName(table.Name));
				builder.Append(".ForeignKeys.Add(CreateForeignKey(");
				builder.Append(Quote(fk.Name));
				builder.Append(", ");
				builder.Append(Quote(fk.PrincipalTable));
				builder.Append(", ");
				builder.Append(Quote(fk.PrincipalColumn));
				builder.Append(", ");
				builder.Append(Quote(columnName));
				builder.AppendLine("));");
			}

			builder.AppendLine();
		}

		builder.AppendLine("	}");
		builder.AppendLine();
		builder.AppendLine("	#endregion");
		builder.AppendLine("}");
		return builder.ToString();
	}

	private static string Quote(string value)
	{
		return "\"" + (value ?? string.Empty).Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";
	}

	private static string ToLiteral(bool value)
	{
		return value ? "true" : "false";
	}

	private static string ToLocalName(string tableName)
	{
		if (string.IsNullOrEmpty(tableName))
		{
			return "table";
		}

		var first = char.ToLowerInvariant(tableName[0]);
		return tableName.Length == 1
			? first.ToString()
			: first + tableName.Substring(1);
	}

	#endregion
}