#region References

using System;
using System.Collections.Generic;
using System.Text;
using Cornerstone.Storage.Sql.Data;
using Cornerstone.Text;

#endregion

namespace Cornerstone.Storage.Sql.Migrations;

/// <summary>
/// Emits a SqlMigration C# class from a schema diff.
/// </summary>
public static class SqlMigrationCodeGenerator
{
	#region Methods

	public static string WriteMigration(
		string namespaceName,
		string className,
		string migrationId,
		SchemaDiff diff,
		IReadOnlyDictionary<string, Type> tablesToEntityTypes)
	{
		ArgumentNullException.ThrowIfNull(diff);
		tablesToEntityTypes ??= new Dictionary<string, Type>(StringComparer.OrdinalIgnoreCase);

		using var rented = StringBuilderPool.Rent();
		var builder = rented.Value;
		builder.AppendLine("#region References");
		builder.AppendLine();
		builder.AppendLine("using Cornerstone.Storage.Sql.Migrations;");
		builder.AppendLine();
		builder.AppendLine("#endregion");
		builder.AppendLine();
		builder.Append("namespace ");
		builder.Append(namespaceName);
		builder.AppendLine(";");
		builder.AppendLine();
		builder.Append("public class ");
		builder.Append(className);
		builder.AppendLine(" : SqlMigration");
		builder.AppendLine("{");
		builder.AppendLine("	#region Properties");
		builder.AppendLine();
		builder.AppendLine("	public override string Id => \"" + migrationId + "\";");
		builder.AppendLine();
		builder.AppendLine("	#endregion");
		builder.AppendLine();
		builder.AppendLine("	#region Methods");
		builder.AppendLine();
		builder.AppendLine("	public override void Down(MigrationBuilder builder)");
		builder.AppendLine("	{");
		WriteDown(builder, diff, tablesToEntityTypes);
		builder.AppendLine("	}");
		builder.AppendLine();
		builder.AppendLine("	public override void Up(MigrationBuilder builder)");
		builder.AppendLine("	{");
		WriteUp(builder, diff, tablesToEntityTypes);
		builder.AppendLine("	}");
		builder.AppendLine();
		builder.AppendLine("	#endregion");
		builder.AppendLine("}");
		return builder.ToString();
	}

	public static string WriteRegister(
		string namespaceName,
		string databaseClassName,
		string migrationsNamespace,
		IReadOnlyList<string> migrationClassNames)
	{
		using var rented = StringBuilderPool.Rent();
		var builder = rented.Value;
		builder.AppendLine("#region References");
		builder.AppendLine();
		builder.AppendLine("using System.Collections.Generic;");
		builder.Append("using ");
		builder.Append(migrationsNamespace);
		builder.AppendLine(";");
		builder.AppendLine("using Cornerstone.Storage.Sql.Migrations;");
		builder.AppendLine();
		builder.AppendLine("#endregion");
		builder.AppendLine();
		builder.Append("namespace ");
		builder.Append(namespaceName);
		builder.AppendLine(";");
		builder.AppendLine();
		builder.Append("public partial class ");
		builder.AppendLine(databaseClassName);
		builder.AppendLine("{");
		builder.AppendLine("	#region Methods");
		builder.AppendLine();
		builder.AppendLine("	protected override IReadOnlyList<SqlMigration> GetMigrations()");
		builder.AppendLine("	{");
		builder.AppendLine("		return");
		builder.AppendLine("		[");
		foreach (var name in migrationClassNames)
		{
			builder.Append("			new ");
			builder.Append(name);
			builder.AppendLine("(),");
		}

		builder.AppendLine("		];");
		builder.AppendLine("	}");
		builder.AppendLine();
		builder.AppendLine("	#endregion");
		builder.AppendLine("}");
		return builder.ToString();
	}

	public static string WriteSnapshotSubclass(string namespaceName, string className, string baseClassName)
	{
		using var rented = StringBuilderPool.Rent();
		var builder = rented.Value;
		builder.AppendLine("// <auto-generated />");
		builder.AppendLine();
		builder.AppendLine("#region References");
		builder.AppendLine();
		builder.AppendLine("using Cornerstone.Storage.Sql.Migrations;");
		builder.AppendLine();
		builder.AppendLine("#endregion");
		builder.AppendLine();
		builder.Append("namespace ");
		builder.Append(namespaceName);
		builder.AppendLine(";");
		builder.AppendLine();
		builder.Append("public partial class ");
		builder.Append(className);
		builder.Append(" : ");
		builder.AppendLine(baseClassName);
		builder.AppendLine("{");
		builder.AppendLine("}");
		return builder.ToString();
	}

	private static string CreateColumnCall(SqlTableColumn column)
	{
		return "SchemaSnapshot.CreateColumn(" + SchemaSnapshotWriter.FormatCreateColumnArguments(column) + ")";
	}

	private static string Typeof(Type type)
	{
		return "typeof(" + type.FullName.Replace("+", ".") + ")";
	}

	private static void WriteColumn(StringBuilder builder, string tableName, ColumnChange column)
	{
		if (column.Action == ColumnAction.Add)
		{
			builder.Append("		builder.AddColumn(\"");
			builder.Append(tableName);
			builder.Append("\", ");
			builder.Append(CreateColumnCall(column.Column));
			builder.AppendLine(");");
			return;
		}

		builder.Append("		builder.DropColumn(\"");
		builder.Append(tableName);
		builder.Append("\", \"");
		builder.Append(column.Name);
		builder.AppendLine("\");");
	}

	private static void WriteCreateTable(StringBuilder builder, TableDiff table, IReadOnlyDictionary<string, Type> tablesToEntityTypes)
	{
		if (!tablesToEntityTypes.TryGetValue(table.TableName, out var entityType))
		{
			throw new InvalidOperationException(
				$"No mapped entity type for table '{table.TableName}'. Pass entity types into the scaffolder.");
		}

		builder.Append("		builder.CreateTable(");
		builder.Append(Typeof(entityType));
		builder.AppendLine(");");
	}

	private static void WriteDown(StringBuilder builder, SchemaDiff diff, IReadOnlyDictionary<string, Type> tablesToEntityTypes)
	{
		for (var i = diff.Tables.Count - 1; i >= 0; i--)
		{
			var table = diff.Tables[i];
			switch (table.Action)
			{
				case TableAction.Create:
					builder.Append("		builder.DropTable(\"");
					builder.Append(table.TableName);
					builder.AppendLine("\");");
					break;
				case TableAction.Drop:
					WriteCreateTable(builder, table, tablesToEntityTypes);
					break;
				case TableAction.Alter:
					if (table.Columns.Exists(x => x.Action == ColumnAction.Modify) || table.ForeignKeysChanged)
					{
						WriteRebuildTable(builder, table, tablesToEntityTypes);
						WriteIndexChanges(builder, table, true);
						break;
					}

					for (var c = table.Columns.Count - 1; c >= 0; c--)
					{
						WriteInverseColumn(builder, table.TableName, table.Columns[c]);
					}

					WriteIndexChanges(builder, table, true);
					break;
			}
		}
	}

	private static void WriteIndexChanges(StringBuilder builder, TableDiff table, bool inverse)
	{
		foreach (var change in table.IndexChanges)
		{
			var drop = inverse ? change.Action == ColumnAction.Add : change.Action == ColumnAction.Drop;
			if (drop)
			{
				builder.Append("		builder.DropIndex(\"");
				builder.Append(table.TableName);
				builder.Append("\", \"");
				builder.Append(change.Index.Name);
				builder.AppendLine("\");");
				continue;
			}

			builder.Append("		builder.CreateIndex(\"");
			builder.Append(table.TableName);
			builder.Append("\", SchemaSnapshot.CreateIndex(");
			builder.Append("\"").Append(change.Index.Name).Append("\", ");
			builder.Append(change.Index.IsUnique ? "true" : "false");
			builder.Append(", \"");
			builder.Append(change.Index.Columns.Count > 0 ? change.Index.Columns[0].ColumnName : string.Empty);
			builder.AppendLine("\"));");
		}
	}

	private static void WriteInverseColumn(StringBuilder builder, string tableName, ColumnChange column)
	{
		if (column.Action == ColumnAction.Add)
		{
			builder.Append("		builder.DropColumn(\"");
			builder.Append(tableName);
			builder.Append("\", \"");
			builder.Append(column.Name);
			builder.AppendLine("\");");
			return;
		}

		builder.Append("		builder.AddColumn(\"");
		builder.Append(tableName);
		builder.Append("\", ");
		builder.Append(CreateColumnCall(column.Column));
		builder.AppendLine(");");
	}

	private static void WriteRebuildTable(StringBuilder builder, TableDiff table, IReadOnlyDictionary<string, Type> tablesToEntityTypes)
	{
		if (!tablesToEntityTypes.TryGetValue(table.TableName, out var entityType))
		{
			throw new InvalidOperationException(
				$"No mapped entity type for table '{table.TableName}'. Pass entity types into the scaffolder.");
		}

		builder.Append("		builder.RebuildTable(");
		builder.Append(Typeof(entityType));
		builder.AppendLine(");");
	}

	private static void WriteUp(StringBuilder builder, SchemaDiff diff, IReadOnlyDictionary<string, Type> tablesToEntityTypes)
	{
		foreach (var table in diff.Tables)
		{
			switch (table.Action)
			{
				case TableAction.Create:
					WriteCreateTable(builder, table, tablesToEntityTypes);
					break;
				case TableAction.Drop:
					builder.Append("		builder.DropTable(\"");
					builder.Append(table.TableName);
					builder.AppendLine("\");");
					break;
				case TableAction.Alter:
					if (table.Columns.Exists(x => x.Action == ColumnAction.Modify) || table.ForeignKeysChanged)
					{
						WriteRebuildTable(builder, table, tablesToEntityTypes);
						WriteIndexChanges(builder, table, false);
						break;
					}

					foreach (var column in table.Columns)
					{
						WriteColumn(builder, table.TableName, column);
					}

					WriteIndexChanges(builder, table, false);
					break;
			}
		}
	}

	#endregion
}