#region References

using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Text;
using Cornerstone.Collections;
using Cornerstone.Convert.Converters;
using Cornerstone.Protocols.Osc;
using Cornerstone.Serialization.Json.Values;
using Cornerstone.Testing;
using Cornerstone.Text;
using Microsoft.VisualStudio.TestTools.UnitTesting;

#endregion

namespace Cornerstone.UnitTests.Convert.Converters;

[TestClass]
public class StringConverterTests : ConverterTests<StringConverter>
{
	#region Methods

	[TestMethod]
	public void Basic()
	{
		AreEqual(null, Converter.TryConvertTo(null, typeof(string), typeof(bool?), out var value) ? value : 1);
		AreEqual(true, Converter.TryConvertTo("true", typeof(string), typeof(bool), out value) ? value : 1);
		AreEqual(true, Converter.TryConvertTo("True", typeof(string), typeof(bool), out value) ? value : 1);
		AreEqual(true, Converter.TryConvertTo("TRUE", typeof(string), typeof(bool), out value) ? value : 1);
		AreEqual(false, Converter.TryConvertTo("false", typeof(string), typeof(bool), out value) ? value : 1);
		AreEqual(false, Converter.TryConvertTo("False", typeof(string), typeof(bool), out value) ? value : 1);
		AreEqual(false, Converter.TryConvertTo("FALSE", typeof(string), typeof(bool), out value) ? value : 1);
	}

	[TestMethod]
	public void CanConvert()
	{
		ValidateCanConvert();

		IsTrue(Converter.CanConvert(typeof(StringBuilder), typeof(TextBuilder)));
		IsTrue(Converter.CanConvert(typeof(StringBuilder), typeof(int)));
		IsTrue(Converter.CanConvert(typeof(TextBuilder), typeof(Guid)));
		IsTrue(Converter.CanConvert(typeof(JsonString), typeof(ShortGuid)));
		IsTrue(Converter.CanConvert(typeof(JsonString), typeof(bool)));
		IsTrue(Converter.CanConvert(typeof(JsonString), typeof(bool?)));
		IsTrue(Converter.CanConvert(typeof(string), typeof(Version)));

		IsFalse(Converter.CanConvert(typeof(DateTime), typeof(string)));
	}

	[TestMethod]
	public void GenerateScenarios()
	{
		GenerateNewScenarios($"{nameof(StringConverterTests)}.cs", EnableFileUpdates || IsDebugging);
	}

	[TestMethod]
	public void RunAllTests()
	{
		TestScenarios(GetTestScenarios());
	}

	[TestMethod]
	public void RunSingleTest()
	{
		TestScenarios(GetTestScenarios()[11]);
	}

	[SuppressMessage("ReSharper", "StringLiteralTypo")]
	[SuppressMessage("ReSharper", "RedundantCast")]
	private TestScenario[] GetTestScenarios()
	{
		var response = new List<TestScenario>();

		response.AddRange(new TestScenario[]
		{
			// <Scenarios>
			new("0: string -> string", null, typeof(string), null, typeof(string)),
			new("1: string -> StringBuilder", null, typeof(string), null, typeof(StringBuilder)),
			new("2: StringBuilder -> string", null, typeof(StringBuilder), null, typeof(string)),
			new("3: string -> TextBuilder", null, typeof(string), null, typeof(TextBuilder)),
			new("4: TextBuilder -> string", null, typeof(TextBuilder), null, typeof(string)),
			new("5: string -> GapBuffer<char>", null, typeof(string), null, typeof(GapBuffer<char>)),
			new("6: GapBuffer<char> -> string", null, typeof(GapBuffer<char>), null, typeof(string)),
			new("7: string -> RopeBuffer<char>", null, typeof(string), null, typeof(RopeBuffer<char>)),
			new("8: RopeBuffer<char> -> string", null, typeof(RopeBuffer<char>), null, typeof(string)),
			new("9: string -> JsonString", null, typeof(string), null, typeof(JsonString)),
			new("10: JsonString -> string", null, typeof(JsonString), null, typeof(string)),
			new("11: string -> char", "a", 'a'),
			new("12: string -> char?", null, typeof(string), null, typeof(char?)),
			new("13: string -> DateTime", "2000-01-02T03:04:00.0000000Z", new DateTime(2000, 1, 2, 3, 4, 0, DateTimeKind.Utc)),
			new("14: string -> DateTime?", null, typeof(string), null, typeof(DateTime?)),
			new("15: string -> DateTimeOffset", "2000-01-02T03:04:01.0000000Z", new DateTimeOffset(2000, 1, 2, 3, 4, 1, 0, 0, new TimeSpan(0, 0, 0))),
			new("16: string -> DateTimeOffset?", null, typeof(string), null, typeof(DateTimeOffset?)),
			new("17: string -> IsoDateTime", "2000-01-02T03:04:02.0000000Z", new IsoDateTime(new DateTime(2000, 1, 2, 3, 4, 2, DateTimeKind.Utc), new TimeSpan(0, 0, 0))),
			new("18: string -> IsoDateTime?", null, typeof(string), null, typeof(IsoDateTime?)),
			new("19: string -> OscTimeTag", "2000-01-02T03:04:03.0000000Z", new OscTimeTag(new DateTime(2000, 1, 2, 3, 4, 3, DateTimeKind.Utc))),
			new("20: string -> OscTimeTag?", null, typeof(string), null, typeof(OscTimeTag?)),
			new("21: string -> TimeSpan", "0:03:04:04.0000000", new TimeSpan(3, 4, 4)),
			new("22: string -> TimeSpan?", null, typeof(string), null, typeof(TimeSpan?)),
			new("23: string -> byte", "6", 6),
			new("24: string -> byte?", null, typeof(string), null, typeof(byte?)),
			new("25: string -> sbyte", "7", 7),
			new("26: string -> sbyte?", null, typeof(string), null, typeof(sbyte?)),
			new("27: string -> short", "8", 8),
			new("28: string -> short?", null, typeof(string), null, typeof(short?)),
			new("29: string -> ushort", "9", 9),
			new("30: string -> ushort?", null, typeof(string), null, typeof(ushort?)),
			new("31: string -> int", "10", 10),
			new("32: string -> int?", null, typeof(string), null, typeof(int?)),
			new("33: string -> uint", "11", 11),
			new("34: string -> uint?", null, typeof(string), null, typeof(uint?)),
			new("35: string -> long", "12", 12),
			new("36: string -> long?", null, typeof(string), null, typeof(long?)),
			new("37: string -> ulong", "13", 13),
			new("38: string -> ulong?", null, typeof(string), null, typeof(ulong?)),
			new("39: string -> IntPtr", "14", (IntPtr) 14),
			new("40: string -> IntPtr?", null, typeof(string), null, typeof(IntPtr?)),
			new("41: string -> UIntPtr", "15", (UIntPtr) 15),
			new("42: string -> UIntPtr?", null, typeof(string), null, typeof(UIntPtr?)),
			new("43: string -> Int128", "16", 16),
			new("44: string -> Int128?", null, typeof(string), null, typeof(Int128?)),
			new("45: string -> UInt128", "17", 17),
			new("46: string -> UInt128?", null, typeof(string), null, typeof(UInt128?)),
			new("47: string -> decimal", "18.01", (decimal) 18.01),
			new("48: string -> decimal?", null, typeof(string), null, typeof(decimal?)),
			new("49: string -> double", "19.02", (double) 19.02),
			new("50: string -> double?", null, typeof(string), null, typeof(double?)),
			new("51: string -> float", "20.03", (float) 20.03),
			new("52: string -> float?", null, typeof(string), null, typeof(float?)),
			new("53: string -> Guid", "00000000-0000-0000-0000-000000000021", Guid.Parse("00000000-0000-0000-0000-000000000021")),
			new("54: string -> Guid?", null, typeof(string), null, typeof(Guid?)),
			new("55: string -> ShortGuid", "00000000-0000-0000-0000-000000000022", ShortGuid.Parse("AAAAAAAAAAAAAAAAAAAAIg")),
			new("56: string -> ShortGuid?", null, typeof(string), null, typeof(ShortGuid?)),
			new("57: string -> bool", "True", true),
			new("58: string -> bool?", null, typeof(string), null, typeof(bool?)),
			new("59: string -> Version", null, typeof(string), null, typeof(Version)),
			new("60: StringBuilder -> string", null, typeof(StringBuilder), null, typeof(string)),
			new("61: string -> StringBuilder", null, typeof(string), null, typeof(StringBuilder)),
			new("62: StringBuilder -> StringBuilder", null, typeof(StringBuilder), null, typeof(StringBuilder)),
			new("63: StringBuilder -> TextBuilder", null, typeof(StringBuilder), null, typeof(TextBuilder)),
			new("64: TextBuilder -> StringBuilder", null, typeof(TextBuilder), null, typeof(StringBuilder)),
			new("65: StringBuilder -> GapBuffer<char>", null, typeof(StringBuilder), null, typeof(GapBuffer<char>)),
			new("66: GapBuffer<char> -> StringBuilder", null, typeof(GapBuffer<char>), null, typeof(StringBuilder)),
			new("67: StringBuilder -> RopeBuffer<char>", null, typeof(StringBuilder), null, typeof(RopeBuffer<char>)),
			new("68: RopeBuffer<char> -> StringBuilder", null, typeof(RopeBuffer<char>), null, typeof(StringBuilder)),
			new("69: StringBuilder -> JsonString", null, typeof(StringBuilder), null, typeof(JsonString)),
			new("70: JsonString -> StringBuilder", null, typeof(JsonString), null, typeof(StringBuilder)),
			new("71: StringBuilder -> char", new StringBuilder("w"), 'w'),
			new("72: StringBuilder -> char?", null, typeof(StringBuilder), null, typeof(char?)),
			new("73: StringBuilder -> DateTime", "2000-01-02T03:04:22.0000000Z", new DateTime(2000, 1, 2, 3, 4, 22, DateTimeKind.Utc)),
			new("74: StringBuilder -> DateTime?", null, typeof(StringBuilder), null, typeof(DateTime?)),
			new("75: StringBuilder -> DateTimeOffset", "2000-01-02T03:04:23.0000000Z", new DateTimeOffset(2000, 1, 2, 3, 4, 23, 0, 0, new TimeSpan(0, 0, 0))),
			new("76: StringBuilder -> DateTimeOffset?", null, typeof(StringBuilder), null, typeof(DateTimeOffset?)),
			new("77: StringBuilder -> IsoDateTime", "2000-01-02T03:04:24.0000000Z", new IsoDateTime(new DateTime(2000, 1, 2, 3, 4, 24, DateTimeKind.Utc), new TimeSpan(0, 0, 0))),
			new("78: StringBuilder -> IsoDateTime?", null, typeof(StringBuilder), null, typeof(IsoDateTime?)),
			new("79: StringBuilder -> OscTimeTag", "2000-01-02T03:04:25.0000000Z", new OscTimeTag(new DateTime(2000, 1, 2, 3, 4, 25, DateTimeKind.Utc))),
			new("80: StringBuilder -> OscTimeTag?", null, typeof(StringBuilder), null, typeof(OscTimeTag?)),
			new("81: StringBuilder -> TimeSpan", "0:03:04:26.0000000", new TimeSpan(3, 4, 26)),
			new("82: StringBuilder -> TimeSpan?", null, typeof(StringBuilder), null, typeof(TimeSpan?)),
			new("83: StringBuilder -> byte", new StringBuilder("28"), 28),
			new("84: StringBuilder -> byte?", null, typeof(StringBuilder), null, typeof(byte?)),
			new("85: StringBuilder -> sbyte", new StringBuilder("29"), 29),
			new("86: StringBuilder -> sbyte?", null, typeof(StringBuilder), null, typeof(sbyte?)),
			new("87: StringBuilder -> short", new StringBuilder("30"), 30),
			new("88: StringBuilder -> short?", null, typeof(StringBuilder), null, typeof(short?)),
			new("89: StringBuilder -> ushort", new StringBuilder("31"), 31),
			new("90: StringBuilder -> ushort?", null, typeof(StringBuilder), null, typeof(ushort?)),
			new("91: StringBuilder -> int", new StringBuilder("32"), 32),
			new("92: StringBuilder -> int?", null, typeof(StringBuilder), null, typeof(int?)),
			new("93: StringBuilder -> uint", new StringBuilder("33"), 33),
			new("94: StringBuilder -> uint?", null, typeof(StringBuilder), null, typeof(uint?)),
			new("95: StringBuilder -> long", new StringBuilder("34"), 34),
			new("96: StringBuilder -> long?", null, typeof(StringBuilder), null, typeof(long?)),
			new("97: StringBuilder -> ulong", new StringBuilder("35"), 35),
			new("98: StringBuilder -> ulong?", null, typeof(StringBuilder), null, typeof(ulong?)),
			new("99: StringBuilder -> IntPtr", new StringBuilder("36"), (IntPtr) 36),
			new("100: StringBuilder -> IntPtr?", null, typeof(StringBuilder), null, typeof(IntPtr?)),
			new("101: StringBuilder -> UIntPtr", new StringBuilder("37"), (UIntPtr) 37),
			new("102: StringBuilder -> UIntPtr?", null, typeof(StringBuilder), null, typeof(UIntPtr?)),
			new("103: StringBuilder -> Int128", new StringBuilder("38"), 38),
			new("104: StringBuilder -> Int128?", null, typeof(StringBuilder), null, typeof(Int128?)),
			new("105: StringBuilder -> UInt128", new StringBuilder("39"), 39),
			new("106: StringBuilder -> UInt128?", null, typeof(StringBuilder), null, typeof(UInt128?)),
			new("107: StringBuilder -> decimal", new StringBuilder("40.04"), (decimal) 40.04),
			new("108: StringBuilder -> decimal?", null, typeof(StringBuilder), null, typeof(decimal?)),
			new("109: StringBuilder -> double", new StringBuilder("41.05"), (double) 41.05),
			new("110: StringBuilder -> double?", null, typeof(StringBuilder), null, typeof(double?)),
			new("111: StringBuilder -> float", new StringBuilder("42.06"), (float) 42.06),
			new("112: StringBuilder -> float?", null, typeof(StringBuilder), null, typeof(float?)),
			new("113: StringBuilder -> Guid", new StringBuilder("00000000-0000-0000-0000-000000000043"), Guid.Parse("00000000-0000-0000-0000-000000000043")),
			new("114: StringBuilder -> Guid?", null, typeof(StringBuilder), null, typeof(Guid?)),
			new("115: StringBuilder -> ShortGuid", new StringBuilder("00000000-0000-0000-0000-000000000044"), ShortGuid.Parse("AAAAAAAAAAAAAAAAAAAARA")),
			new("116: StringBuilder -> ShortGuid?", null, typeof(StringBuilder), null, typeof(ShortGuid?)),
			new("117: StringBuilder -> bool", new StringBuilder("True"), true),
			new("118: StringBuilder -> bool?", null, typeof(StringBuilder), null, typeof(bool?)),
			new("119: StringBuilder -> Version", null, typeof(StringBuilder), null, typeof(Version)),
			new("120: TextBuilder -> string", null, typeof(TextBuilder), null, typeof(string)),
			new("121: string -> TextBuilder", null, typeof(string), null, typeof(TextBuilder)),
			new("122: TextBuilder -> StringBuilder", null, typeof(TextBuilder), null, typeof(StringBuilder)),
			new("123: StringBuilder -> TextBuilder", null, typeof(StringBuilder), null, typeof(TextBuilder)),
			new("124: TextBuilder -> TextBuilder", null, typeof(TextBuilder), null, typeof(TextBuilder)),
			new("125: TextBuilder -> GapBuffer<char>", null, typeof(TextBuilder), null, typeof(GapBuffer<char>)),
			new("126: GapBuffer<char> -> TextBuilder", null, typeof(GapBuffer<char>), null, typeof(TextBuilder)),
			new("127: TextBuilder -> RopeBuffer<char>", null, typeof(TextBuilder), null, typeof(RopeBuffer<char>)),
			new("128: RopeBuffer<char> -> TextBuilder", null, typeof(RopeBuffer<char>), null, typeof(TextBuilder)),
			new("129: TextBuilder -> JsonString", null, typeof(TextBuilder), null, typeof(JsonString)),
			new("130: JsonString -> TextBuilder", null, typeof(JsonString), null, typeof(TextBuilder)),
			new("131: TextBuilder -> char", new TextBuilder("S"), 'S'),
			new("132: TextBuilder -> char?", null, typeof(TextBuilder), null, typeof(char?)),
			new("133: TextBuilder -> DateTime", "2000-01-02T03:04:44.0000000Z", new DateTime(2000, 1, 2, 3, 4, 44, DateTimeKind.Utc)),
			new("134: TextBuilder -> DateTime?", null, typeof(TextBuilder), null, typeof(DateTime?)),
			new("135: TextBuilder -> DateTimeOffset", "2000-01-02T03:04:45.0000000Z", new DateTimeOffset(2000, 1, 2, 3, 4, 45, 0, 0, new TimeSpan(0, 0, 0))),
			new("136: TextBuilder -> DateTimeOffset?", null, typeof(TextBuilder), null, typeof(DateTimeOffset?)),
			new("137: TextBuilder -> IsoDateTime", "2000-01-02T03:04:46.0000000Z", new IsoDateTime(new DateTime(2000, 1, 2, 3, 4, 46, DateTimeKind.Utc), new TimeSpan(0, 0, 0))),
			new("138: TextBuilder -> IsoDateTime?", null, typeof(TextBuilder), null, typeof(IsoDateTime?)),
			new("139: TextBuilder -> OscTimeTag", "2000-01-02T03:04:47.0000000Z", new OscTimeTag(new DateTime(2000, 1, 2, 3, 4, 47, DateTimeKind.Utc))),
			new("140: TextBuilder -> OscTimeTag?", null, typeof(TextBuilder), null, typeof(OscTimeTag?)),
			new("141: TextBuilder -> TimeSpan", "0:03:04:48.0000000", new TimeSpan(3, 4, 48)),
			new("142: TextBuilder -> TimeSpan?", null, typeof(TextBuilder), null, typeof(TimeSpan?)),
			new("143: TextBuilder -> byte", new TextBuilder("50"), 50),
			new("144: TextBuilder -> byte?", null, typeof(TextBuilder), null, typeof(byte?)),
			new("145: TextBuilder -> sbyte", new TextBuilder("51"), 51),
			new("146: TextBuilder -> sbyte?", null, typeof(TextBuilder), null, typeof(sbyte?)),
			new("147: TextBuilder -> short", new TextBuilder("52"), 52),
			new("148: TextBuilder -> short?", null, typeof(TextBuilder), null, typeof(short?)),
			new("149: TextBuilder -> ushort", new TextBuilder("53"), 53),
			new("150: TextBuilder -> ushort?", null, typeof(TextBuilder), null, typeof(ushort?)),
			new("151: TextBuilder -> int", new TextBuilder("54"), 54),
			new("152: TextBuilder -> int?", null, typeof(TextBuilder), null, typeof(int?)),
			new("153: TextBuilder -> uint", new TextBuilder("55"), 55),
			new("154: TextBuilder -> uint?", null, typeof(TextBuilder), null, typeof(uint?)),
			new("155: TextBuilder -> long", new TextBuilder("56"), 56),
			new("156: TextBuilder -> long?", null, typeof(TextBuilder), null, typeof(long?)),
			new("157: TextBuilder -> ulong", new TextBuilder("57"), 57),
			new("158: TextBuilder -> ulong?", null, typeof(TextBuilder), null, typeof(ulong?)),
			new("159: TextBuilder -> IntPtr", new TextBuilder("58"), (IntPtr) 58),
			new("160: TextBuilder -> IntPtr?", null, typeof(TextBuilder), null, typeof(IntPtr?)),
			new("161: TextBuilder -> UIntPtr", new TextBuilder("59"), (UIntPtr) 59),
			new("162: TextBuilder -> UIntPtr?", null, typeof(TextBuilder), null, typeof(UIntPtr?)),
			new("163: TextBuilder -> Int128", new TextBuilder("60"), 60),
			new("164: TextBuilder -> Int128?", null, typeof(TextBuilder), null, typeof(Int128?)),
			new("165: TextBuilder -> UInt128", new TextBuilder("61"), 61),
			new("166: TextBuilder -> UInt128?", null, typeof(TextBuilder), null, typeof(UInt128?)),
			new("167: TextBuilder -> decimal", new TextBuilder("62.07"), (decimal) 62.07),
			new("168: TextBuilder -> decimal?", null, typeof(TextBuilder), null, typeof(decimal?)),
			new("169: TextBuilder -> double", new TextBuilder("63.08"), (double) 63.08),
			new("170: TextBuilder -> double?", null, typeof(TextBuilder), null, typeof(double?)),
			new("171: TextBuilder -> float", new TextBuilder("64.09"), (float) 64.09),
			new("172: TextBuilder -> float?", null, typeof(TextBuilder), null, typeof(float?)),
			new("173: TextBuilder -> Guid", new TextBuilder("00000000-0000-0000-0000-000000000065"), Guid.Parse("00000000-0000-0000-0000-000000000065")),
			new("174: TextBuilder -> Guid?", null, typeof(TextBuilder), null, typeof(Guid?)),
			new("175: TextBuilder -> ShortGuid", new TextBuilder("00000000-0000-0000-0000-000000000066"), ShortGuid.Parse("AAAAAAAAAAAAAAAAAAAAZg")),
			new("176: TextBuilder -> ShortGuid?", null, typeof(TextBuilder), null, typeof(ShortGuid?)),
			new("177: TextBuilder -> bool", new TextBuilder("True"), true),
			new("178: TextBuilder -> bool?", null, typeof(TextBuilder), null, typeof(bool?)),
			new("179: TextBuilder -> Version", null, typeof(TextBuilder), null, typeof(Version)),
			new("180: GapBuffer<char> -> string", null, typeof(GapBuffer<char>), null, typeof(string)),
			new("181: string -> GapBuffer<char>", null, typeof(string), null, typeof(GapBuffer<char>)),
			new("182: GapBuffer<char> -> StringBuilder", null, typeof(GapBuffer<char>), null, typeof(StringBuilder)),
			new("183: StringBuilder -> GapBuffer<char>", null, typeof(StringBuilder), null, typeof(GapBuffer<char>)),
			new("184: GapBuffer<char> -> TextBuilder", null, typeof(GapBuffer<char>), null, typeof(TextBuilder)),
			new("185: TextBuilder -> GapBuffer<char>", null, typeof(TextBuilder), null, typeof(GapBuffer<char>)),
			new("186: GapBuffer<char> -> GapBuffer<char>", null, typeof(GapBuffer<char>), null, typeof(GapBuffer<char>)),
			new("187: GapBuffer<char> -> RopeBuffer<char>", null, typeof(GapBuffer<char>), null, typeof(RopeBuffer<char>)),
			new("188: RopeBuffer<char> -> GapBuffer<char>", null, typeof(RopeBuffer<char>), null, typeof(GapBuffer<char>)),
			new("189: GapBuffer<char> -> JsonString", null, typeof(GapBuffer<char>), null, typeof(JsonString)),
			new("190: JsonString -> GapBuffer<char>", null, typeof(JsonString), null, typeof(GapBuffer<char>)),
			new("191: GapBuffer<char> -> char", new GapBuffer<char>("%"), '%'),
			new("192: GapBuffer<char> -> char?", null, typeof(GapBuffer<char>), null, typeof(char?)),
			new("193: GapBuffer<char> -> DateTime", "2000-01-02T03:05:06.0000000Z", new DateTime(2000, 1, 2, 3, 5, 6, DateTimeKind.Utc)),
			new("194: GapBuffer<char> -> DateTime?", null, typeof(GapBuffer<char>), null, typeof(DateTime?)),
			new("195: GapBuffer<char> -> DateTimeOffset", "2000-01-02T03:05:07.0000000Z", new DateTimeOffset(2000, 1, 2, 3, 5, 7, 0, 0, new TimeSpan(0, 0, 0))),
			new("196: GapBuffer<char> -> DateTimeOffset?", null, typeof(GapBuffer<char>), null, typeof(DateTimeOffset?)),
			new("197: GapBuffer<char> -> IsoDateTime", "2000-01-02T03:05:08.0000000Z", new IsoDateTime(new DateTime(2000, 1, 2, 3, 5, 8, DateTimeKind.Utc), new TimeSpan(0, 0, 0))),
			new("198: GapBuffer<char> -> IsoDateTime?", null, typeof(GapBuffer<char>), null, typeof(IsoDateTime?)),
			new("199: GapBuffer<char> -> OscTimeTag", "2000-01-02T03:05:09.0000000Z", new OscTimeTag(new DateTime(2000, 1, 2, 3, 5, 9, DateTimeKind.Utc))),
			new("200: GapBuffer<char> -> OscTimeTag?", null, typeof(GapBuffer<char>), null, typeof(OscTimeTag?)),
			new("201: GapBuffer<char> -> TimeSpan", "0:03:05:10.0000000", new TimeSpan(3, 5, 10)),
			new("202: GapBuffer<char> -> TimeSpan?", null, typeof(GapBuffer<char>), null, typeof(TimeSpan?)),
			new("203: GapBuffer<char> -> byte", new GapBuffer<char>("72"), 72),
			new("204: GapBuffer<char> -> byte?", null, typeof(GapBuffer<char>), null, typeof(byte?)),
			new("205: GapBuffer<char> -> sbyte", new GapBuffer<char>("73"), 73),
			new("206: GapBuffer<char> -> sbyte?", null, typeof(GapBuffer<char>), null, typeof(sbyte?)),
			new("207: GapBuffer<char> -> short", new GapBuffer<char>("74"), 74),
			new("208: GapBuffer<char> -> short?", null, typeof(GapBuffer<char>), null, typeof(short?)),
			new("209: GapBuffer<char> -> ushort", new GapBuffer<char>("75"), 75),
			new("210: GapBuffer<char> -> ushort?", null, typeof(GapBuffer<char>), null, typeof(ushort?)),
			new("211: GapBuffer<char> -> int", new GapBuffer<char>("76"), 76),
			new("212: GapBuffer<char> -> int?", null, typeof(GapBuffer<char>), null, typeof(int?)),
			new("213: GapBuffer<char> -> uint", new GapBuffer<char>("77"), 77),
			new("214: GapBuffer<char> -> uint?", null, typeof(GapBuffer<char>), null, typeof(uint?)),
			new("215: GapBuffer<char> -> long", new GapBuffer<char>("78"), 78),
			new("216: GapBuffer<char> -> long?", null, typeof(GapBuffer<char>), null, typeof(long?)),
			new("217: GapBuffer<char> -> ulong", new GapBuffer<char>("79"), 79),
			new("218: GapBuffer<char> -> ulong?", null, typeof(GapBuffer<char>), null, typeof(ulong?)),
			new("219: GapBuffer<char> -> IntPtr", new GapBuffer<char>("80"), (IntPtr) 80),
			new("220: GapBuffer<char> -> IntPtr?", null, typeof(GapBuffer<char>), null, typeof(IntPtr?)),
			new("221: GapBuffer<char> -> UIntPtr", new GapBuffer<char>("81"), (UIntPtr) 81),
			new("222: GapBuffer<char> -> UIntPtr?", null, typeof(GapBuffer<char>), null, typeof(UIntPtr?)),
			new("223: GapBuffer<char> -> Int128", new GapBuffer<char>("82"), 82),
			new("224: GapBuffer<char> -> Int128?", null, typeof(GapBuffer<char>), null, typeof(Int128?)),
			new("225: GapBuffer<char> -> UInt128", new GapBuffer<char>("83"), 83),
			new("226: GapBuffer<char> -> UInt128?", null, typeof(GapBuffer<char>), null, typeof(UInt128?)),
			new("227: GapBuffer<char> -> decimal", new GapBuffer<char>("84.10"), (decimal) 84.10),
			new("228: GapBuffer<char> -> decimal?", null, typeof(GapBuffer<char>), null, typeof(decimal?)),
			new("229: GapBuffer<char> -> double", new GapBuffer<char>("85.11"), (double) 85.11),
			new("230: GapBuffer<char> -> double?", null, typeof(GapBuffer<char>), null, typeof(double?)),
			new("231: GapBuffer<char> -> float", new GapBuffer<char>("86.12"), (float) 86.12),
			new("232: GapBuffer<char> -> float?", null, typeof(GapBuffer<char>), null, typeof(float?)),
			new("233: GapBuffer<char> -> Guid", new GapBuffer<char>("00000000-0000-0000-0000-000000000087"), Guid.Parse("00000000-0000-0000-0000-000000000087")),
			new("234: GapBuffer<char> -> Guid?", null, typeof(GapBuffer<char>), null, typeof(Guid?)),
			new("235: GapBuffer<char> -> ShortGuid", new GapBuffer<char>("00000000-0000-0000-0000-000000000088"), ShortGuid.Parse("AAAAAAAAAAAAAAAAAAAAiA")),
			new("236: GapBuffer<char> -> ShortGuid?", null, typeof(GapBuffer<char>), null, typeof(ShortGuid?)),
			new("237: GapBuffer<char> -> bool", new GapBuffer<char>("True"), true),
			new("238: GapBuffer<char> -> bool?", null, typeof(GapBuffer<char>), null, typeof(bool?)),
			new("239: GapBuffer<char> -> Version", null, typeof(GapBuffer<char>), null, typeof(Version)),
			new("240: RopeBuffer<char> -> string", null, typeof(RopeBuffer<char>), null, typeof(string)),
			new("241: string -> RopeBuffer<char>", null, typeof(string), null, typeof(RopeBuffer<char>)),
			new("242: RopeBuffer<char> -> StringBuilder", null, typeof(RopeBuffer<char>), null, typeof(StringBuilder)),
			new("243: StringBuilder -> RopeBuffer<char>", null, typeof(StringBuilder), null, typeof(RopeBuffer<char>)),
			new("244: RopeBuffer<char> -> TextBuilder", null, typeof(RopeBuffer<char>), null, typeof(TextBuilder)),
			new("245: TextBuilder -> RopeBuffer<char>", null, typeof(TextBuilder), null, typeof(RopeBuffer<char>)),
			new("246: RopeBuffer<char> -> GapBuffer<char>", null, typeof(RopeBuffer<char>), null, typeof(GapBuffer<char>)),
			new("247: GapBuffer<char> -> RopeBuffer<char>", null, typeof(GapBuffer<char>), null, typeof(RopeBuffer<char>)),
			new("248: RopeBuffer<char> -> RopeBuffer<char>", null, typeof(RopeBuffer<char>), null, typeof(RopeBuffer<char>)),
			new("249: RopeBuffer<char> -> JsonString", null, typeof(RopeBuffer<char>), null, typeof(JsonString)),
			new("250: JsonString -> RopeBuffer<char>", null, typeof(JsonString), null, typeof(RopeBuffer<char>)),
			new("251: RopeBuffer<char> -> char", new RopeBuffer<char>("`"), '`'),
			new("252: RopeBuffer<char> -> char?", null, typeof(RopeBuffer<char>), null, typeof(char?)),
			new("253: RopeBuffer<char> -> DateTime", "2000-01-02T03:05:28.0000000Z", new DateTime(2000, 1, 2, 3, 5, 28, DateTimeKind.Utc)),
			new("254: RopeBuffer<char> -> DateTime?", null, typeof(RopeBuffer<char>), null, typeof(DateTime?)),
			new("255: RopeBuffer<char> -> DateTimeOffset", "2000-01-02T03:05:29.0000000Z", new DateTimeOffset(2000, 1, 2, 3, 5, 29, 0, 0, new TimeSpan(0, 0, 0))),
			new("256: RopeBuffer<char> -> DateTimeOffset?", null, typeof(RopeBuffer<char>), null, typeof(DateTimeOffset?)),
			new("257: RopeBuffer<char> -> IsoDateTime", "2000-01-02T03:05:30.0000000Z", new IsoDateTime(new DateTime(2000, 1, 2, 3, 5, 30, DateTimeKind.Utc), new TimeSpan(0, 0, 0))),
			new("258: RopeBuffer<char> -> IsoDateTime?", null, typeof(RopeBuffer<char>), null, typeof(IsoDateTime?)),
			new("259: RopeBuffer<char> -> OscTimeTag", "2000-01-02T03:05:31.0000000Z", new OscTimeTag(new DateTime(2000, 1, 2, 3, 5, 31, DateTimeKind.Utc))),
			new("260: RopeBuffer<char> -> OscTimeTag?", null, typeof(RopeBuffer<char>), null, typeof(OscTimeTag?)),
			new("261: RopeBuffer<char> -> TimeSpan", "0:03:05:32.0000000", new TimeSpan(3, 5, 32)),
			new("262: RopeBuffer<char> -> TimeSpan?", null, typeof(RopeBuffer<char>), null, typeof(TimeSpan?)),
			new("263: RopeBuffer<char> -> byte", new RopeBuffer<char>("94"), 94),
			new("264: RopeBuffer<char> -> byte?", null, typeof(RopeBuffer<char>), null, typeof(byte?)),
			new("265: RopeBuffer<char> -> sbyte", new RopeBuffer<char>("95"), 95),
			new("266: RopeBuffer<char> -> sbyte?", null, typeof(RopeBuffer<char>), null, typeof(sbyte?)),
			new("267: RopeBuffer<char> -> short", new RopeBuffer<char>("96"), 96),
			new("268: RopeBuffer<char> -> short?", null, typeof(RopeBuffer<char>), null, typeof(short?)),
			new("269: RopeBuffer<char> -> ushort", new RopeBuffer<char>("97"), 97),
			new("270: RopeBuffer<char> -> ushort?", null, typeof(RopeBuffer<char>), null, typeof(ushort?)),
			new("271: RopeBuffer<char> -> int", new RopeBuffer<char>("98"), 98),
			new("272: RopeBuffer<char> -> int?", null, typeof(RopeBuffer<char>), null, typeof(int?)),
			new("273: RopeBuffer<char> -> uint", new RopeBuffer<char>("99"), 99),
			new("274: RopeBuffer<char> -> uint?", null, typeof(RopeBuffer<char>), null, typeof(uint?)),
			new("275: RopeBuffer<char> -> long", new RopeBuffer<char>("100"), 100),
			new("276: RopeBuffer<char> -> long?", null, typeof(RopeBuffer<char>), null, typeof(long?)),
			new("277: RopeBuffer<char> -> ulong", new RopeBuffer<char>("101"), 101),
			new("278: RopeBuffer<char> -> ulong?", null, typeof(RopeBuffer<char>), null, typeof(ulong?)),
			new("279: RopeBuffer<char> -> IntPtr", new RopeBuffer<char>("102"), (IntPtr) 102),
			new("280: RopeBuffer<char> -> IntPtr?", null, typeof(RopeBuffer<char>), null, typeof(IntPtr?)),
			new("281: RopeBuffer<char> -> UIntPtr", new RopeBuffer<char>("103"), (UIntPtr) 103),
			new("282: RopeBuffer<char> -> UIntPtr?", null, typeof(RopeBuffer<char>), null, typeof(UIntPtr?)),
			new("283: RopeBuffer<char> -> Int128", new RopeBuffer<char>("104"), 104),
			new("284: RopeBuffer<char> -> Int128?", null, typeof(RopeBuffer<char>), null, typeof(Int128?)),
			new("285: RopeBuffer<char> -> UInt128", new RopeBuffer<char>("105"), 105),
			new("286: RopeBuffer<char> -> UInt128?", null, typeof(RopeBuffer<char>), null, typeof(UInt128?)),
			new("287: RopeBuffer<char> -> decimal", new RopeBuffer<char>("106.13"), (decimal) 106.13),
			new("288: RopeBuffer<char> -> decimal?", null, typeof(RopeBuffer<char>), null, typeof(decimal?)),
			new("289: RopeBuffer<char> -> double", new RopeBuffer<char>("107.14"), (double) 107.14),
			new("290: RopeBuffer<char> -> double?", null, typeof(RopeBuffer<char>), null, typeof(double?)),
			new("291: RopeBuffer<char> -> float", new RopeBuffer<char>("108.15"), (float) 108.15),
			new("292: RopeBuffer<char> -> float?", null, typeof(RopeBuffer<char>), null, typeof(float?)),
			new("293: RopeBuffer<char> -> Guid", new RopeBuffer<char>("00000000-0000-0000-0000-000000000109"), Guid.Parse("00000000-0000-0000-0000-000000000109")),
			new("294: RopeBuffer<char> -> Guid?", null, typeof(RopeBuffer<char>), null, typeof(Guid?)),
			new("295: RopeBuffer<char> -> ShortGuid", new RopeBuffer<char>("00000000-0000-0000-0000-000000000110"), ShortGuid.Parse("AAAAAAAAAAAAAAAAAAABEA")),
			new("296: RopeBuffer<char> -> ShortGuid?", null, typeof(RopeBuffer<char>), null, typeof(ShortGuid?)),
			new("297: RopeBuffer<char> -> bool", new RopeBuffer<char>("True"), true),
			new("298: RopeBuffer<char> -> bool?", null, typeof(RopeBuffer<char>), null, typeof(bool?)),
			new("299: RopeBuffer<char> -> Version", null, typeof(RopeBuffer<char>), null, typeof(Version)),
			new("300: JsonString -> string", null, typeof(JsonString), null, typeof(string)),
			new("301: string -> JsonString", null, typeof(string), null, typeof(JsonString)),
			new("302: JsonString -> StringBuilder", null, typeof(JsonString), null, typeof(StringBuilder)),
			new("303: StringBuilder -> JsonString", null, typeof(StringBuilder), null, typeof(JsonString)),
			new("304: JsonString -> TextBuilder", null, typeof(JsonString), null, typeof(TextBuilder)),
			new("305: TextBuilder -> JsonString", null, typeof(TextBuilder), null, typeof(JsonString)),
			new("306: JsonString -> GapBuffer<char>", null, typeof(JsonString), null, typeof(GapBuffer<char>)),
			new("307: GapBuffer<char> -> JsonString", null, typeof(GapBuffer<char>), null, typeof(JsonString)),
			new("308: JsonString -> RopeBuffer<char>", null, typeof(JsonString), null, typeof(RopeBuffer<char>)),
			new("309: RopeBuffer<char> -> JsonString", null, typeof(RopeBuffer<char>), null, typeof(JsonString)),
			new("310: JsonString -> JsonString", null, typeof(JsonString), null, typeof(JsonString)),
			new("311: JsonString -> char", new JsonString("n"), 'n'),
			new("312: JsonString -> char?", null, typeof(JsonString), null, typeof(char?)),
			new("313: JsonString -> DateTime", "2000-01-02T03:05:50.0000000Z", new DateTime(2000, 1, 2, 3, 5, 50, DateTimeKind.Utc)),
			new("314: JsonString -> DateTime?", null, typeof(JsonString), null, typeof(DateTime?)),
			new("315: JsonString -> DateTimeOffset", "2000-01-02T03:05:51.0000000Z", new DateTimeOffset(2000, 1, 2, 3, 5, 51, 0, 0, new TimeSpan(0, 0, 0))),
			new("316: JsonString -> DateTimeOffset?", null, typeof(JsonString), null, typeof(DateTimeOffset?)),
			new("317: JsonString -> IsoDateTime", "2000-01-02T03:05:52.0000000Z", new IsoDateTime(new DateTime(2000, 1, 2, 3, 5, 52, DateTimeKind.Utc), new TimeSpan(0, 0, 0))),
			new("318: JsonString -> IsoDateTime?", null, typeof(JsonString), null, typeof(IsoDateTime?)),
			new("319: JsonString -> OscTimeTag", "2000-01-02T03:05:53.0000000Z", new OscTimeTag(new DateTime(2000, 1, 2, 3, 5, 53, DateTimeKind.Utc))),
			new("320: JsonString -> OscTimeTag?", null, typeof(JsonString), null, typeof(OscTimeTag?)),
			new("321: JsonString -> TimeSpan", "0:03:05:54.0000000", new TimeSpan(3, 5, 54)),
			new("322: JsonString -> TimeSpan?", null, typeof(JsonString), null, typeof(TimeSpan?)),
			new("323: JsonString -> byte", new JsonString("116"), 116),
			new("324: JsonString -> byte?", null, typeof(JsonString), null, typeof(byte?)),
			new("325: JsonString -> sbyte", new JsonString("117"), 117),
			new("326: JsonString -> sbyte?", null, typeof(JsonString), null, typeof(sbyte?)),
			new("327: JsonString -> short", new JsonString("118"), 118),
			new("328: JsonString -> short?", null, typeof(JsonString), null, typeof(short?)),
			new("329: JsonString -> ushort", new JsonString("119"), 119),
			new("330: JsonString -> ushort?", null, typeof(JsonString), null, typeof(ushort?)),
			new("331: JsonString -> int", new JsonString("120"), 120),
			new("332: JsonString -> int?", null, typeof(JsonString), null, typeof(int?)),
			new("333: JsonString -> uint", new JsonString("121"), 121),
			new("334: JsonString -> uint?", null, typeof(JsonString), null, typeof(uint?)),
			new("335: JsonString -> long", new JsonString("122"), 122),
			new("336: JsonString -> long?", null, typeof(JsonString), null, typeof(long?)),
			new("337: JsonString -> ulong", new JsonString("123"), 123),
			new("338: JsonString -> ulong?", null, typeof(JsonString), null, typeof(ulong?)),
			new("339: JsonString -> IntPtr", new JsonString("124"), (IntPtr) 124),
			new("340: JsonString -> IntPtr?", null, typeof(JsonString), null, typeof(IntPtr?)),
			new("341: JsonString -> UIntPtr", new JsonString("125"), (UIntPtr) 125),
			new("342: JsonString -> UIntPtr?", null, typeof(JsonString), null, typeof(UIntPtr?)),
			new("343: JsonString -> Int128", new JsonString("126"), 126),
			new("344: JsonString -> Int128?", null, typeof(JsonString), null, typeof(Int128?)),
			new("345: JsonString -> UInt128", new JsonString("127"), 127),
			new("346: JsonString -> UInt128?", null, typeof(JsonString), null, typeof(UInt128?)),
			new("347: JsonString -> decimal", new JsonString("2.01"), (decimal) 2.01),
			new("348: JsonString -> decimal?", null, typeof(JsonString), null, typeof(decimal?)),
			new("349: JsonString -> double", new JsonString("3.02"), (double) 3.02),
			new("350: JsonString -> double?", null, typeof(JsonString), null, typeof(double?)),
			new("351: JsonString -> float", new JsonString("4.03"), (float) 4.03),
			new("352: JsonString -> float?", null, typeof(JsonString), null, typeof(float?)),
			new("353: JsonString -> Guid", new JsonString("00000000-0000-0000-0000-000000000005"), Guid.Parse("00000000-0000-0000-0000-000000000005")),
			new("354: JsonString -> Guid?", null, typeof(JsonString), null, typeof(Guid?)),
			new("355: JsonString -> ShortGuid", new JsonString("00000000-0000-0000-0000-000000000006"), ShortGuid.Parse("AAAAAAAAAAAAAAAAAAAABg")),
			new("356: JsonString -> ShortGuid?", null, typeof(JsonString), null, typeof(ShortGuid?)),
			new("357: JsonString -> bool", new JsonString("True"), true),
			new("358: JsonString -> bool?", null, typeof(JsonString), null, typeof(bool?)),
			new("359: JsonString -> Version", null, typeof(JsonString), null, typeof(Version)),
			#if (!NET48)
			new("360: string -> DateOnly", "2000-01-02", new DateOnly(2000, 1, 2)),
			new("361: string -> DateOnly?", null, typeof(string), null, typeof(DateOnly?)),
			new("362: string -> TimeOnly", "03:04:07.0000000", TimeOnly.Parse("03:04:07.0000000")),
			new("363: string -> TimeOnly?", null, typeof(string), null, typeof(TimeOnly?)),
			new("364: StringBuilder -> DateOnly", "2000-01-02", new DateOnly(2000, 1, 2)),
			new("365: StringBuilder -> DateOnly?", null, typeof(StringBuilder), null, typeof(DateOnly?)),
			new("366: StringBuilder -> TimeOnly", "03:04:09.0000000", TimeOnly.Parse("03:04:09.0000000")),
			new("367: StringBuilder -> TimeOnly?", null, typeof(StringBuilder), null, typeof(TimeOnly?)),
			new("368: TextBuilder -> DateOnly", "2000-01-02", new DateOnly(2000, 1, 2)),
			new("369: TextBuilder -> DateOnly?", null, typeof(TextBuilder), null, typeof(DateOnly?)),
			new("370: TextBuilder -> TimeOnly", "03:04:11.0000000", TimeOnly.Parse("03:04:11.0000000")),
			new("371: TextBuilder -> TimeOnly?", null, typeof(TextBuilder), null, typeof(TimeOnly?)),
			new("372: GapBuffer<char> -> DateOnly", "2000-01-02", new DateOnly(2000, 1, 2)),
			new("373: GapBuffer<char> -> DateOnly?", null, typeof(GapBuffer<char>), null, typeof(DateOnly?)),
			new("374: GapBuffer<char> -> TimeOnly", "03:04:13.0000000", TimeOnly.Parse("03:04:13.0000000")),
			new("375: GapBuffer<char> -> TimeOnly?", null, typeof(GapBuffer<char>), null, typeof(TimeOnly?)),
			new("376: RopeBuffer<char> -> DateOnly", "2000-01-02", new DateOnly(2000, 1, 2)),
			new("377: RopeBuffer<char> -> DateOnly?", null, typeof(RopeBuffer<char>), null, typeof(DateOnly?)),
			new("378: RopeBuffer<char> -> TimeOnly", "03:04:15.0000000", TimeOnly.Parse("03:04:15.0000000")),
			new("379: RopeBuffer<char> -> TimeOnly?", null, typeof(RopeBuffer<char>), null, typeof(TimeOnly?)),
			new("380: JsonString -> DateOnly", "2000-01-02", new DateOnly(2000, 1, 2)),
			new("381: JsonString -> DateOnly?", null, typeof(JsonString), null, typeof(DateOnly?)),
			new("382: JsonString -> TimeOnly", "03:04:17.0000000", TimeOnly.Parse("03:04:17.0000000")),
			new("383: JsonString -> TimeOnly?", null, typeof(JsonString), null, typeof(TimeOnly?)),
			#endif
			// </Scenarios>
		});

		return response.ToArray();
	}

	#endregion
}