#region References

using Microsoft.VisualStudio.TestTools.UnitTesting;

#endregion

namespace Cornerstone.Generators.UnitTests.PropertyChange;

[TestClass]
public class PropertyChangeTests : GeneratorUnitTest
{
	#region Methods

	[TestMethod]
	public void NotifiableAttribute()
	{
		var source = """
					namespace Cornerstone.Test.Models;

					[Notifiable([nameof(Name)])]
					public partial class SampleRecord : Notifiable
					{
						public partial string Name { get; set; }
					}
					""";

		// Generated Code - Expected
		var expected = new[]
		{
			"""
			using System;
			using System.Collections.Generic;
			// <auto-generated>
			// Auto-generated by Cornerstone.Generators
			// </auto-generated>
			namespace Cornerstone.Test.Models
			{
				partial class SampleRecord
				{
					private global::System.String _name;
					public partial global::System.String Name
					{
						get => _name;
						set
						{
							if (!global::System.Collections.Generic.EqualityComparer<global::System.String>.Default.Equals(value, _name))
							{
								OnPropertyChanging("Name");
								_name = value;
								OnPropertyChanged("Name");
							}
						}
					}
				}
			}
			""",
			"""
			// <auto-generated>
			// Auto-generated by Cornerstone.Generators
			// </auto-generated>
			internal static partial class __CornerstoneGeneratedInitializer
			{
				[global::System.Runtime.CompilerServices.ModuleInitializer]
				public static void Initialize()
				{
				}
			}
			"""
		};

		// Generated Code - /Expected

		ValidateSource(source, expected);
	}

	[TestMethod]
	public void NotifiableAttributeWithWildcard()
	{
		var source = """
					namespace Cornerstone.Test.Models;

					[Notifiable(["*"])]
					public partial class SampleRecord : Notifiable
					{
						public partial string Name { get; set; }
						public partial string EmailAddress { get; set; }
					}
					""";

		// Generated Code - Expected
		var expected = new[]
		{
			"""
			using System;
			using System.Collections.Generic;
			// <auto-generated>
			// Auto-generated by Cornerstone.Generators
			// </auto-generated>
			namespace Cornerstone.Test.Models
			{
				partial class SampleRecord
				{
					private global::System.String _name;
					public partial global::System.String Name
					{
						get => _name;
						set
						{
							if (!global::System.Collections.Generic.EqualityComparer<global::System.String>.Default.Equals(value, _name))
							{
								OnPropertyChanging("Name");
								_name = value;
								OnPropertyChanged("Name");
							}
						}
					}
					private global::System.String _emailAddress;
					public partial global::System.String EmailAddress
					{
						get => _emailAddress;
						set
						{
							if (!global::System.Collections.Generic.EqualityComparer<global::System.String>.Default.Equals(value, _emailAddress))
							{
								OnPropertyChanging("EmailAddress");
								_emailAddress = value;
								OnPropertyChanged("EmailAddress");
							}
						}
					}
				}
			}
			""",
			"""
			// <auto-generated>
			// Auto-generated by Cornerstone.Generators
			// </auto-generated>
			internal static partial class __CornerstoneGeneratedInitializer
			{
				[global::System.Runtime.CompilerServices.ModuleInitializer]
				public static void Initialize()
				{
				}
			}
			"""
		};

		// Generated Code - /Expected

		ValidateSource(source, expected);
	}

	[TestMethod]
	public void NotifyAttributeWithoutPartial()
	{
		var source = """
					namespace Cornerstone.Test.Models;

					public partial class SampleRecord : Notifiable
					{
						[Notify]
						public string Value { get; set; }
					}
					""";

		// Generated Code - Expected
		var expected = new[]
		{
			"Error CSG002: Type \'SampleRecord.Value\' Property must be partial in order for Cornerstone.Generators to generate the property.",
			"Error CS9249: Partial property \'SampleRecord.Value\' must have a definition part.",
			"Error CS0102: The type \'SampleRecord\' already contains a definition for \'Value\'"
		};
		// Generated Code - /Expected

		ExpectErrors(source, expected);
	}

	[TestMethod]
	public void NotifyAttribute()
	{
		var source = """
					namespace Cornerstone.Test.Models;

					public partial class SampleRecord : Notifiable
					{
						[Notify]
						public partial string Name { get; set; }
					}
					""";

		// Generated Code - Expected
		var expected = new[]
		{
			"""
			using System;
			using System.Collections.Generic;
			// <auto-generated>
			// Auto-generated by Cornerstone.Generators
			// </auto-generated>
			namespace Cornerstone.Test.Models
			{
				partial class SampleRecord
				{
					private global::System.String _name;
					public partial global::System.String Name
					{
						get => _name;
						set
						{
							if (!global::System.Collections.Generic.EqualityComparer<global::System.String>.Default.Equals(value, _name))
							{
								OnPropertyChanging("Name");
								_name = value;
								OnPropertyChanged("Name");
							}
						}
					}
				}
			}
			""",
			"""
			// <auto-generated>
			// Auto-generated by Cornerstone.Generators
			// </auto-generated>
			internal static partial class __CornerstoneGeneratedInitializer
			{
				[global::System.Runtime.CompilerServices.ModuleInitializer]
				public static void Initialize()
				{
				}
			}
			"""
		};

		// Generated Code - /Expected

		ValidateSource(source, expected);
	}

	#endregion
}