#region References

using NUnit.Framework;

#endregion

namespace Cornerstone.Generators.UnitTests.PropertyChange;

[TestFixture]
public class PropertyChangeTests : GeneratorUnitTest
{
	#region Methods

	[Test]
	public void SourceReflectionAttribute()
	{
		var source = """
					namespace Cornerstone.Test.Models;

					public partial class SampleRecord : Notifiable
					{
						[Notify]
						public partial string Name { get; set; }
					}
					""";

		// Generated Code - Expected
		var expected = new[]
		{
			"""
			using System;
			using System.Collections.Generic;
			// <auto-generated>
			// Auto-generated by Cornerstone.Generators
			// </auto-generated>
			namespace Cornerstone.Test.Models
			{
				partial class SampleRecord
				{
					private global::System.String _name;
					public partial global::System.String Name
					{
						get => _name;
						set
						{
							if (!global::System.Collections.Generic.EqualityComparer<global::System.String>.Default.Equals(value, _name))
							{
								OnPropertyChanging("Name");
								_name = value;
								OnPropertyChanged("Name");
							}
						}
					}
				}
			}
			""",
			"""
			// <auto-generated>
			// Auto-generated by Cornerstone.Generators
			// </auto-generated>
			internal static partial class __CornerstoneSourceReflectorInitializer
			{
				[global::System.Runtime.CompilerServices.ModuleInitializer]
				public static void Initialize()
				{
				}
			}
			"""
		};
		// Generated Code - /Expected

		ValidateSource(source, expected);
	}

	#endregion
}