#region References

using Microsoft.VisualStudio.TestTools.UnitTesting;

#endregion

namespace Cornerstone.Generators.UnitTests.DependencyInjection;

[TestClass]
public class DependencyInjectedTests : GeneratorUnitTest
{
	#region Methods

	[TestMethod]
	public void MultipleAttributes()
	{
		var source = """
					namespace Cornerstone.Test.Models;

					public interface ISampleService
					{
					}

					public interface IOtherService
					{
					}

					[DependencyInjected]
					[DependencyInjected(typeof(ISampleService))]
					[DependencyInjected(typeof(IOtherService), TypeLifetime.Transient)]
					public class SampleService : ISampleService, IOtherService
					{
					}
					""";

		// Generated Code - Expected
		var expected = new[]
		{
			"""
			// <auto-generated>
			// Auto-generated by Cornerstone.Generators
			// </auto-generated>
			namespace TestCompilation
			{
				public static partial class CornerstoneGenerated
				{
					[global::System.Runtime.CompilerServices.ModuleInitializer]
					public static void Initialize()
					{
					}
				}
			}
			""",
			"""
			// <auto-generated>
			// Auto-generated by Cornerstone.Generators
			// </auto-generated>
			namespace TestCompilation
			{
				public static partial class CornerstoneGenerated
				{
					/// <summary>
					/// Registers default factory services discovered via [DependencyInjected].
					/// Call before any <c>SetSingleton</c> overrides and before first resolve.
					/// Hosts may call this for each referenced assembly (e.g. Cornerstone, Cornerstone.Avalonia).
					/// </summary>
					public static void RegisterDependencies(global::Cornerstone.Runtime.DependencyProvider provider)
					{
						if (provider == null)
						{
							throw new global::System.ArgumentNullException(nameof(provider));
						}
			
						provider.AddSingleton<global::Cornerstone.Test.Models.SampleService>();
						provider.AddTransient<global::Cornerstone.Test.Models.IOtherService, global::Cornerstone.Test.Models.SampleService>();
						provider.AddSingleton<global::Cornerstone.Test.Models.ISampleService, global::Cornerstone.Test.Models.SampleService>();
					}
				}
			}
			"""
		};
		// Generated Code - /Expected

		ValidateSource(source, expected);
	}

	[TestMethod]
	public void ServiceTypeMapping()
	{
		var source = """
					namespace Cornerstone.Test.Models;

					public interface ISampleService
					{
					}

					[DependencyInjected(typeof(ISampleService))]
					public class SampleService : ISampleService
					{
					}
					""";

		// Generated Code - Expected
		var expected = new[]
		{
			"""
			// <auto-generated>
			// Auto-generated by Cornerstone.Generators
			// </auto-generated>
			namespace TestCompilation
			{
				public static partial class CornerstoneGenerated
				{
					[global::System.Runtime.CompilerServices.ModuleInitializer]
					public static void Initialize()
					{
					}
				}
			}
			""",
			"""
			// <auto-generated>
			// Auto-generated by Cornerstone.Generators
			// </auto-generated>
			namespace TestCompilation
			{
				public static partial class CornerstoneGenerated
				{
					/// <summary>
					/// Registers default factory services discovered via [DependencyInjected].
					/// Call before any <c>SetSingleton</c> overrides and before first resolve.
					/// Hosts may call this for each referenced assembly (e.g. Cornerstone, Cornerstone.Avalonia).
					/// </summary>
					public static void RegisterDependencies(global::Cornerstone.Runtime.DependencyProvider provider)
					{
						if (provider == null)
						{
							throw new global::System.ArgumentNullException(nameof(provider));
						}
			
						provider.AddSingleton<global::Cornerstone.Test.Models.ISampleService, global::Cornerstone.Test.Models.SampleService>();
					}
				}
			}
			"""
		};
		// Generated Code - /Expected

		ValidateSource(source, expected);
	}

	[TestMethod]
	public void SingletonSelf()
	{
		var source = """
					namespace Cornerstone.Test.Models;

					[DependencyInjected]
					public class SampleService
					{
					}
					""";

		// Generated Code - Expected
		var expected = new[]
		{
			"""
			// <auto-generated>
			// Auto-generated by Cornerstone.Generators
			// </auto-generated>
			namespace TestCompilation
			{
				public static partial class CornerstoneGenerated
				{
					[global::System.Runtime.CompilerServices.ModuleInitializer]
					public static void Initialize()
					{
					}
				}
			}
			""",
			"""
			// <auto-generated>
			// Auto-generated by Cornerstone.Generators
			// </auto-generated>
			namespace TestCompilation
			{
				public static partial class CornerstoneGenerated
				{
					/// <summary>
					/// Registers default factory services discovered via [DependencyInjected].
					/// Call before any <c>SetSingleton</c> overrides and before first resolve.
					/// Hosts may call this for each referenced assembly (e.g. Cornerstone, Cornerstone.Avalonia).
					/// </summary>
					public static void RegisterDependencies(global::Cornerstone.Runtime.DependencyProvider provider)
					{
						if (provider == null)
						{
							throw new global::System.ArgumentNullException(nameof(provider));
						}
			
						provider.AddSingleton<global::Cornerstone.Test.Models.SampleService>();
					}
				}
			}
			"""
		};
		// Generated Code - /Expected

		ValidateSource(source, expected);
	}

	[TestMethod]
	public void SkipsAbstractType()
	{
		var source = """
					namespace Cornerstone.Test.Models;

					[DependencyInjected]
					public abstract class SampleServiceBase
					{
					}
					""";

		// Generated Code - Expected
		var expected = new[]
		{
			"""
			// <auto-generated>
			// Auto-generated by Cornerstone.Generators
			// </auto-generated>
			namespace TestCompilation
			{
				public static partial class CornerstoneGenerated
				{
					[global::System.Runtime.CompilerServices.ModuleInitializer]
					public static void Initialize()
					{
					}
				}
			}
			"""
		};
		// Generated Code - /Expected

		ValidateSource(source, expected);
	}

	[TestMethod]
	public void SkipsInvalidServiceMapping()
	{
		var source = """
					namespace Cornerstone.Test.Models;

					public interface IUnrelated
					{
					}

					[DependencyInjected(typeof(IUnrelated))]
					public class SampleService
					{
					}
					""";

		// Generated Code - Expected
		var expected = new[]
		{
			"""
			// <auto-generated>
			// Auto-generated by Cornerstone.Generators
			// </auto-generated>
			namespace TestCompilation
			{
				public static partial class CornerstoneGenerated
				{
					[global::System.Runtime.CompilerServices.ModuleInitializer]
					public static void Initialize()
					{
					}
				}
			}
			"""
		};
		// Generated Code - /Expected

		ValidateSource(source, expected);
	}

	[TestMethod]
	public void TransientSelf()
	{
		var source = """
					namespace Cornerstone.Test.Models;

					[DependencyInjected(TypeLifetime.Transient)]
					public class SampleService
					{
					}
					""";

		// Generated Code - Expected
		var expected = new[]
		{
			"""
			// <auto-generated>
			// Auto-generated by Cornerstone.Generators
			// </auto-generated>
			namespace TestCompilation
			{
				public static partial class CornerstoneGenerated
				{
					[global::System.Runtime.CompilerServices.ModuleInitializer]
					public static void Initialize()
					{
					}
				}
			}
			""",
			"""
			// <auto-generated>
			// Auto-generated by Cornerstone.Generators
			// </auto-generated>
			namespace TestCompilation
			{
				public static partial class CornerstoneGenerated
				{
					/// <summary>
					/// Registers default factory services discovered via [DependencyInjected].
					/// Call before any <c>SetSingleton</c> overrides and before first resolve.
					/// Hosts may call this for each referenced assembly (e.g. Cornerstone, Cornerstone.Avalonia).
					/// </summary>
					public static void RegisterDependencies(global::Cornerstone.Runtime.DependencyProvider provider)
					{
						if (provider == null)
						{
							throw new global::System.ArgumentNullException(nameof(provider));
						}
			
						provider.AddTransient<global::Cornerstone.Test.Models.SampleService>();
					}
				}
			}
			"""
		};
		// Generated Code - /Expected

		ValidateSource(source, expected);
	}

	#endregion
}