#region References

using Avalonia.Diagnostics;

#endregion

// note: this must be here due to code generated by
//		Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator
// ReSharper disable once CheckNamespace
namespace Avalonia.Controls;

/// <summary>
/// Extension methods for attaching DevTools.
/// </summary>
public static class DevToolsExtensions
{
	#region Methods

	/// <summary>
	/// Attaches DevTools to a window, to be opened with the F12 key.
	/// </summary>
	/// <param name="root"> The window to attach DevTools to. </param>
	public static void AttachDevTools(this TopLevel root)
	{
		// note: disabled auto connect from generated code
		// - Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator
		// - we do not want to auto connect.
		//DevTools.Attach(root, new DevToolsOptions());
	}

	/// <summary>
	/// Attaches DevTools to an Application, to be opened with the specified options.
	/// </summary>
	/// <param name="application"> The Application to attach DevTools to. </param>
	public static void AttachDevTools(this Application application)
	{
		DevTools.Attach(application, new DevToolsOptions());
	}

	/// <summary>
	/// Attaches DevTools to an Application, to be opened with the specified options.
	/// </summary>
	/// <param name="application"> The Application to attach DevTools to. </param>
	/// <param name="options"> Additional settings of DevTools. </param>
	/// <remarks>
	/// Attach DevTools should only be called after application initialization is complete.
	/// A good point is <see cref="Application.OnFrameworkInitializationCompleted" />
	/// </remarks>
	public static void AttachDevTools(this Application application, DevToolsOptions options)
	{
		DevTools.Attach(application, options);
	}

	#endregion
}