#region References

using Microsoft.VisualStudio.TestTools.UnitTesting;

#endregion

namespace Cornerstone.Generators.UnitTests.SourceReflection;

[TestClass]
public class ClassTests : GeneratorUnitTest
{
	#region Methods

	[TestMethod]
	public void Class()
	{
		var source = """
					namespace Cornerstone.Test.Models;

					[SourceReflection]
					public class SampleRecord
					{
						public string Name { get; set; }
						public int Age { get; set; }
						
						public void Update()
						{
						}
						
						public DateTime GetBirthday()
						{
							return DateTime.Now.AddYears(-Age);
						}
					}
					""";

		// Generated Code - Expected
		var expected = new[]
		{
			"""
			using System;
			using System.Collections.Generic;
			// <auto-generated>
			// Auto-generated by Cornerstone.Generators
			// </auto-generated>
			internal static partial class __CornerstoneGeneratedInitializer
			{
				private static readonly global::Cornerstone.Reflection.SourceTypeInfo CornerstoneTestModelsSampleRecord = new global::Cornerstone.Reflection.SourceTypeInfo()
				{
					Accessibility = global::Cornerstone.Reflection.SourceAccessibility.Public,
					Attributes = new[]
					{
						new global::Cornerstone.Reflection.SourceAttributeInfo
						{
							ConstructorArguments = [],
							FullyQualifiedName = "Cornerstone.Reflection.SourceReflectionAttribute",
							FullyGlobalQualifiedName = "global::Cornerstone.Reflection.SourceReflectionAttribute",
							Name = "SourceReflectionAttribute",
							NamedArguments = new Dictionary<string, object>(),
							Type = typeof(global::Cornerstone.Reflection.SourceReflectionAttribute)
						}
					},
					BaseType = typeof(global::System.Object),
					DeclaredConstructorsInitializer = static () => new global::Cornerstone.Reflection.SourceConstructorInfo[]
					{
						new global::Cornerstone.Reflection.SourceConstructorInfo()
						{
							Accessibility = global::Cornerstone.Reflection.SourceAccessibility.Public,
							Name = ".ctor",
							IsStatic = false,
							IsDependencyConstructor = false,
							Parameters = global::System.Array.Empty<global::Cornerstone.Reflection.SourceParameterInfo>(),
							Invoke = static (parameters) => new global::Cornerstone.Test.Models.SampleRecord()
						},
					},
					DeclaredFieldsInitializer = static () => new global::Cornerstone.Reflection.SourceFieldInfo[]
					{
						new global::Cornerstone.Reflection.SourceFieldInfo()
						{
							Accessibility = global::Cornerstone.Reflection.SourceAccessibility.Private,
							Attributes = [],
							FieldInfo = typeof(global::Cornerstone.Test.Models.SampleRecord).GetField("<Name>k__BackingField", global::System.Reflection.BindingFlags.DeclaredOnly | global::System.Reflection.BindingFlags.Instance | global::System.Reflection.BindingFlags.NonPublic),
							IsConstant = false,
							IsReadOnly = false,
							IsRequired = false,
							IsStatic = false,
							Name = "<Name>k__BackingField",
							NullableAnnotation = global::Cornerstone.Reflection.SourceNullableAnnotation.None
						},
						new global::Cornerstone.Reflection.SourceFieldInfo()
						{
							Accessibility = global::Cornerstone.Reflection.SourceAccessibility.Private,
							Attributes = [],
							FieldInfo = typeof(global::Cornerstone.Test.Models.SampleRecord).GetField("<Age>k__BackingField", global::System.Reflection.BindingFlags.DeclaredOnly | global::System.Reflection.BindingFlags.Instance | global::System.Reflection.BindingFlags.NonPublic),
							IsConstant = false,
							IsReadOnly = false,
							IsRequired = false,
							IsStatic = false,
							Name = "<Age>k__BackingField",
							NullableAnnotation = global::Cornerstone.Reflection.SourceNullableAnnotation.NotAnnotated
						},
					},
					DeclaredInterfacesInitializer = static () => global::System.Array.Empty<global::Cornerstone.Reflection.SourceInterfaceInfo>(),
					DeclaredMethodsInitializer = static () => new global::Cornerstone.Reflection.SourceMethodInfo[]
					{
						new global::Cornerstone.Reflection.SourceMethodInfo()
						{
							Name = "Update",
							Accessibility = global::Cornerstone.Reflection.SourceAccessibility.Public,
							FullyQualifiedTypeName = "Update",
							IsStatic = false,
							MethodInfo = typeof(global::Cornerstone.Test.Models.SampleRecord).GetMethod("Update", global::System.Reflection.BindingFlags.DeclaredOnly | global::System.Reflection.BindingFlags.Instance | global::System.Reflection.BindingFlags.Public, global::System.Array.Empty<global::System.Type>()),
							Attributes = [],
							Invoke = static (instance, parameters) => { ((global::Cornerstone.Test.Models.SampleRecord) instance).Update(); return null; }
						},
						new global::Cornerstone.Reflection.SourceMethodInfo()
						{
							Name = "GetBirthday",
							Accessibility = global::Cornerstone.Reflection.SourceAccessibility.Public,
							FullyQualifiedTypeName = "GetBirthday",
							IsStatic = false,
							MethodInfo = typeof(global::Cornerstone.Test.Models.SampleRecord).GetMethod("GetBirthday", global::System.Reflection.BindingFlags.DeclaredOnly | global::System.Reflection.BindingFlags.Instance | global::System.Reflection.BindingFlags.Public, global::System.Array.Empty<global::System.Type>()),
							Attributes = [],
							Invoke = static (instance, parameters) => ((global::Cornerstone.Test.Models.SampleRecord) instance).GetBirthday()
						},
					},
					DeclaredPropertiesInitializer = static () => new global::Cornerstone.Reflection.SourcePropertyInfo[]
					{
						new global::Cornerstone.Reflection.SourcePropertyInfo()
						{
							Accessibility = global::Cornerstone.Reflection.SourceAccessibility.Public,
							Attributes = [],
							CanRead = true,
							CanWrite = true,
							IsAbstract = false,
							IsDependencyInjected = false,
							IsReadOnly = false,
							IsRequired = false,
							IsStatic = false,
							IsVirtual = false,
							PropertyInfo = typeof(global::Cornerstone.Test.Models.SampleRecord).GetProperty("Name", global::System.Reflection.BindingFlags.DeclaredOnly | global::System.Reflection.BindingFlags.Instance | global::System.Reflection.BindingFlags.Public),
							Name = "Name",
							GetValue = static instance => ((global::Cornerstone.Test.Models.SampleRecord)instance).Name,
							SetValue = static (instance, value) => ((global::Cornerstone.Test.Models.SampleRecord) instance).Name = (System.String) value
						},
						new global::Cornerstone.Reflection.SourcePropertyInfo()
						{
							Accessibility = global::Cornerstone.Reflection.SourceAccessibility.Public,
							Attributes = [],
							CanRead = true,
							CanWrite = true,
							IsAbstract = false,
							IsDependencyInjected = false,
							IsReadOnly = false,
							IsRequired = false,
							IsStatic = false,
							IsVirtual = false,
							PropertyInfo = typeof(global::Cornerstone.Test.Models.SampleRecord).GetProperty("Age", global::System.Reflection.BindingFlags.DeclaredOnly | global::System.Reflection.BindingFlags.Instance | global::System.Reflection.BindingFlags.Public),
							Name = "Age",
							GetValue = static instance => ((global::Cornerstone.Test.Models.SampleRecord)instance).Age,
							SetValue = static (instance, value) => ((global::Cornerstone.Test.Models.SampleRecord) instance).Age = (System.Int32) value
						},
					},
					IsEnum = false,
					IsReadOnly = false,
					IsStatic = false,
					IsStruct = false,
					Name = "SampleRecord",
					Type = typeof(global::Cornerstone.Test.Models.SampleRecord)
				};
			};
			""",
			"""
			// <auto-generated>
			// Auto-generated by Cornerstone.Generators
			// </auto-generated>
			internal static partial class __CornerstoneGeneratedInitializer
			{
				[global::System.Runtime.CompilerServices.ModuleInitializer]
				public static void Initialize()
				{
					global::Cornerstone.Reflection.SourceReflector.Add(CornerstoneTestModelsSampleRecord);
				}
			}
			"""
		};
		// Generated Code - /Expected

		ValidateSource(source, expected);
	}

	[TestMethod]
	public void ClassWithGeneric()
	{
		var source = """
					namespace Cornerstone.Test.Models;

					[SourceReflection]
					public class SampleRecord<T>
					{
						public string Name { get; set; }
						public T Value { get; set; }
					}
					""";

		// Generated Code - Expected
		var expected = new[]
		{
			"""
			using System;
			using System.Collections.Generic;
			// <auto-generated>
			// Auto-generated by Cornerstone.Generators
			// </auto-generated>
			internal static partial class __CornerstoneGeneratedInitializer
			{
				private static readonly global::Cornerstone.Reflection.SourceTypeInfo CornerstoneTestModelsSampleRecordOfCornerstone_Test_Models_T = new global::Cornerstone.Reflection.SourceTypeInfo()
				{
					Accessibility = global::Cornerstone.Reflection.SourceAccessibility.Public,
					Attributes = new[]
					{
						new global::Cornerstone.Reflection.SourceAttributeInfo
						{
							ConstructorArguments = [],
							FullyQualifiedName = "Cornerstone.Reflection.SourceReflectionAttribute",
							FullyGlobalQualifiedName = "global::Cornerstone.Reflection.SourceReflectionAttribute",
							Name = "SourceReflectionAttribute",
							NamedArguments = new Dictionary<string, object>(),
							Type = typeof(global::Cornerstone.Reflection.SourceReflectionAttribute)
						}
					},
					BaseType = typeof(global::System.Object),
					DeclaredConstructorsInitializer = static () => new global::Cornerstone.Reflection.SourceConstructorInfo[]
					{
						new global::Cornerstone.Reflection.SourceConstructorInfo()
						{
							Accessibility = global::Cornerstone.Reflection.SourceAccessibility.Public,
							Name = ".ctor",
							IsStatic = false,
							IsDependencyConstructor = false,
							Parameters = global::System.Array.Empty<global::Cornerstone.Reflection.SourceParameterInfo>(),
						},
					},
					DeclaredFieldsInitializer = static () => new global::Cornerstone.Reflection.SourceFieldInfo[]
					{
						new global::Cornerstone.Reflection.SourceFieldInfo()
						{
							Accessibility = global::Cornerstone.Reflection.SourceAccessibility.Private,
							Attributes = [],
							FieldInfo = typeof(global::Cornerstone.Test.Models.SampleRecord<>).GetField("<Name>k__BackingField", global::System.Reflection.BindingFlags.DeclaredOnly | global::System.Reflection.BindingFlags.Instance | global::System.Reflection.BindingFlags.NonPublic),
							IsConstant = false,
							IsReadOnly = false,
							IsRequired = false,
							IsStatic = false,
							Name = "<Name>k__BackingField",
							NullableAnnotation = global::Cornerstone.Reflection.SourceNullableAnnotation.None
						},
						new global::Cornerstone.Reflection.SourceFieldInfo()
						{
							Accessibility = global::Cornerstone.Reflection.SourceAccessibility.Private,
							Attributes = [],
							FieldInfo = typeof(global::Cornerstone.Test.Models.SampleRecord<>).GetField("<Value>k__BackingField", global::System.Reflection.BindingFlags.DeclaredOnly | global::System.Reflection.BindingFlags.Instance | global::System.Reflection.BindingFlags.NonPublic),
							IsConstant = false,
							IsReadOnly = false,
							IsRequired = false,
							IsStatic = false,
							Name = "<Value>k__BackingField",
							NullableAnnotation = global::Cornerstone.Reflection.SourceNullableAnnotation.None
						},
					},
					DeclaredInterfacesInitializer = static () => global::System.Array.Empty<global::Cornerstone.Reflection.SourceInterfaceInfo>(),
					DeclaredMethodsInitializer = static () => global::System.Array.Empty<global::Cornerstone.Reflection.SourceMethodInfo>(),
					DeclaredPropertiesInitializer = static () => new global::Cornerstone.Reflection.SourcePropertyInfo[]
					{
						new global::Cornerstone.Reflection.SourcePropertyInfo()
						{
							Accessibility = global::Cornerstone.Reflection.SourceAccessibility.Public,
							Attributes = [],
							CanRead = true,
							CanWrite = true,
							IsAbstract = false,
							IsDependencyInjected = false,
							IsReadOnly = false,
							IsRequired = false,
							IsStatic = false,
							IsVirtual = false,
							PropertyInfo = typeof(global::Cornerstone.Test.Models.SampleRecord<>).GetProperty("Name", global::System.Reflection.BindingFlags.DeclaredOnly | global::System.Reflection.BindingFlags.Instance | global::System.Reflection.BindingFlags.Public),
							Name = "Name",
						},
						new global::Cornerstone.Reflection.SourcePropertyInfo()
						{
							Accessibility = global::Cornerstone.Reflection.SourceAccessibility.Public,
							Attributes = [],
							CanRead = true,
							CanWrite = true,
							IsAbstract = false,
							IsDependencyInjected = false,
							IsReadOnly = false,
							IsRequired = false,
							IsStatic = false,
							IsVirtual = false,
							PropertyInfo = typeof(global::Cornerstone.Test.Models.SampleRecord<>).GetProperty("Value", global::System.Reflection.BindingFlags.DeclaredOnly | global::System.Reflection.BindingFlags.Instance | global::System.Reflection.BindingFlags.Public),
							Name = "Value",
						},
					},
					IsEnum = false,
					IsReadOnly = false,
					IsStatic = false,
					IsStruct = false,
					Name = "SampleRecord",
					Type = typeof(global::Cornerstone.Test.Models.SampleRecord<>)
				};
			};
			""",
			"""
			// <auto-generated>
			// Auto-generated by Cornerstone.Generators
			// </auto-generated>
			internal static partial class __CornerstoneGeneratedInitializer
			{
				[global::System.Runtime.CompilerServices.ModuleInitializer]
				public static void Initialize()
				{
					global::Cornerstone.Reflection.SourceReflector.Add(CornerstoneTestModelsSampleRecordOfCornerstone_Test_Models_T);
				}
			}
			"""
		};
		// Generated Code - /Expected

		ValidateSource(source, expected);
	}

	#endregion
}