#region References

using NUnit.Framework;

#endregion

#pragma warning disable IL2026

namespace Cornerstone.Generators.UnitTests.SourceReflection;

[TestFixture]
public class EnumTests : GeneratorUnitTest
{
	#region Methods

	[Test]
	public void SourceReflectionAttribute()
	{
		var source = """
					namespace Cornerstone.Test.Models;

					[SourceReflection]
					public enum SampleEnum
					{
						[Display(Name = "Unknown", ShortName = "-1", Order = 0)]
						Unknown = 0,

						[Display(Name = "One", ShortName = "1", Order = 1)]
						One = 1,

						[Display(Name = "One", ShortName = "2", Order = 2)]
						Two = 2,

						[Display(Name = "Ten", ShortName = "10", Order = 3)]
						Ten = 10
					}
					""";

		// Generated Code - Expected
		var expected = new[]
		{
			"""
			using System;
			using System.Collections.Generic;
			// <auto-generated>
			// Auto-generated by Cornerstone.Generators
			// </auto-generated>
			internal static partial class __CornerstoneSourceReflectorInitializer
			{
				private static readonly global::Cornerstone.Reflection.SourceTypeInfo SampleEnum = new global::Cornerstone.Reflection.SourceTypeInfo()
				{
					Accessibility = global::Cornerstone.Reflection.SourceAccessibility.Public,
					Attributes = new[]
					{
						new global::Cornerstone.Reflection.SourceAttributeInfo
						{
							ConstructorArguments = [],
							FullyQualifiedName = "Cornerstone.Reflection.SourceReflectionAttribute",
							FullyGlobalQualifiedName = "global::Cornerstone.Reflection.SourceReflectionAttribute",
							Name = "SourceReflectionAttribute",
							NamedArguments = new Dictionary<string, object>(),
							Type = typeof(global::Cornerstone.Reflection.SourceReflectionAttribute)
						}
					},
					BaseType = typeof(global::System.Enum),
					DeclaredConstructorsInitializer = static () => new global::Cornerstone.Reflection.SourceConstructorInfo[]
					{
						new global::Cornerstone.Reflection.SourceConstructorInfo()
						{
							Accessibility = global::Cornerstone.Reflection.SourceAccessibility.Public,
							Name = ".ctor",
							IsStatic = false,
							IsDependencyConstructor = false,
							Parameters = global::System.Array.Empty<global::Cornerstone.Reflection.SourceParameterInfo>(),
							Invoke = static (parameters) => new global::Cornerstone.Test.Models.SampleEnum()
						},
					},
					DeclaredFieldsInitializer = static () => new global::Cornerstone.Reflection.SourceFieldInfo[]
					{
						new global::Cornerstone.Reflection.SourceFieldInfo()
						{
							Accessibility = global::Cornerstone.Reflection.SourceAccessibility.Public,
							Attributes = new[]
							{
								new global::Cornerstone.Reflection.SourceAttributeInfo
								{
									ConstructorArguments = [],
									FullyQualifiedName = "System.ComponentModel.DataAnnotations.DisplayAttribute",
									FullyGlobalQualifiedName = "global::System.ComponentModel.DataAnnotations.DisplayAttribute",
									Name = "DisplayAttribute",
									NamedArguments = new Dictionary<string, object>
									{
										{ "Name", "Unknown" },
										{ "ShortName", "-1" },
										{ "Order", 0 }
									},
									Type = typeof(global::System.ComponentModel.DataAnnotations.DisplayAttribute)
								}
							},
							FieldInfo = typeof(global::Cornerstone.Test.Models.SampleEnum).GetField("Unknown", global::System.Reflection.BindingFlags.DeclaredOnly | global::System.Reflection.BindingFlags.Static | global::System.Reflection.BindingFlags.Public),
							GetValue = static _ => global::Cornerstone.Test.Models.SampleEnum.Unknown,
							IsConstant = true,
							IsReadOnly = false,
							IsRequired = false,
							IsStatic = true,
							Name = "Unknown",
							NullableAnnotation = global::Cornerstone.Reflection.SourceNullableAnnotation.NotAnnotated
						},
						new global::Cornerstone.Reflection.SourceFieldInfo()
						{
							Accessibility = global::Cornerstone.Reflection.SourceAccessibility.Public,
							Attributes = new[]
							{
								new global::Cornerstone.Reflection.SourceAttributeInfo
								{
									ConstructorArguments = [],
									FullyQualifiedName = "System.ComponentModel.DataAnnotations.DisplayAttribute",
									FullyGlobalQualifiedName = "global::System.ComponentModel.DataAnnotations.DisplayAttribute",
									Name = "DisplayAttribute",
									NamedArguments = new Dictionary<string, object>
									{
										{ "Name", "One" },
										{ "ShortName", "1" },
										{ "Order", 1 }
									},
									Type = typeof(global::System.ComponentModel.DataAnnotations.DisplayAttribute)
								}
							},
							FieldInfo = typeof(global::Cornerstone.Test.Models.SampleEnum).GetField("One", global::System.Reflection.BindingFlags.DeclaredOnly | global::System.Reflection.BindingFlags.Static | global::System.Reflection.BindingFlags.Public),
							GetValue = static _ => global::Cornerstone.Test.Models.SampleEnum.One,
							IsConstant = true,
							IsReadOnly = false,
							IsRequired = false,
							IsStatic = true,
							Name = "One",
							NullableAnnotation = global::Cornerstone.Reflection.SourceNullableAnnotation.NotAnnotated
						},
						new global::Cornerstone.Reflection.SourceFieldInfo()
						{
							Accessibility = global::Cornerstone.Reflection.SourceAccessibility.Public,
							Attributes = new[]
							{
								new global::Cornerstone.Reflection.SourceAttributeInfo
								{
									ConstructorArguments = [],
									FullyQualifiedName = "System.ComponentModel.DataAnnotations.DisplayAttribute",
									FullyGlobalQualifiedName = "global::System.ComponentModel.DataAnnotations.DisplayAttribute",
									Name = "DisplayAttribute",
									NamedArguments = new Dictionary<string, object>
									{
										{ "Name", "One" },
										{ "ShortName", "2" },
										{ "Order", 2 }
									},
									Type = typeof(global::System.ComponentModel.DataAnnotations.DisplayAttribute)
								}
							},
							FieldInfo = typeof(global::Cornerstone.Test.Models.SampleEnum).GetField("Two", global::System.Reflection.BindingFlags.DeclaredOnly | global::System.Reflection.BindingFlags.Static | global::System.Reflection.BindingFlags.Public),
							GetValue = static _ => global::Cornerstone.Test.Models.SampleEnum.Two,
							IsConstant = true,
							IsReadOnly = false,
							IsRequired = false,
							IsStatic = true,
							Name = "Two",
							NullableAnnotation = global::Cornerstone.Reflection.SourceNullableAnnotation.NotAnnotated
						},
						new global::Cornerstone.Reflection.SourceFieldInfo()
						{
							Accessibility = global::Cornerstone.Reflection.SourceAccessibility.Public,
							Attributes = new[]
							{
								new global::Cornerstone.Reflection.SourceAttributeInfo
								{
									ConstructorArguments = [],
									FullyQualifiedName = "System.ComponentModel.DataAnnotations.DisplayAttribute",
									FullyGlobalQualifiedName = "global::System.ComponentModel.DataAnnotations.DisplayAttribute",
									Name = "DisplayAttribute",
									NamedArguments = new Dictionary<string, object>
									{
										{ "Name", "Ten" },
										{ "ShortName", "10" },
										{ "Order", 3 }
									},
									Type = typeof(global::System.ComponentModel.DataAnnotations.DisplayAttribute)
								}
							},
							FieldInfo = typeof(global::Cornerstone.Test.Models.SampleEnum).GetField("Ten", global::System.Reflection.BindingFlags.DeclaredOnly | global::System.Reflection.BindingFlags.Static | global::System.Reflection.BindingFlags.Public),
							GetValue = static _ => global::Cornerstone.Test.Models.SampleEnum.Ten,
							IsConstant = true,
							IsReadOnly = false,
							IsRequired = false,
							IsStatic = true,
							Name = "Ten",
							NullableAnnotation = global::Cornerstone.Reflection.SourceNullableAnnotation.NotAnnotated
						},
					},
					DeclaredInterfacesInitializer = static () => global::System.Array.Empty<global::Cornerstone.Reflection.SourceInterfaceInfo>(),
					DeclaredMethodsInitializer = static () => global::System.Array.Empty<global::Cornerstone.Reflection.SourceMethodInfo>(),
					DeclaredPropertiesInitializer = static () => global::System.Array.Empty<global::Cornerstone.Reflection.SourcePropertyInfo>(),
					IsEnum = true,
					IsReadOnly = false,
					IsStatic = false,
					IsStruct = false,
					Name = "SampleEnum",
					Type = typeof(global::Cornerstone.Test.Models.SampleEnum)
				};
			};
			""",
			"""
			// <auto-generated>
			// Auto-generated by Cornerstone.Generators
			// </auto-generated>
			internal static partial class __CornerstoneSourceReflectorInitializer
			{
				[global::System.Runtime.CompilerServices.ModuleInitializer]
				public static void Initialize()
				{
					global::Cornerstone.Reflection.SourceReflector.Add(SampleEnum);
				}
			}
			"""
		};
		// Generated Code - /Expected

		ValidateSource(source, expected);
	}

	#endregion
}