#region References

using Microsoft.VisualStudio.TestTools.UnitTesting;

#endregion

namespace Cornerstone.Generators.UnitTests.SourceReflection;

[TestClass]
public class RecordTests : GeneratorUnitTest
{
	#region Methods

	[TestMethod]
	public void SourceReflectionAttribute()
	{
		var source = """
					namespace Cornerstone.Test.Models;

					[SourceReflection]
					public record SampleRecord(int One, bool Enable, string Name);
					""";

		// Generated Code - Expected
		var expected = new[]
		{
			"""
			using System;
			using System.Collections.Generic;
			// <auto-generated>
			// Auto-generated by Cornerstone.Generators
			// </auto-generated>
			internal static partial class __CornerstoneGeneratedInitializer
			{
				private static readonly global::Cornerstone.Reflection.SourceTypeInfo CornerstoneTestModelsSampleRecord = new global::Cornerstone.Reflection.SourceTypeInfo()
				{
					Accessibility = global::Cornerstone.Reflection.SourceAccessibility.Public,
					Attributes = new[]
					{
						new global::Cornerstone.Reflection.SourceAttributeInfo
						{
							ConstructorArguments = [],
							FullyQualifiedName = "Cornerstone.Reflection.SourceReflectionAttribute",
							FullyGlobalQualifiedName = "global::Cornerstone.Reflection.SourceReflectionAttribute",
							Name = "SourceReflectionAttribute",
							NamedArguments = new Dictionary<string, object>(),
							Type = typeof(global::Cornerstone.Reflection.SourceReflectionAttribute)
						}
					},
					BaseType = typeof(global::System.Object),
					DeclaredConstructorsInitializer = static () => new global::Cornerstone.Reflection.SourceConstructorInfo[]
					{
						new global::Cornerstone.Reflection.SourceConstructorInfo()
						{
							Accessibility = global::Cornerstone.Reflection.SourceAccessibility.Public,
							Name = ".ctor",
							IsStatic = false,
							IsDependencyConstructor = false,
							Parameters = new global::Cornerstone.Reflection.SourceParameterInfo[]
							{
								new global::Cornerstone.Reflection.SourceParameterInfo()
								{
									Name = "One",
									HasDefaultValue = false,
									DefaultValue = null,
									IsRef = false,
									IsOut = false,
									ParameterType = typeof(global::System.Int32),
									NullableAnnotation = global::Cornerstone.Reflection.SourceNullableAnnotation.NotAnnotated
								},
								new global::Cornerstone.Reflection.SourceParameterInfo()
								{
									Name = "Enable",
									HasDefaultValue = false,
									DefaultValue = null,
									IsRef = false,
									IsOut = false,
									ParameterType = typeof(global::System.Boolean),
									NullableAnnotation = global::Cornerstone.Reflection.SourceNullableAnnotation.NotAnnotated
								},
								new global::Cornerstone.Reflection.SourceParameterInfo()
								{
									Name = "Name",
									HasDefaultValue = false,
									DefaultValue = null,
									IsRef = false,
									IsOut = false,
									ParameterType = typeof(global::System.String),
									NullableAnnotation = global::Cornerstone.Reflection.SourceNullableAnnotation.None
								},
							},
							Invoke = static (parameters) => new global::Cornerstone.Test.Models.SampleRecord((global::System.Int32) parameters[0], (global::System.Boolean) parameters[1], (global::System.String) parameters[2])
						},
						new global::Cornerstone.Reflection.SourceConstructorInfo()
						{
							Accessibility = global::Cornerstone.Reflection.SourceAccessibility.Protected,
							Name = ".ctor",
							IsStatic = false,
							IsDependencyConstructor = false,
							Parameters = new global::Cornerstone.Reflection.SourceParameterInfo[]
							{
								new global::Cornerstone.Reflection.SourceParameterInfo()
								{
									Name = "original",
									HasDefaultValue = false,
									DefaultValue = null,
									IsRef = false,
									IsOut = false,
									ParameterType = typeof(global::Cornerstone.Test.Models.SampleRecord),
									NullableAnnotation = global::Cornerstone.Reflection.SourceNullableAnnotation.NotAnnotated
								},
							},
						},
					},
					DeclaredFieldsInitializer = static () => new global::Cornerstone.Reflection.SourceFieldInfo[]
					{
						new global::Cornerstone.Reflection.SourceFieldInfo()
						{
							Accessibility = global::Cornerstone.Reflection.SourceAccessibility.Private,
							Attributes = [],
							FieldInfo = typeof(global::Cornerstone.Test.Models.SampleRecord).GetField("<One>k__BackingField", global::System.Reflection.BindingFlags.DeclaredOnly | global::System.Reflection.BindingFlags.Instance | global::System.Reflection.BindingFlags.NonPublic),
							IsConstant = false,
							IsReadOnly = true,
							IsRequired = false,
							IsStatic = false,
							Name = "<One>k__BackingField",
							NullableAnnotation = global::Cornerstone.Reflection.SourceNullableAnnotation.NotAnnotated
						},
						new global::Cornerstone.Reflection.SourceFieldInfo()
						{
							Accessibility = global::Cornerstone.Reflection.SourceAccessibility.Private,
							Attributes = [],
							FieldInfo = typeof(global::Cornerstone.Test.Models.SampleRecord).GetField("<Enable>k__BackingField", global::System.Reflection.BindingFlags.DeclaredOnly | global::System.Reflection.BindingFlags.Instance | global::System.Reflection.BindingFlags.NonPublic),
							IsConstant = false,
							IsReadOnly = true,
							IsRequired = false,
							IsStatic = false,
							Name = "<Enable>k__BackingField",
							NullableAnnotation = global::Cornerstone.Reflection.SourceNullableAnnotation.NotAnnotated
						},
						new global::Cornerstone.Reflection.SourceFieldInfo()
						{
							Accessibility = global::Cornerstone.Reflection.SourceAccessibility.Private,
							Attributes = [],
							FieldInfo = typeof(global::Cornerstone.Test.Models.SampleRecord).GetField("<Name>k__BackingField", global::System.Reflection.BindingFlags.DeclaredOnly | global::System.Reflection.BindingFlags.Instance | global::System.Reflection.BindingFlags.NonPublic),
							IsConstant = false,
							IsReadOnly = true,
							IsRequired = false,
							IsStatic = false,
							Name = "<Name>k__BackingField",
							NullableAnnotation = global::Cornerstone.Reflection.SourceNullableAnnotation.None
						},
					},
					DeclaredInterfacesInitializer = static () => new global::Cornerstone.Reflection.SourceInterfaceInfo[]
					{
						new global::Cornerstone.Reflection.SourceInterfaceInfo()
						{
							FullyGlobalQualifiedName = "global::System.IEquatable<T>",
							FullyQualifiedName = "System.IEquatable<T>",
							Name = "IEquatable"
						},
					},
					DeclaredMethodsInitializer = static () => global::System.Array.Empty<global::Cornerstone.Reflection.SourceMethodInfo>(),
					DeclaredPropertiesInitializer = static () => new global::Cornerstone.Reflection.SourcePropertyInfo[]
					{
						new global::Cornerstone.Reflection.SourcePropertyInfo()
						{
							Accessibility = global::Cornerstone.Reflection.SourceAccessibility.Protected,
							Attributes = [],
							CanRead = true,
							CanWrite = false,
							IsAbstract = false,
							IsDependencyInjected = false,
							IsReadOnly = true,
							IsRequired = false,
							IsStatic = false,
							IsVirtual = true,
							PropertyInfo = typeof(global::Cornerstone.Test.Models.SampleRecord).GetProperty("EqualityContract", global::System.Reflection.BindingFlags.DeclaredOnly | global::System.Reflection.BindingFlags.Instance | global::System.Reflection.BindingFlags.NonPublic),
							Name = "EqualityContract",
						},
						new global::Cornerstone.Reflection.SourcePropertyInfo()
						{
							Accessibility = global::Cornerstone.Reflection.SourceAccessibility.Public,
							Attributes = [],
							CanRead = true,
							CanWrite = true,
							IsAbstract = false,
							IsDependencyInjected = false,
							IsReadOnly = false,
							IsRequired = false,
							IsStatic = false,
							IsVirtual = false,
							PropertyInfo = typeof(global::Cornerstone.Test.Models.SampleRecord).GetProperty("One", global::System.Reflection.BindingFlags.DeclaredOnly | global::System.Reflection.BindingFlags.Instance | global::System.Reflection.BindingFlags.Public),
							Name = "One",
							GetValue = static instance => ((global::Cornerstone.Test.Models.SampleRecord)instance).One,
						},
						new global::Cornerstone.Reflection.SourcePropertyInfo()
						{
							Accessibility = global::Cornerstone.Reflection.SourceAccessibility.Public,
							Attributes = [],
							CanRead = true,
							CanWrite = true,
							IsAbstract = false,
							IsDependencyInjected = false,
							IsReadOnly = false,
							IsRequired = false,
							IsStatic = false,
							IsVirtual = false,
							PropertyInfo = typeof(global::Cornerstone.Test.Models.SampleRecord).GetProperty("Enable", global::System.Reflection.BindingFlags.DeclaredOnly | global::System.Reflection.BindingFlags.Instance | global::System.Reflection.BindingFlags.Public),
							Name = "Enable",
							GetValue = static instance => ((global::Cornerstone.Test.Models.SampleRecord)instance).Enable,
						},
						new global::Cornerstone.Reflection.SourcePropertyInfo()
						{
							Accessibility = global::Cornerstone.Reflection.SourceAccessibility.Public,
							Attributes = [],
							CanRead = true,
							CanWrite = true,
							IsAbstract = false,
							IsDependencyInjected = false,
							IsReadOnly = false,
							IsRequired = false,
							IsStatic = false,
							IsVirtual = false,
							PropertyInfo = typeof(global::Cornerstone.Test.Models.SampleRecord).GetProperty("Name", global::System.Reflection.BindingFlags.DeclaredOnly | global::System.Reflection.BindingFlags.Instance | global::System.Reflection.BindingFlags.Public),
							Name = "Name",
							GetValue = static instance => ((global::Cornerstone.Test.Models.SampleRecord)instance).Name,
						},
					},
					IsEnum = false,
					IsReadOnly = false,
					IsStatic = false,
					IsStruct = false,
					Name = "SampleRecord",
					Type = typeof(global::Cornerstone.Test.Models.SampleRecord)
				};
			};
			""",
			"""
			// <auto-generated>
			// Auto-generated by Cornerstone.Generators
			// </auto-generated>
			internal static partial class __CornerstoneGeneratedInitializer
			{
				[global::System.Runtime.CompilerServices.ModuleInitializer]
				public static void Initialize()
				{
					global::Cornerstone.Reflection.SourceReflector.Add(CornerstoneTestModelsSampleRecord);
				}
			}
			"""
		};
		// Generated Code - /Expected

		ValidateSource(source, expected);
	}

	#endregion
}