#region References

using Microsoft.VisualStudio.TestTools.UnitTesting;

#endregion

namespace Cornerstone.Generators.UnitTests.SourceReflection;

[TestClass]
public class SourceReflectionTypeTests : GeneratorUnitTest
{
	#region Methods

	[TestMethod]
	public void SourceReflectionAttribute()
	{
		var source = """
					[assembly: SourceReflectionType<Version>]
					""";

		// Generated Code - Expected
		var expected = new[]
		{
			"""
			using System;
			using System.Collections.Generic;
			// <auto-generated>
			// Auto-generated by Cornerstone.Generators
			// </auto-generated>
			internal static partial class __CornerstoneGeneratedInitializer
			{
				private static readonly global::Cornerstone.Reflection.SourceTypeInfo SystemVersion = new global::Cornerstone.Reflection.SourceTypeInfo()
				{
					Accessibility = global::Cornerstone.Reflection.SourceAccessibility.Public,
					Attributes = new[]
					{
						new global::Cornerstone.Reflection.SourceAttributeInfo
						{
							ConstructorArguments = [
								"mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089"
							],
							FullyQualifiedName = "System.Runtime.CompilerServices.TypeForwardedFromAttribute",
							FullyGlobalQualifiedName = "global::System.Runtime.CompilerServices.TypeForwardedFromAttribute",
							Name = "TypeForwardedFromAttribute",
							NamedArguments = new Dictionary<string, object>(),
							Type = typeof(global::System.Runtime.CompilerServices.TypeForwardedFromAttribute)
						}
					},
					BaseType = typeof(global::System.Object),
					DeclaredConstructorsInitializer = static () => new global::Cornerstone.Reflection.SourceConstructorInfo[]
					{
						new global::Cornerstone.Reflection.SourceConstructorInfo()
						{
							Accessibility = global::Cornerstone.Reflection.SourceAccessibility.Public,
							Name = ".ctor",
							IsStatic = false,
							IsDependencyConstructor = false,
							Parameters = new global::Cornerstone.Reflection.SourceParameterInfo[]
							{
								new global::Cornerstone.Reflection.SourceParameterInfo()
								{
									Name = "major",
									HasDefaultValue = false,
									DefaultValue = null,
									IsRef = false,
									IsOut = false,
									ParameterType = typeof(global::System.Int32),
									NullableAnnotation = global::Cornerstone.Reflection.SourceNullableAnnotation.NotAnnotated
								},
								new global::Cornerstone.Reflection.SourceParameterInfo()
								{
									Name = "minor",
									HasDefaultValue = false,
									DefaultValue = null,
									IsRef = false,
									IsOut = false,
									ParameterType = typeof(global::System.Int32),
									NullableAnnotation = global::Cornerstone.Reflection.SourceNullableAnnotation.NotAnnotated
								},
								new global::Cornerstone.Reflection.SourceParameterInfo()
								{
									Name = "build",
									HasDefaultValue = false,
									DefaultValue = null,
									IsRef = false,
									IsOut = false,
									ParameterType = typeof(global::System.Int32),
									NullableAnnotation = global::Cornerstone.Reflection.SourceNullableAnnotation.NotAnnotated
								},
								new global::Cornerstone.Reflection.SourceParameterInfo()
								{
									Name = "revision",
									HasDefaultValue = false,
									DefaultValue = null,
									IsRef = false,
									IsOut = false,
									ParameterType = typeof(global::System.Int32),
									NullableAnnotation = global::Cornerstone.Reflection.SourceNullableAnnotation.NotAnnotated
								},
							},
							Invoke = static (parameters) => new global::System.Version((global::System.Int32) parameters[0], (global::System.Int32) parameters[1], (global::System.Int32) parameters[2], (global::System.Int32) parameters[3])
						},
						new global::Cornerstone.Reflection.SourceConstructorInfo()
						{
							Accessibility = global::Cornerstone.Reflection.SourceAccessibility.Public,
							Name = ".ctor",
							IsStatic = false,
							IsDependencyConstructor = false,
							Parameters = new global::Cornerstone.Reflection.SourceParameterInfo[]
							{
								new global::Cornerstone.Reflection.SourceParameterInfo()
								{
									Name = "major",
									HasDefaultValue = false,
									DefaultValue = null,
									IsRef = false,
									IsOut = false,
									ParameterType = typeof(global::System.Int32),
									NullableAnnotation = global::Cornerstone.Reflection.SourceNullableAnnotation.NotAnnotated
								},
								new global::Cornerstone.Reflection.SourceParameterInfo()
								{
									Name = "minor",
									HasDefaultValue = false,
									DefaultValue = null,
									IsRef = false,
									IsOut = false,
									ParameterType = typeof(global::System.Int32),
									NullableAnnotation = global::Cornerstone.Reflection.SourceNullableAnnotation.NotAnnotated
								},
								new global::Cornerstone.Reflection.SourceParameterInfo()
								{
									Name = "build",
									HasDefaultValue = false,
									DefaultValue = null,
									IsRef = false,
									IsOut = false,
									ParameterType = typeof(global::System.Int32),
									NullableAnnotation = global::Cornerstone.Reflection.SourceNullableAnnotation.NotAnnotated
								},
							},
							Invoke = static (parameters) => new global::System.Version((global::System.Int32) parameters[0], (global::System.Int32) parameters[1], (global::System.Int32) parameters[2])
						},
						new global::Cornerstone.Reflection.SourceConstructorInfo()
						{
							Accessibility = global::Cornerstone.Reflection.SourceAccessibility.Public,
							Name = ".ctor",
							IsStatic = false,
							IsDependencyConstructor = false,
							Parameters = new global::Cornerstone.Reflection.SourceParameterInfo[]
							{
								new global::Cornerstone.Reflection.SourceParameterInfo()
								{
									Name = "major",
									HasDefaultValue = false,
									DefaultValue = null,
									IsRef = false,
									IsOut = false,
									ParameterType = typeof(global::System.Int32),
									NullableAnnotation = global::Cornerstone.Reflection.SourceNullableAnnotation.NotAnnotated
								},
								new global::Cornerstone.Reflection.SourceParameterInfo()
								{
									Name = "minor",
									HasDefaultValue = false,
									DefaultValue = null,
									IsRef = false,
									IsOut = false,
									ParameterType = typeof(global::System.Int32),
									NullableAnnotation = global::Cornerstone.Reflection.SourceNullableAnnotation.NotAnnotated
								},
							},
							Invoke = static (parameters) => new global::System.Version((global::System.Int32) parameters[0], (global::System.Int32) parameters[1])
						},
						new global::Cornerstone.Reflection.SourceConstructorInfo()
						{
							Accessibility = global::Cornerstone.Reflection.SourceAccessibility.Public,
							Name = ".ctor",
							IsStatic = false,
							IsDependencyConstructor = false,
							Parameters = new global::Cornerstone.Reflection.SourceParameterInfo[]
							{
								new global::Cornerstone.Reflection.SourceParameterInfo()
								{
									Name = "version",
									HasDefaultValue = false,
									DefaultValue = null,
									IsRef = false,
									IsOut = false,
									ParameterType = typeof(global::System.String),
									NullableAnnotation = global::Cornerstone.Reflection.SourceNullableAnnotation.NotAnnotated
								},
							},
							Invoke = static (parameters) => new global::System.Version((global::System.String) parameters[0])
						},
						new global::Cornerstone.Reflection.SourceConstructorInfo()
						{
							Accessibility = global::Cornerstone.Reflection.SourceAccessibility.Public,
							Name = ".ctor",
							IsStatic = false,
							IsDependencyConstructor = false,
							Parameters = global::System.Array.Empty<global::Cornerstone.Reflection.SourceParameterInfo>(),
							Invoke = static (parameters) => new global::System.Version()
						},
						new global::Cornerstone.Reflection.SourceConstructorInfo()
						{
							Accessibility = global::Cornerstone.Reflection.SourceAccessibility.Private,
							Name = ".ctor",
							IsStatic = false,
							IsDependencyConstructor = false,
							Parameters = new global::Cornerstone.Reflection.SourceParameterInfo[]
							{
								new global::Cornerstone.Reflection.SourceParameterInfo()
								{
									Name = "version",
									HasDefaultValue = false,
									DefaultValue = null,
									IsRef = false,
									IsOut = false,
									ParameterType = typeof(global::System.Version),
									NullableAnnotation = global::Cornerstone.Reflection.SourceNullableAnnotation.None
								},
							},
						},
					},
					DeclaredFieldsInitializer = static () => new global::Cornerstone.Reflection.SourceFieldInfo[]
					{
						new global::Cornerstone.Reflection.SourceFieldInfo()
						{
							Accessibility = global::Cornerstone.Reflection.SourceAccessibility.Private,
							Attributes = [],
							FieldInfo = typeof(global::System.Version).GetField("_Major", global::System.Reflection.BindingFlags.DeclaredOnly | global::System.Reflection.BindingFlags.Instance | global::System.Reflection.BindingFlags.NonPublic),
							IsConstant = false,
							IsReadOnly = true,
							IsRequired = false,
							IsStatic = false,
							Name = "_Major",
							NullableAnnotation = global::Cornerstone.Reflection.SourceNullableAnnotation.NotAnnotated
						},
						new global::Cornerstone.Reflection.SourceFieldInfo()
						{
							Accessibility = global::Cornerstone.Reflection.SourceAccessibility.Private,
							Attributes = [],
							FieldInfo = typeof(global::System.Version).GetField("_Minor", global::System.Reflection.BindingFlags.DeclaredOnly | global::System.Reflection.BindingFlags.Instance | global::System.Reflection.BindingFlags.NonPublic),
							IsConstant = false,
							IsReadOnly = true,
							IsRequired = false,
							IsStatic = false,
							Name = "_Minor",
							NullableAnnotation = global::Cornerstone.Reflection.SourceNullableAnnotation.NotAnnotated
						},
						new global::Cornerstone.Reflection.SourceFieldInfo()
						{
							Accessibility = global::Cornerstone.Reflection.SourceAccessibility.Private,
							Attributes = [],
							FieldInfo = typeof(global::System.Version).GetField("_Build", global::System.Reflection.BindingFlags.DeclaredOnly | global::System.Reflection.BindingFlags.Instance | global::System.Reflection.BindingFlags.NonPublic),
							IsConstant = false,
							IsReadOnly = true,
							IsRequired = false,
							IsStatic = false,
							Name = "_Build",
							NullableAnnotation = global::Cornerstone.Reflection.SourceNullableAnnotation.NotAnnotated
						},
						new global::Cornerstone.Reflection.SourceFieldInfo()
						{
							Accessibility = global::Cornerstone.Reflection.SourceAccessibility.Private,
							Attributes = [],
							FieldInfo = typeof(global::System.Version).GetField("_Revision", global::System.Reflection.BindingFlags.DeclaredOnly | global::System.Reflection.BindingFlags.Instance | global::System.Reflection.BindingFlags.NonPublic),
							IsConstant = false,
							IsReadOnly = true,
							IsRequired = false,
							IsStatic = false,
							Name = "_Revision",
							NullableAnnotation = global::Cornerstone.Reflection.SourceNullableAnnotation.NotAnnotated
						},
					},
					DeclaredInterfacesInitializer = static () => new global::Cornerstone.Reflection.SourceInterfaceInfo[]
					{
						new global::Cornerstone.Reflection.SourceInterfaceInfo()
						{
							FullyGlobalQualifiedName = "global::System.ICloneable",
							FullyQualifiedName = "System.ICloneable",
							Name = "ICloneable"
						},
						new global::Cornerstone.Reflection.SourceInterfaceInfo()
						{
							FullyGlobalQualifiedName = "global::System.IComparable",
							FullyQualifiedName = "System.IComparable",
							Name = "IComparable"
						},
						new global::Cornerstone.Reflection.SourceInterfaceInfo()
						{
							FullyGlobalQualifiedName = "global::System.IComparable<T>",
							FullyQualifiedName = "System.IComparable<T>",
							Name = "IComparable"
						},
						new global::Cornerstone.Reflection.SourceInterfaceInfo()
						{
							FullyGlobalQualifiedName = "global::System.IEquatable<T>",
							FullyQualifiedName = "System.IEquatable<T>",
							Name = "IEquatable"
						},
						new global::Cornerstone.Reflection.SourceInterfaceInfo()
						{
							FullyGlobalQualifiedName = "global::System.ISpanFormattable",
							FullyQualifiedName = "System.ISpanFormattable",
							Name = "ISpanFormattable"
						},
						new global::Cornerstone.Reflection.SourceInterfaceInfo()
						{
							FullyGlobalQualifiedName = "global::System.IFormattable",
							FullyQualifiedName = "System.IFormattable",
							Name = "IFormattable"
						},
						new global::Cornerstone.Reflection.SourceInterfaceInfo()
						{
							FullyGlobalQualifiedName = "global::System.IUtf8SpanFormattable",
							FullyQualifiedName = "System.IUtf8SpanFormattable",
							Name = "IUtf8SpanFormattable"
						},
						new global::Cornerstone.Reflection.SourceInterfaceInfo()
						{
							FullyGlobalQualifiedName = "global::System.IUtf8SpanParsable<TSelf>",
							FullyQualifiedName = "System.IUtf8SpanParsable<TSelf>",
							Name = "IUtf8SpanParsable"
						},
					},
					DeclaredMethodsInitializer = static () => new global::Cornerstone.Reflection.SourceMethodInfo[]
					{
						new global::Cornerstone.Reflection.SourceMethodInfo()
						{
							Name = "Clone",
							Accessibility = global::Cornerstone.Reflection.SourceAccessibility.Public,
							FullyQualifiedTypeName = "Clone",
							IsStatic = false,
							MethodInfo = typeof(global::System.Version).GetMethod("Clone", global::System.Reflection.BindingFlags.DeclaredOnly | global::System.Reflection.BindingFlags.Instance | global::System.Reflection.BindingFlags.Public, global::System.Array.Empty<global::System.Type>()),
							Attributes = new[]
							{
								new global::Cornerstone.Reflection.SourceAttributeInfo
								{
									ConstructorArguments = [
										1
									],
									FullyQualifiedName = "System.Runtime.CompilerServices.NullableContextAttribute",
									FullyGlobalQualifiedName = "global::System.Runtime.CompilerServices.NullableContextAttribute",
									Name = "NullableContextAttribute",
									NamedArguments = new Dictionary<string, object>(),
									Type = typeof(global::System.Runtime.CompilerServices.NullableContextAttribute)
								}
							},
							Invoke = static (instance, parameters) => ((global::System.Version) instance).Clone()
						},
						new global::Cornerstone.Reflection.SourceMethodInfo()
						{
							Name = "CompareTo",
							Accessibility = global::Cornerstone.Reflection.SourceAccessibility.Public,
							FullyQualifiedTypeName = "CompareTo",
							IsStatic = false,
							MethodInfo = typeof(global::System.Version).GetMethod("CompareTo", global::System.Reflection.BindingFlags.DeclaredOnly | global::System.Reflection.BindingFlags.Instance | global::System.Reflection.BindingFlags.Public, new global::System.Type[] { typeof(global::System.Object) }),
							Attributes = new[]
							{
								new global::Cornerstone.Reflection.SourceAttributeInfo
								{
									ConstructorArguments = [
										2
									],
									FullyQualifiedName = "System.Runtime.CompilerServices.NullableContextAttribute",
									FullyGlobalQualifiedName = "global::System.Runtime.CompilerServices.NullableContextAttribute",
									Name = "NullableContextAttribute",
									NamedArguments = new Dictionary<string, object>(),
									Type = typeof(global::System.Runtime.CompilerServices.NullableContextAttribute)
								}
							},
							Invoke = static (instance, parameters) => ((global::System.Version) instance).CompareTo((global::System.Object) parameters[0])
						},
						new global::Cornerstone.Reflection.SourceMethodInfo()
						{
							Name = "CompareTo",
							Accessibility = global::Cornerstone.Reflection.SourceAccessibility.Public,
							FullyQualifiedTypeName = "CompareTo",
							IsStatic = false,
							MethodInfo = typeof(global::System.Version).GetMethod("CompareTo", global::System.Reflection.BindingFlags.DeclaredOnly | global::System.Reflection.BindingFlags.Instance | global::System.Reflection.BindingFlags.Public, new global::System.Type[] { typeof(global::System.Version) }),
							Attributes = new[]
							{
								new global::Cornerstone.Reflection.SourceAttributeInfo
								{
									ConstructorArguments = [
										2
									],
									FullyQualifiedName = "System.Runtime.CompilerServices.NullableContextAttribute",
									FullyGlobalQualifiedName = "global::System.Runtime.CompilerServices.NullableContextAttribute",
									Name = "NullableContextAttribute",
									NamedArguments = new Dictionary<string, object>(),
									Type = typeof(global::System.Runtime.CompilerServices.NullableContextAttribute)
								}
							},
							Invoke = static (instance, parameters) => ((global::System.Version) instance).CompareTo((global::System.Version) parameters[0])
						},
						new global::Cornerstone.Reflection.SourceMethodInfo()
						{
							Name = "Equals",
							Accessibility = global::Cornerstone.Reflection.SourceAccessibility.Public,
							FullyQualifiedTypeName = "Equals",
							IsStatic = false,
							MethodInfo = typeof(global::System.Version).GetMethod("Equals", global::System.Reflection.BindingFlags.DeclaredOnly | global::System.Reflection.BindingFlags.Instance | global::System.Reflection.BindingFlags.Public, new global::System.Type[] { typeof(global::System.Object) }),
							Attributes = new[]
							{
								new global::Cornerstone.Reflection.SourceAttributeInfo
								{
									ConstructorArguments = [
										2
									],
									FullyQualifiedName = "System.Runtime.CompilerServices.NullableContextAttribute",
									FullyGlobalQualifiedName = "global::System.Runtime.CompilerServices.NullableContextAttribute",
									Name = "NullableContextAttribute",
									NamedArguments = new Dictionary<string, object>(),
									Type = typeof(global::System.Runtime.CompilerServices.NullableContextAttribute)
								}
							},
							Invoke = static (instance, parameters) => ((global::System.Version) instance).Equals((global::System.Object) parameters[0])
						},
						new global::Cornerstone.Reflection.SourceMethodInfo()
						{
							Name = "Equals",
							Accessibility = global::Cornerstone.Reflection.SourceAccessibility.Public,
							FullyQualifiedTypeName = "Equals",
							IsStatic = false,
							MethodInfo = typeof(global::System.Version).GetMethod("Equals", global::System.Reflection.BindingFlags.DeclaredOnly | global::System.Reflection.BindingFlags.Instance | global::System.Reflection.BindingFlags.Public, new global::System.Type[] { typeof(global::System.Version) }),
							Attributes = new[]
							{
								new global::Cornerstone.Reflection.SourceAttributeInfo
								{
									ConstructorArguments = [
										2
									],
									FullyQualifiedName = "System.Runtime.CompilerServices.NullableContextAttribute",
									FullyGlobalQualifiedName = "global::System.Runtime.CompilerServices.NullableContextAttribute",
									Name = "NullableContextAttribute",
									NamedArguments = new Dictionary<string, object>(),
									Type = typeof(global::System.Runtime.CompilerServices.NullableContextAttribute)
								}
							},
							Invoke = static (instance, parameters) => ((global::System.Version) instance).Equals((global::System.Version) parameters[0])
						},
						new global::Cornerstone.Reflection.SourceMethodInfo()
						{
							Name = "GetHashCode",
							Accessibility = global::Cornerstone.Reflection.SourceAccessibility.Public,
							FullyQualifiedTypeName = "GetHashCode",
							IsStatic = false,
							MethodInfo = typeof(global::System.Version).GetMethod("GetHashCode", global::System.Reflection.BindingFlags.DeclaredOnly | global::System.Reflection.BindingFlags.Instance | global::System.Reflection.BindingFlags.Public, global::System.Array.Empty<global::System.Type>()),
							Attributes = [],
							Invoke = static (instance, parameters) => ((global::System.Version) instance).GetHashCode()
						},
						new global::Cornerstone.Reflection.SourceMethodInfo()
						{
							Name = "ToString",
							Accessibility = global::Cornerstone.Reflection.SourceAccessibility.Public,
							FullyQualifiedTypeName = "ToString",
							IsStatic = false,
							MethodInfo = typeof(global::System.Version).GetMethod("ToString", global::System.Reflection.BindingFlags.DeclaredOnly | global::System.Reflection.BindingFlags.Instance | global::System.Reflection.BindingFlags.Public, global::System.Array.Empty<global::System.Type>()),
							Attributes = new[]
							{
								new global::Cornerstone.Reflection.SourceAttributeInfo
								{
									ConstructorArguments = [
										1
									],
									FullyQualifiedName = "System.Runtime.CompilerServices.NullableContextAttribute",
									FullyGlobalQualifiedName = "global::System.Runtime.CompilerServices.NullableContextAttribute",
									Name = "NullableContextAttribute",
									NamedArguments = new Dictionary<string, object>(),
									Type = typeof(global::System.Runtime.CompilerServices.NullableContextAttribute)
								}
							},
							Invoke = static (instance, parameters) => ((global::System.Version) instance).ToString()
						},
						new global::Cornerstone.Reflection.SourceMethodInfo()
						{
							Name = "ToString",
							Accessibility = global::Cornerstone.Reflection.SourceAccessibility.Public,
							FullyQualifiedTypeName = "ToString",
							IsStatic = false,
							MethodInfo = typeof(global::System.Version).GetMethod("ToString", global::System.Reflection.BindingFlags.DeclaredOnly | global::System.Reflection.BindingFlags.Instance | global::System.Reflection.BindingFlags.Public, new global::System.Type[] { typeof(global::System.Int32) }),
							Attributes = new[]
							{
								new global::Cornerstone.Reflection.SourceAttributeInfo
								{
									ConstructorArguments = [
										1
									],
									FullyQualifiedName = "System.Runtime.CompilerServices.NullableContextAttribute",
									FullyGlobalQualifiedName = "global::System.Runtime.CompilerServices.NullableContextAttribute",
									Name = "NullableContextAttribute",
									NamedArguments = new Dictionary<string, object>(),
									Type = typeof(global::System.Runtime.CompilerServices.NullableContextAttribute)
								}
							},
							Invoke = static (instance, parameters) => ((global::System.Version) instance).ToString((global::System.Int32) parameters[0])
						},
						new global::Cornerstone.Reflection.SourceMethodInfo()
						{
							Name = "TryFormat",
							Accessibility = global::Cornerstone.Reflection.SourceAccessibility.Public,
							FullyQualifiedTypeName = "TryFormat",
							IsStatic = false,
							MethodInfo = typeof(global::System.Version).GetMethod("TryFormat", global::System.Reflection.BindingFlags.DeclaredOnly | global::System.Reflection.BindingFlags.Instance | global::System.Reflection.BindingFlags.Public, new global::System.Type[] { typeof(global::System.Span<global::System.Char>), typeof(global::System.Int32) }),
							Attributes = [],
						},
						new global::Cornerstone.Reflection.SourceMethodInfo()
						{
							Name = "TryFormat",
							Accessibility = global::Cornerstone.Reflection.SourceAccessibility.Public,
							FullyQualifiedTypeName = "TryFormat",
							IsStatic = false,
							MethodInfo = typeof(global::System.Version).GetMethod("TryFormat", global::System.Reflection.BindingFlags.DeclaredOnly | global::System.Reflection.BindingFlags.Instance | global::System.Reflection.BindingFlags.Public, new global::System.Type[] { typeof(global::System.Span<global::System.Char>), typeof(global::System.Int32), typeof(global::System.Int32) }),
							Attributes = [],
						},
						new global::Cornerstone.Reflection.SourceMethodInfo()
						{
							Name = "TryFormat",
							Accessibility = global::Cornerstone.Reflection.SourceAccessibility.Public,
							FullyQualifiedTypeName = "TryFormat",
							IsStatic = false,
							MethodInfo = typeof(global::System.Version).GetMethod("TryFormat", global::System.Reflection.BindingFlags.DeclaredOnly | global::System.Reflection.BindingFlags.Instance | global::System.Reflection.BindingFlags.Public, new global::System.Type[] { typeof(global::System.Span<global::System.Byte>), typeof(global::System.Int32) }),
							Attributes = [],
						},
						new global::Cornerstone.Reflection.SourceMethodInfo()
						{
							Name = "TryFormat",
							Accessibility = global::Cornerstone.Reflection.SourceAccessibility.Public,
							FullyQualifiedTypeName = "TryFormat",
							IsStatic = false,
							MethodInfo = typeof(global::System.Version).GetMethod("TryFormat", global::System.Reflection.BindingFlags.DeclaredOnly | global::System.Reflection.BindingFlags.Instance | global::System.Reflection.BindingFlags.Public, new global::System.Type[] { typeof(global::System.Span<global::System.Byte>), typeof(global::System.Int32), typeof(global::System.Int32) }),
							Attributes = [],
						},
						new global::Cornerstone.Reflection.SourceMethodInfo()
						{
							Name = "Parse",
							Accessibility = global::Cornerstone.Reflection.SourceAccessibility.Public,
							FullyQualifiedTypeName = "Parse",
							IsStatic = true,
							MethodInfo = typeof(global::System.Version).GetMethod("Parse", global::System.Reflection.BindingFlags.DeclaredOnly | global::System.Reflection.BindingFlags.Static | global::System.Reflection.BindingFlags.Public, new global::System.Type[] { typeof(global::System.String) }),
							Attributes = new[]
							{
								new global::Cornerstone.Reflection.SourceAttributeInfo
								{
									ConstructorArguments = [
										1
									],
									FullyQualifiedName = "System.Runtime.CompilerServices.NullableContextAttribute",
									FullyGlobalQualifiedName = "global::System.Runtime.CompilerServices.NullableContextAttribute",
									Name = "NullableContextAttribute",
									NamedArguments = new Dictionary<string, object>(),
									Type = typeof(global::System.Runtime.CompilerServices.NullableContextAttribute)
								}
							},
							Invoke = static (instance, parameters) => global::System.Version.Parse((global::System.String) parameters[0])
						},
						new global::Cornerstone.Reflection.SourceMethodInfo()
						{
							Name = "Parse",
							Accessibility = global::Cornerstone.Reflection.SourceAccessibility.Public,
							FullyQualifiedTypeName = "Parse",
							IsStatic = true,
							MethodInfo = typeof(global::System.Version).GetMethod("Parse", global::System.Reflection.BindingFlags.DeclaredOnly | global::System.Reflection.BindingFlags.Static | global::System.Reflection.BindingFlags.Public, new global::System.Type[] { typeof(global::System.ReadOnlySpan<global::System.Char>) }),
							Attributes = [],
						},
						new global::Cornerstone.Reflection.SourceMethodInfo()
						{
							Name = "Parse",
							Accessibility = global::Cornerstone.Reflection.SourceAccessibility.Public,
							FullyQualifiedTypeName = "Parse",
							IsStatic = true,
							MethodInfo = typeof(global::System.Version).GetMethod("Parse", global::System.Reflection.BindingFlags.DeclaredOnly | global::System.Reflection.BindingFlags.Static | global::System.Reflection.BindingFlags.Public, new global::System.Type[] { typeof(global::System.ReadOnlySpan<global::System.Byte>) }),
							Attributes = [],
						},
						new global::Cornerstone.Reflection.SourceMethodInfo()
						{
							Name = "TryParse",
							Accessibility = global::Cornerstone.Reflection.SourceAccessibility.Public,
							FullyQualifiedTypeName = "TryParse",
							IsStatic = true,
							MethodInfo = typeof(global::System.Version).GetMethod("TryParse", global::System.Reflection.BindingFlags.DeclaredOnly | global::System.Reflection.BindingFlags.Static | global::System.Reflection.BindingFlags.Public, new global::System.Type[] { typeof(global::System.String), typeof(global::System.Version) }),
							Attributes = new[]
							{
								new global::Cornerstone.Reflection.SourceAttributeInfo
								{
									ConstructorArguments = [
										2
									],
									FullyQualifiedName = "System.Runtime.CompilerServices.NullableContextAttribute",
									FullyGlobalQualifiedName = "global::System.Runtime.CompilerServices.NullableContextAttribute",
									Name = "NullableContextAttribute",
									NamedArguments = new Dictionary<string, object>(),
									Type = typeof(global::System.Runtime.CompilerServices.NullableContextAttribute)
								}
							},
						},
						new global::Cornerstone.Reflection.SourceMethodInfo()
						{
							Name = "TryParse",
							Accessibility = global::Cornerstone.Reflection.SourceAccessibility.Public,
							FullyQualifiedTypeName = "TryParse",
							IsStatic = true,
							MethodInfo = typeof(global::System.Version).GetMethod("TryParse", global::System.Reflection.BindingFlags.DeclaredOnly | global::System.Reflection.BindingFlags.Static | global::System.Reflection.BindingFlags.Public, new global::System.Type[] { typeof(global::System.ReadOnlySpan<global::System.Char>), typeof(global::System.Version) }),
							Attributes = [],
						},
						new global::Cornerstone.Reflection.SourceMethodInfo()
						{
							Name = "TryParse",
							Accessibility = global::Cornerstone.Reflection.SourceAccessibility.Public,
							FullyQualifiedTypeName = "TryParse",
							IsStatic = true,
							MethodInfo = typeof(global::System.Version).GetMethod("TryParse", global::System.Reflection.BindingFlags.DeclaredOnly | global::System.Reflection.BindingFlags.Static | global::System.Reflection.BindingFlags.Public, new global::System.Type[] { typeof(global::System.ReadOnlySpan<global::System.Byte>), typeof(global::System.Version) }),
							Attributes = [],
						},
					},
					DeclaredPropertiesInitializer = static () => new global::Cornerstone.Reflection.SourcePropertyInfo[]
					{
						new global::Cornerstone.Reflection.SourcePropertyInfo()
						{
							Accessibility = global::Cornerstone.Reflection.SourceAccessibility.Public,
							Attributes = [],
							CanRead = true,
							CanWrite = false,
							IsAbstract = false,
							IsDependencyInjected = false,
							IsReadOnly = true,
							IsRequired = false,
							IsStatic = false,
							IsVirtual = false,
							PropertyInfo = typeof(global::System.Version).GetProperty("Major", global::System.Reflection.BindingFlags.DeclaredOnly | global::System.Reflection.BindingFlags.Instance | global::System.Reflection.BindingFlags.Public),
							Name = "Major",
							GetValue = static instance => ((global::System.Version)instance).Major,
						},
						new global::Cornerstone.Reflection.SourcePropertyInfo()
						{
							Accessibility = global::Cornerstone.Reflection.SourceAccessibility.Public,
							Attributes = [],
							CanRead = true,
							CanWrite = false,
							IsAbstract = false,
							IsDependencyInjected = false,
							IsReadOnly = true,
							IsRequired = false,
							IsStatic = false,
							IsVirtual = false,
							PropertyInfo = typeof(global::System.Version).GetProperty("Minor", global::System.Reflection.BindingFlags.DeclaredOnly | global::System.Reflection.BindingFlags.Instance | global::System.Reflection.BindingFlags.Public),
							Name = "Minor",
							GetValue = static instance => ((global::System.Version)instance).Minor,
						},
						new global::Cornerstone.Reflection.SourcePropertyInfo()
						{
							Accessibility = global::Cornerstone.Reflection.SourceAccessibility.Public,
							Attributes = [],
							CanRead = true,
							CanWrite = false,
							IsAbstract = false,
							IsDependencyInjected = false,
							IsReadOnly = true,
							IsRequired = false,
							IsStatic = false,
							IsVirtual = false,
							PropertyInfo = typeof(global::System.Version).GetProperty("Build", global::System.Reflection.BindingFlags.DeclaredOnly | global::System.Reflection.BindingFlags.Instance | global::System.Reflection.BindingFlags.Public),
							Name = "Build",
							GetValue = static instance => ((global::System.Version)instance).Build,
						},
						new global::Cornerstone.Reflection.SourcePropertyInfo()
						{
							Accessibility = global::Cornerstone.Reflection.SourceAccessibility.Public,
							Attributes = [],
							CanRead = true,
							CanWrite = false,
							IsAbstract = false,
							IsDependencyInjected = false,
							IsReadOnly = true,
							IsRequired = false,
							IsStatic = false,
							IsVirtual = false,
							PropertyInfo = typeof(global::System.Version).GetProperty("Revision", global::System.Reflection.BindingFlags.DeclaredOnly | global::System.Reflection.BindingFlags.Instance | global::System.Reflection.BindingFlags.Public),
							Name = "Revision",
							GetValue = static instance => ((global::System.Version)instance).Revision,
						},
						new global::Cornerstone.Reflection.SourcePropertyInfo()
						{
							Accessibility = global::Cornerstone.Reflection.SourceAccessibility.Public,
							Attributes = [],
							CanRead = true,
							CanWrite = false,
							IsAbstract = false,
							IsDependencyInjected = false,
							IsReadOnly = true,
							IsRequired = false,
							IsStatic = false,
							IsVirtual = false,
							PropertyInfo = typeof(global::System.Version).GetProperty("MajorRevision", global::System.Reflection.BindingFlags.DeclaredOnly | global::System.Reflection.BindingFlags.Instance | global::System.Reflection.BindingFlags.Public),
							Name = "MajorRevision",
							GetValue = static instance => ((global::System.Version)instance).MajorRevision,
						},
						new global::Cornerstone.Reflection.SourcePropertyInfo()
						{
							Accessibility = global::Cornerstone.Reflection.SourceAccessibility.Public,
							Attributes = [],
							CanRead = true,
							CanWrite = false,
							IsAbstract = false,
							IsDependencyInjected = false,
							IsReadOnly = true,
							IsRequired = false,
							IsStatic = false,
							IsVirtual = false,
							PropertyInfo = typeof(global::System.Version).GetProperty("MinorRevision", global::System.Reflection.BindingFlags.DeclaredOnly | global::System.Reflection.BindingFlags.Instance | global::System.Reflection.BindingFlags.Public),
							Name = "MinorRevision",
							GetValue = static instance => ((global::System.Version)instance).MinorRevision,
						},
						new global::Cornerstone.Reflection.SourcePropertyInfo()
						{
							Accessibility = global::Cornerstone.Reflection.SourceAccessibility.Private,
							Attributes = [],
							CanRead = true,
							CanWrite = false,
							IsAbstract = false,
							IsDependencyInjected = false,
							IsReadOnly = true,
							IsRequired = false,
							IsStatic = false,
							IsVirtual = false,
							PropertyInfo = typeof(global::System.Version).GetProperty("DefaultFormatFieldCount", global::System.Reflection.BindingFlags.DeclaredOnly | global::System.Reflection.BindingFlags.Instance | global::System.Reflection.BindingFlags.NonPublic),
							Name = "DefaultFormatFieldCount",
						},
					},
					IsEnum = false,
					IsReadOnly = false,
					IsStatic = false,
					IsStruct = false,
					Name = "Version",
					Type = typeof(global::System.Version)
				};
			};
			""",
			"""
			// <auto-generated>
			// Auto-generated by Cornerstone.Generators
			// </auto-generated>
			internal static partial class __CornerstoneGeneratedInitializer
			{
				[global::System.Runtime.CompilerServices.ModuleInitializer]
				public static void Initialize()
				{
					global::Cornerstone.Reflection.SourceReflector.Add(SystemVersion);
				}
			}
			"""
		};
		// Generated Code - /Expected

		ValidateSource(source, expected);
	}

	#endregion
}