#region References

using NUnit.Framework;

#endregion

namespace Cornerstone.Generators.UnitTests.SourceReflection;

[TestFixture]
public class SourceReflectionTypeTests : GeneratorUnitTest
{
	#region Methods

	[Test]
	public void SourceReflectionAttribute()
	{
		var source = """
					[assembly: SourceReflectionType<Version>]
					""";

		// Generated Code - Expected
		var expected = new[]
		{
			"""
			// <auto-generated>
			// Auto-generated by Cornerstone.Generators
			// </auto-generated>
			internal static partial class __CornerstoneSourceReflectorInitializer
			{
				[global::System.Runtime.CompilerServices.ModuleInitializer]
				public static void Initialize()
				{
				}
			}
			"""
		};
		// Generated Code - /Expected

		ValidateSource(source, expected);
	}

	#endregion
}