#region References

using Microsoft.VisualStudio.TestTools.UnitTesting;

#endregion

namespace Cornerstone.Generators.UnitTests.Packable;

[TestClass]
public class PackableTests : GeneratorUnitTest
{
	#region Methods

	[TestMethod]
	public void PackableAttribute()
	{
		var source = """
					namespace Cornerstone.Test.Models;

					[Packable(1, [nameof(Name), nameof(Age)])]
					[Packable(2, [nameof(Name), nameof(CreatedOn)])]
					public partial class SampleRecord
					{
						public int Age { get; set; }
						public DateTime CreatedOn { get; set; }
						public string Name { get; set; }
					}
					""";

		// Generated Code - Expected
		var expected = new[]
		{
			"""
			using System;
			using System.Collections.Generic;
			// <auto-generated>
			// Auto-generated by Cornerstone.Generators
			// </auto-generated>
			namespace Cornerstone.Test.Models
			{
				partial class SampleRecord
				{
					public virtual global::Cornerstone.Serialization.SpeedyPacket ToSpeedyPacket()
					{
						return new global::Cornerstone.Serialization.SpeedyPacket([(byte) 2, Name, CreatedOn]);
					}
					public virtual void FromSpeedyPacket(global::Cornerstone.Serialization.SpeedyPacket values)
					{
						var version = (byte) values[0];
						if (version == 1)
						{
							Name = (System.String) values[1];
							Age = (System.Int32) values[2];
						}
						if (version == 2)
						{
							Name = (System.String) values[1];
							CreatedOn = (System.DateTime) values[2];
						}
					}
				}
			}
			""",
			"""
			// <auto-generated>
			// Auto-generated by Cornerstone.Generators
			// </auto-generated>
			internal static partial class __CornerstoneGeneratedInitializer
			{
				[global::System.Runtime.CompilerServices.ModuleInitializer]
				public static void Initialize()
				{
				}
			}
			"""
		};
		// Generated Code - /Expected

		ValidateSource(source, expected);
	}
	
	[TestMethod]
	public void PackAttribute()
	{
		var source = """
					namespace Cornerstone.Test.Models;

					public partial class SampleRecord
					{
						[Pack(1, 1)]
						[Pack(2, 1)]
						public string Name { get; set; }
						
						[Pack(1, 2)]
						[Pack(2, 2)]
						public int Age { get; set; }
						
						[Pack(2, 3)]
						public DateTime CreatedOn { get; set; }
					}
					""";

		// Generated Code - Expected
		var expected = new[]
		{
			"""
			using System;
			using System.Collections.Generic;
			// <auto-generated>
			// Auto-generated by Cornerstone.Generators
			// </auto-generated>
			namespace Cornerstone.Test.Models
			{
				partial class SampleRecord
				{
					public virtual global::Cornerstone.Serialization.SpeedyPacket ToSpeedyPacket()
					{
						return new global::Cornerstone.Serialization.SpeedyPacket([(byte) 2, Name, Age, CreatedOn]);
					}
					public virtual void FromSpeedyPacket(global::Cornerstone.Serialization.SpeedyPacket values)
					{
						var version = (byte) values[0];
						if (version == 1)
						{
							Name = (System.String) values[1];
							Age = (System.Int32) values[2];
						}
						if (version == 2)
						{
							Name = (System.String) values[1];
							Age = (System.Int32) values[2];
							CreatedOn = (System.DateTime) values[3];
						}
					}
				}
			}
			""",
			"""
			// <auto-generated>
			// Auto-generated by Cornerstone.Generators
			// </auto-generated>
			internal static partial class __CornerstoneGeneratedInitializer
			{
				[global::System.Runtime.CompilerServices.ModuleInitializer]
				public static void Initialize()
				{
				}
			}
			"""
		};
		// Generated Code - /Expected

		ValidateSource(source, expected);
	}

	#endregion
}