#region References

using NUnit.Framework;

#endregion

namespace Cornerstone.Generators.UnitTests.Packable;

[TestFixture]
public class PackableTests : GeneratorUnitTest
{
	#region Methods

	[Test]
	public void PackAttribute()
	{
		var source = """
					namespace Cornerstone.Test.Models;

					public partial class SampleRecord
					{
						[Pack(1, 1)]
						public string Name { get; set; }
						
						[Pack(1, 2)]
						public int Age { get; set; }
						
						[Pack(2, 3)]
						public DateTime CreatedOn { get; set; }
					}
					""";

		// Generated Code - Expected
		var expected = new[]
		{
			"""
			using System;
			using System.Collections.Generic;
			// <auto-generated>
			// Auto-generated by Cornerstone.Generators
			// </auto-generated>
			namespace Cornerstone.Test.Models
			{
				partial class SampleRecord
				{
					public virtual global::Cornerstone.Serialization.SpeedyPacket ToSpeedyPacket()
					{
						return new global::Cornerstone.Serialization.SpeedyPacket([(byte)2,Name,Age,CreatedOn]);
					}
					public virtual void FromSpeedyPacket(global::Cornerstone.Serialization.SpeedyPacket values)
					{
						var version = (byte) values[0];
						if (version == 1)
						{
							Name = (System.String)values[1];
							Age = (System.Int32)values[2];
						}
						if (version == 2)
						{
							Name = (System.String)values[1];
							Age = (System.Int32)values[2];
							CreatedOn = (System.DateTime)values[3];
						}
					}
				}
			}
			""",
			"""
			// <auto-generated>
			// Auto-generated by Cornerstone.Generators
			// </auto-generated>
			internal static partial class __CornerstoneSourceReflectorInitializer
			{
				[global::System.Runtime.CompilerServices.ModuleInitializer]
				public static void Initialize()
				{
				}
			}
			"""
		};
		// Generated Code - /Expected

		ValidateSource(source, expected);
	}

	#endregion
}