#region References

using System;
using Cornerstone.Presentation.Media.TextFormatting.Unicode;
using Cornerstone.Presentation.UnitTests.Helpers;
using Cornerstone.Testing;
using Microsoft.VisualStudio.TestTools.UnitTesting;

#endregion

namespace Cornerstone.Presentation.UnitTests.Base.Media.TextFormatting;

/// <summary>
/// Conformance tests for <see cref="GraphemeEnumerator" /> against the Unicode
/// GraphemeBreakTest data. The trie itself is regenerated by the
/// <c> GenerateUnicodeData </c> Nuke target.
/// </summary>
[TestClass]
public class GraphemeBreakClassTrieGeneratorTests
{
	#region Fields

	private readonly ITestLog _outputHelper;

	#endregion

	#region Constructors

	public GraphemeBreakClassTrieGeneratorTests()
	{
		_outputHelper = new NullTestLog();
	}

	#endregion

	#region Methods

	[ClassDataSource(typeof(GraphemeBreakTestDataGenerator))]
	[PresentationTestMethod(Skip = "Only run when we update Unicode data.")]
	public void ShouldEnumerate(string line, int lineNumber, string grapheme, string text)
	{
		var enumerator = new GraphemeEnumerator(text);

		enumerator.MoveNext(out var g);

		var actual = text.AsSpan(g.Offset, g.Length);

		var pass = actual.Length == grapheme.Length;

		if (pass)
		{
			for (var i = 0; i < grapheme.Length; i++)
			{
				var a = grapheme[i];
				var b = actual[i];

				if (a != b)
				{
					pass = false;

					break;
				}
			}
		}

		if (!pass)
		{
			_outputHelper.WriteLine($"Failed line {lineNumber}");
			_outputHelper.WriteLine($"       Text: {text}");
			_outputHelper.WriteLine($"   Grapheme: {grapheme}");
			_outputHelper.WriteLine($"       Line: {line}");

			CornerstoneTest.IsTrue(false);
		}
	}

	[PresentationTestMethod]
	public void ShouldEnumerateOther()
	{
		const string text = "ABCDEFGHIJ";

		var enumerator = new GraphemeEnumerator(text);

		var count = 0;

		while (enumerator.MoveNext(out var grapheme))
		{
			CornerstoneTest.AreEqual(1, grapheme.Length);

			count++;
		}

		CornerstoneTest.AreEqual(10, count);
	}

	#endregion
}